### ISSUE TITLE
Unable to build solution locally

### ISSUE THREAD

**Issue by MaxFrost** [PowerShell/PSResourceGet#100]
It appears there is a package that is not available anywhere and is preventing local builds of this source
```
[fail]: OmniSharp.MSBuild.ProjectLoader
        Unable to find package NuGet.Protocol.Catalog. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
```

**Comment by alerickson** [comment]
Please add myget as a package source: 

> https://dotnet.myget.org/F/nuget-build/api/v3/index.json

**Comment by fMichaleczek** [comment]
@alerickson please add a nuget.config at the root of the repository. thank you in advance.
