### ISSUE TITLE
Register-PSResourceRepository takes a Credential, but does nothing with it

### ISSUE THREAD

**Issue by MaxFrost** [PowerShell/PSResourceGet#102]
in src/RegisterPSResourceRepository.cs, I can see that credential is accepted as a parameter, but there's no usage of it. The devblog regarding the public preview showed that -Credential was implemented in Register-PSResourceRepository.

I've also noticed that src/RepositorySettings.cs is not currently doing anything around receiving/returning credentials, so I anticipate this is a 'Not yet implemented' issue.

**Comment by SydneyhSmith** [comment]
@MaxFrost thanks you are correct in that we are currently not using the "Credential" parameter as we have not implemented a credential persistence for PSReposoitories yet...I will update blog post to clarify this

**Comment by VOVELEE** [comment]
@SydneyhSmith : According to the article below Credential persistence in Register-PSRepository is available. On the other hand your answer states that it is not implemented yet and I am a little bit confused. I spent one day troubleshooting why Find-Module doesn't work against Azure DevOps private NuGet feeds and still no luck to completely understand it.
It will be great if you can give more details about this topic :) Is persistence implemented or not? Thanks in advance.


- https://devblogs.microsoft.com/powershell/using-powershellget-with-azure-artifacts/?fbclid=IwAR3IPc12d2FUdLrYdGr_3-5Xbt9BbpjAbtGHcfDKessCSuj_Hyi0Len8uvg

**Comment by alerickson** [comment]
Hi @VOVELEE, "find-module" is the cmdlet for PowerShellGet versions 2.x.x and below. That repository can be found here:  [github.com/powershell/powershellgetv2](Https://www.github.com/powershell/powershellgetv2).  We're working on a new version of PowerShellGet that has new cmdlet names with similar functionality. Sydney's referring to the new repository when she says credential persistence isn't yet implemented.  

Please feel free to open up an issue in the PowerShellGetv2 repo and I can help you troubleshoot using credentials against Azure DevOps.

**Comment by VOVELEE** [comment]
@alerickson thanks for the clarification. I totally missed that the discussion is around PowerShellGet 3. Still the information that credential persistence is not still not available is a good one.

**Comment by SydneyhSmith** [comment]
Closing as we have removed the Credential parameter and are planning future work around credential persistence

**Comment by MaxFrost** [comment]
While not the fix I'd like, it _technically_ is a fix. Was hoping this would get done sooner than later due to the issues with working with private Azure Devops feeds and persistence with it.

Thank you for the update.

**Comment by alerickson** [comment]
We're looking at the -Credential param for Register-PSResourceRepository and credential persistence as two separate (but highly related) issues.  Register-PSResourceRepository does nothing with -Credentials because it doesn't need the credentials to register the repo (so the param is moot right now).  As for credential persistence, we will certainly implement that feature, and ideally have an option to pass in and store credentials when registering (tracking that issue here: #64 )
