### ISSUE TITLE
 Find for name with wildcard for V3 will only return first 100 responses

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#1020]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

 Find for name with wildcard for V3 will only return first 100 responses

### Expected behavior

```console
Return all of the responses
```

### Actual behavior

```console
We need to add skip and take parameters to the server level query being made to ensure we get more responses if there are more.
```

### Environment data

```powershell
beta20
```

**Comment by ThomasNieto** [comment]
While you're at it, the cmdlet should implement `SupportsPaging` so `First`, `Skip` and `IncludeTotalCount` parameters are added.
