### ISSUE TITLE
Nitpick: Why have a try statement with no catch and an empty finally block?

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#103]
https://github.com/PowerShell/PowerShellGet/blob/98aadd21b741c69ad782c6438663b18a309ff9e3/src/build.ps1#L95-L96

**Comment by SydneyhSmith** [comment]
@JustinGrote the build script isnt being used yet, were just using tasks in an Azure Dev Ops pipeline, but we will update that so it is publicly available going forward :smile:
