### ISSUE TITLE
Add the SupportsWildcard attribute to the Version parameter for Install-PSResource

### ISSUE THREAD

**Issue by sdwheeler** [PowerShell/PSResourceGet#1040]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Version parameters take wildcard input. This instance is missing the attribute.

### Expected behavior

```console
Version parameters take wildcard input.
```

### Actual behavior

```console
This instance is missing the attribute.
```

### Environment data

```powershell
PS> gmo PowerShellGet

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.20     beta20     PowerShellGet
```

**Comment by alerickson** [comment]
Resolved with #1048
