### ISSUE TITLE
Remove unused PSGet v2 properties

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#1053]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

The following properties are not used by PSGet v3.

PackageManagementProvider
PowerShellGetFormatVersion

### Expected behavior

```console
Properties are removed
```

### Actual behavior

```console
They exist
```

### Environment data

```powershell
beta 20
7.4-preview2
```

**Comment by SydneyhSmith** [comment]
We will get rid of PackageManagementProvider and make PowerShellGetFormatVersion private
