### ISSUE TITLE
Nondescriptive error when publishing

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PSResourceGet#1107]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I'm getting this error when I try to publish a new manifest:

PS /home/vivian> Publish-PSResource -Repository testPSRepo -Path ./bugbash.psd1

Publish-PSResource: Error occured while creating directory to publish: No such device or address : '/home/vivian/.pcsc10/pcscd.comm'

'/home/vivian/.pcsc10/pcscd.comm' exists though

This is the error that I got because the manifest wasn't inside a directory with the same name as the module. Maybe a more descriptive error message?

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```powershell
N/A
```

**Comment by SydneyhSmith** [comment]
<img width="1043" alt="image" src="https://github.com/PowerShell/PowerShellGet/assets/43417619/2c223a7a-fc17-4416-8657-f5c6cbbdd4b1">
I dont seem to have any issues publishing without a folder

**Comment by SydneyhSmith** [comment]
This is on MacOS, beta21
