### ISSUE TITLE
ipv6 and v4 channel switching or customized

### ISSUE THREAD

**Issue by he852100** [PowerShell/PSResourceGet#112]
When one channel times out or fails, try to obtain it from another channel. 
 Or add options for users to choose.  v4 or v6
![Screenshot_20200413_123208](https://user-images.githubusercontent.com/26913892/79092262-ed610380-7d82-11ea-9f8d-92b9c7839da8.jpg)

**Comment by JustinGrote** [comment]
@he852100 it looks like you're working directly against the API, this is probably more appropriate for the powershellgallery repository
https://github.com/PowerShell/PowerShellGallery

**Comment by he852100** [comment]
This looks more intuitive and I can't see anything using install-modlue.

**Comment by SydneyhSmith** [comment]
@he852100 can you please clarify if you are still hitting an issue? thanks!
@JustinGrote made the right suggestion here to use the PowerShellGallery
