### ISSUE TITLE
Change name of Update-ModuleManifest to Update-PSModuleManifest

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PSResourceGet#1139]
### Summary of the new feature / enhancement

Change name of Update-ModuleManifest to Update-PSModuleManifest to avoid name collision (ie when users install or update to v3 they'll need to pass in -allowclobber)

**Comment by ThomasNieto** [comment]
I don't necessarily agree with proposed change. The noun would no longer match `New-ModuleManifest`. It creates inconsistency issues. Are there breaking changes that require the name change? Requiring `-AllowClobber` for the initial install/upgrade does not warrant this change as users can pass the parameter. Users are already used to having all those filler parameters to get modules to install. Once they are on the new version the issue goes away.
