### ISSUE TITLE
Paths need to be resolved on -Path parameters

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#114]
# How to reproduce

`save-psresource -name powershellget -path ~\desktop`
Doesn't work: `Save-PSResource: Could not find a part of the path.`

`save-psresource -name powershellget -path (Resolve-Path ~\desktop)`
Works.

I recommend using the same methods that Resolve-Path uses to resolve paths prior to acting on the path argument.

**Comment by alerickson** [comment]
Addressed with the release of 3.0.0-beta3

**Comment by JustinGrote** [comment]
@alerickson tested and confirmed. Thanks!
![image](https://user-images.githubusercontent.com/15258962/82101385-3a593200-96c1-11ea-9308-2b5ebf5472e4.png)
