### ISSUE TITLE
Get-PSResource missing from 3.0.21

### ISSUE THREAD

**Issue by brainz80** [PowerShell/PSResourceGet#1158]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I'm getting the following error when running a script I've written that uses `Get-PSResource`:

```
The term 'Get-PSResource' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Running `(Get-Module PowerShellGet).ExportedCommands` I can see only the following commands are being exported:

```posh
Find-PSResource
Get-InstalledPSResource
Get-PSResourceRepository
Get-PSScriptFileInfo
Install-PSResource
New-PSScriptFile
Publish-PSResource
Register-PSResourceRepository
Save-PSResource
Set-PSResourceRepository
Test-PSScriptFile
Uninstall-PSResource
Unregister-PSResourceRepository
Update-ModuleManifest
Update-PSResource
Update-PSScriptFileInfo
```

### Expected behavior

```console
I'd expect the command to exist
```

### Actual behavior

```console
Command doesn't exist anymore after update.
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.21     beta21     PowerShellGet                       {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}

Key   : PSVersion
Value : 7.3.4
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.3.4
Name  : GitCommitId


Key   : OS
Value : Microsoft Windows 10.0.19045
Name  : OS


Key   : Platform
Value : Win32NT
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

**Comment by SydneyhSmith** [comment]
The cmdlet was renamed to be `Get-InstalledPSResource` to be consistent with v2 and reflect the behavior of the cmdlet

**Comment by ThomasNieto** [comment]
Here is the issue https://github.com/PowerShell/PowerShellGet/issues/1072 to petition to put it back to `Get-PSResource` as `Installed` is already implied with the `Get` verb. The only reason v2 had `Installed` is because `Get-Module` already existed in the core cmdlets and something different had to be used.

**Comment by peetrike** [comment]
> The cmdlet was renamed to be `Get-InstalledPSResource` to be consistent with v2 and reflect the behavior of the cmdlet

It would be nice to have alias added for compatibility with previous name.  And also warning message about renaming.  So later the alias could be dropped.

Currently I have both beta20 and beta21 module versions installed and old name loaded beta20 version of module (without any warning)

**Comment by SydneyhSmith** [comment]
Just wanted to provide an update that we have continued to have conversation on this issue and are leaning towards aliasing the command to Get-PSResource
