### ISSUE TITLE
We should introduce a -APIVersion parameter for Set-PSResourceRepository

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#1160]
### Summary of the new feature / enhancement

When a PSResourceRepository is registered, it is assigned an API version (currently  v2 or v3) there may be reasons a user wants to change or correct this version and users should not edit the Repository.xml file so we should introduce a way to update this field

**Comment by ThomasNieto** [comment]
Is the API version for NuGet or PowerShellGet?

**Comment by SydneyhSmith** [comment]
NuGet

**Comment by ThomasNieto** [comment]
I don't know much about nuget but doesn't the url determine the API version?

**Comment by SydneyhSmith** [comment]
Typically the url does determine the API version, but there are edge cases where we would not know... for example on prem ADO feed would look like local file share to us but would actually be a v3 feed
