### ISSUE TITLE
Get-PSResource doesn't support prerelease tags

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#117]
Find-PSResource works fine:
![image](https://user-images.githubusercontent.com/15258962/79175882-b6571600-7db3-11ea-9531-c376d0e73554.png)

Get-PSResource for the same installed module does not unless you explicity drop the tag. The behavior should be consistent, recommend implementing -prerelease for Get-PSResource as well as allowing it to match on tagged version strings.
![image](https://user-images.githubusercontent.com/15258962/79175939-dbe41f80-7db3-11ea-8dd3-4e3323df7aab.png)

**Comment by SydneyhSmith** [comment]
Thanks, just confirmed that I am still seeing this issue 
![image](https://user-images.githubusercontent.com/43417619/91220667-58c3c600-e6d1-11ea-91b7-680835216d74.png)

**Comment by SydneyhSmith** [comment]
We are tracking this issue here #467
