### ISSUE TITLE
Inconsistent Nuget Prerelease Version Matching to Powershell Gallery

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#118]
If a prerelease version is present, it shows up in an upper bound EVEN IF the upper bound is exclusive
Similarly, prereleases do not show up in a lower bound regardless if it is inclusive or exclusive

![image](https://user-images.githubusercontent.com/15258962/79176130-56ad3a80-7db4-11ea-92e6-de33424c0690.png)

It may be related to https://github.com/NuGet/Home/issues/6434#issuecomment-358782297

**Comment by anamnavi** [comment]
@JustinGrote I updated the issue #441 with a reasoning why this doesn't work and is actually expected behavior, so closing this issue.
