### ISSUE TITLE
Find-PSResource Minimum Inclusive Version is impossible

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#120]
Specifying a "bare" version number e.g. 2.1.0 returns that exact version, when the nuget version range spec says it should return the latest version with that as the minimum **inclusive** version.
![image](https://user-images.githubusercontent.com/15258962/79178219-7f83fe80-7db9-11ea-91d3-d023905c1382.png)

`find-psresource powershellget -version 2.1.0`
This should return 2.2.3, but returns 2.1.0

I can understand preserving this behavior to stay compatible and familiar with Find-Module, however as a result there is no way to do a direct inclusive minimum search and you have to do it sort-of indirectly e.g. `(2.999.999, 999.999.999]`

I recommend adding a `-MinimumVersion` parameter that would be inclusive minimum and familiar to PSGetv2 users

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote totally agree that this should return 2.2.3...would a minimum version inclusive make sense like [2.1.0,]?

**Comment by JustinGrote** [comment]
@SydneyhSmith I tested with the minimum inclusive and it worked as expected, so current behavior is fine:
1. User specifies a raw version `x.x.x`, it is assumed that is equivalent to `RequiredVersion` in PSGetv2
2. User specifies a nuget version-ranged version `[x.x.x,]`, that is equivalent to `MinimumVersion` in PSGetv2

As such the `minimumversion` parameter is not required anymore, however the parameter help for `-Version` needs to be *extremely clear* on this when it gets to the documentation phase, so I'll leave this issue open until that documentation is created and this can be closed with the doc merge.

**Comment by alerickson** [comment]
@anamnavi as we've been updating the documentation with NuGet version syntax we should make sure we clarify this slight difference between how we use versions and how NuGet uses versions.  I'll go through and make this update to the help documentation.
