### ISSUE TITLE
GitHub PSResourceGet gallery link is PSResourceGet not Microsoft.PowerShell.PSResourceGet 

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#1226]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

The GitHub about section links to the incorrect gallery package.

### Expected behavior

```console
https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet
```

### Actual behavior

```console
https://www.powershellgallery.com/packages/PSResourceGet
```

### Environment data

```powershell
N/A
```

**Comment by adityapatwardhan** [comment]
Fixed the link. Thanks @ThomasNieto !
