### ISSUE TITLE
Find-PSResource prerelease version ranges not correct

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#1235]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Version ranges with prerelease version are not returning the correct versions. As you can see from this version range `(2.0,2.1)` it should not return prerelease versions of 2.0.0 as that is older than 2.0.0 which I have excluded. Then it should be returning prerelease versions of 2.1.0 as those are valid in this range as they are older stable 2.1.0.

### Expected behavior

```console
Find-PSResource -Name PSReadLine -Version '(2.0,2.1)' -Prerelease

Name       Version Prerelease Repository Description
----       ------- ---------- ---------- -----------
PSReadLine 2.1.0   rc1        PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.1.0   beta2      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.1.0   beta1      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.4              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.3              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.2              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.1              PSGallery  Great command line editing in the PowerShell console host
```

### Actual behavior

```console
Find-PSResource -Name PSReadLine -Version '(2.0,2.1)' -Prerelease

Name       Version Prerelease Repository Description
----       ------- ---------- ---------- -----------
PSReadLine 2.0.4              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.3              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.2              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.1              PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   rc2        PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   rc1        PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta6      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta5      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta4      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta3      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta2      PSGallery  Great command line editing in the PowerShell console host
PSReadLine 2.0.0   beta1      PSGallery  Great command line editing in the PowerShell console host
```

### Environment data

```powershell
7.4-preview4
psresourceget beta22
```

**Comment by alerickson** [comment]
I agree that this is unexpected behavior, however, it's how NuGet handles version ranges and it looks like that's unlikely to change any time soon: https://github.com/NuGet/Home/issues/6434#issuecomment-357409519.  We could potentially create a built in workaround (similar to some of the workarounds mentioned in the linked thread).  Kind of an ugly scenario :/

**Comment by ThomasNieto** [comment]
@alerickson that issue doesn't look like the one I have brought up.

2.0.0-beta1 < 2.0.0 < 2.0.1 < 2.1.0-beta1 < 2.1.0

The range I specified is `(2.0,2.1)` which translates to exclusive min version, and exclusive max version so 2.0.1 up to 2.1 prereleases but not 2.1 stable. 2.0 prereleases should not be returned like in the issue above.

NuGet version range `Satisfies` method returns the correct value. I'm not sure if you're using this method or something else but NuGet works while PowerShellGet doesn't.

```powershell
PS C:\> [NuGet.Versioning.VersionRange]::Parse('(2.0,2.1)').Satisfies('2.0-beta1')
False
PS C:\> [NuGet.Versioning.VersionRange]::Parse('(2.0,2.1)').Satisfies('2.0')
False
PS C:\> [NuGet.Versioning.VersionRange]::Parse('(2.0,2.1)').Satisfies('2.0.1')
True
PS C:\> [NuGet.Versioning.VersionRange]::Parse('(2.0,2.1)').Satisfies('2.1-beta1')
True
PS C:\> [NuGet.Versioning.VersionRange]::Parse('(2.0,2.1)').Satisfies('2.1')
False
```

**Comment by alerickson** [comment]
Oh, yup, you're there's actually an issue with how the version ranges are parsed out into OData queries to the gallery.
