### ISSUE TITLE
Unable to install latest version from PSGallery

### ISSUE THREAD

**Issue by Rychard** [PowerShell/PSResourceGet#124]
Attempting to install the latest version of PowerShellGet (`2.2.4`) from PSGallery fails.  Installation was attempted using the command below.  The result is the same with and without the `-RequiredVersion '2.2.4'` parameter.

```PowerShell
Install-Module PowerShellGet -Scope CurrentUser -Force -AllowClobber
```

The error message is as follows:

```text
PackageManagement\Install-Package : The module 'PowerShellGet' cannot be installed because the catalog signature in
'PowerShellGet.cat' does not match the hash generated from the module.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidCatalogSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cm
   dlets.InstallPackage
```

The issue does not occur if explicitly specifying the previous version (`2.2.3`):
```PowerShell
Install-Module PowerShellGet -RequiredVersion '2.2.3' -Scope CurrentUser -Force -AllowClobber
```

Output of `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mohandatla** [comment]
We also hitting the same issue, any help would be greatly appreciated.

**Comment by alerickson** [comment]
Please add the -SkipPublishersCheck flag when installing

**Comment by brwilkinson** [comment]
Try this:

save-Module -Name PowerShellGet -RequiredVersion 2.2.4 -path $home\Desktop\

Then copy the 2 modules over to your psmodulepath directory 
E.g. C:\Program Files\WindowsPowerShell\Modules

**Comment by Rychard** [comment]
> Please add the -SkipPublishersCheck flag when installing

We've added the `-SkipPublisherCheck` as a workaround for now, and it appears to have been effective in resolving the issue.

Thanks for the quick response.

**Comment by sopelt** [comment]
@alerickson do you happen to know the reason why SkipPublisherCheck should be applied here? Is the signature of 2.2.4 broken/missing? Did a certificate change between 2.2.3 and 2.2.4? Is it a false positive?
Disabling signature checks should usually handled with care ;)

Thank you in advance.
