### ISSUE TITLE
Publish-PSResource does not take into account ExternalModuleDependencies, when checking dependencies

### ISSUE THREAD

**Issue by peetrike** [PowerShell/PSResourceGet#1245]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
New-PSScriptFileInfo -Description 'just for test' -RequiredModules @{ModuleName='Hyper-V'} -ExternalModuleDependencies 'Hyper-V' -Path test.ps1

Publish-PSResource -Path .\test.ps1 -Repository local
```

### Expected behavior

script is published

### Actual behavior

```console
publish-psresource : Dependency 'Hyper-V' was not found in repository 'local'.  Make sure the dependency is published to the repository before publishing this module.
```

### Error details

```console
Exception             :
    Type    : System.ArgumentException
    Message : Dependency 'Hyper-V' was not found in repository 'local'.  Make sure the dependency is published to the repository before publishing this module.
    HResult : -2147024809
CategoryInfo          : ObjectNotFound: (:) [Publish-PSResource], ArgumentException
FullyQualifiedErrorId : DependencyNotFound,Microsoft.PowerShell.PSResourceGet.Cmdlets.PublishPSResource
InvocationInfo        :
    MyCommand        : Publish-PSResource
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 297
    Line             : Publish-PSResource -Path .\test.ps1 -Repository local
    PositionMessage  : At line:1 char:1
                       + Publish-PSResource -Path .\test.ps1 -Repository local
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Publish-PSResource
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

PSResourceGet: 0.5.22
PowerShell: 5.1 and 7.3.5

**Comment by ThomasNieto** [comment]
This also impacts module resources.

**Comment by alerickson** [comment]
The behavior for the example here seems correct.   `-RequiredModules @{ModuleName='Hyper-V'} ` should auto import Hyper-V whenever the parent module is imported, so `Publish-PSResource` expects that dependency to be available for installation wherever the parent module is being published to.   There's the `-SkipDependenciesCheck` flag that can be passed in to bypass this check.

**Comment by ThomasNieto** [comment]
A common use case would be to define the required module and then if that module is already installed on the system as a built in module (not available on the gallery) to add it to external module dependencies to be a conditional exclusion.

The required module is necessary to have PowerShell check and auto load that module first. If the user only had it in external required modules it does not benefit from PowerShell checking dependencies on import. 

I would expect this to be an easy fix when publishing to exclude any required modules if it also exists in the external modules.

**Comment by peetrike** [comment]
> I would expect this to be an easy fix when publishing to exclude any required modules if it also exists in the external modules.

This is also the way, how `Publish-Script` works now.

**Comment by peetrike** [comment]
According to [About Requires](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_requires) document and my experience, the `#Requires` statement loads the mentioned modules before the script starts.  So I use that a lot to ensure that module (and types) are loaded before the code in script starts working.  When `Publish-PSResource` refuses to publish these scripts into local repository, it makes whole PSResourceGet module less useful.

**Comment by alerickson** [comment]
@peetrike @ThomasNieto that makes sense, we can add that check in to `Publish-PSResource`
