### ISSUE TITLE
Check for "Clobber" conflicts before trying to install everything

### ISSUE THREAD

**Issue by dbaileyut** [PowerShell/PSResourceGet#1261]
### Summary of the new feature / enhancement

If I run Install-Module with a big module with lots of dependencies like VMware.PowerCLI and I forget to specify -AllowClobber, it takes a long time to finally error out with the conflicts. It would be nice if it could fail sooner.

**Comment by ThomasNieto** [comment]
The new module PSResourceGet doesn't have the `AllowClobber` parameter and by default doesn't check for conflicts but can opt-in by using the `NoClobber` parameter.

**Comment by dbaileyut** [comment]
Ah, thanks, sorry I haven't had a chance to try the new module
