### ISSUE TITLE
Keep AllUsers Scope for updated Core scripts

### ISSUE THREAD

**Issue by echalone** [PowerShell/PSResourceGet#127]
This was a bug in the old PowerShellGetV2 repository. Since you closed that repository (but forgot to close the pull request updating the Readme.md, by the way) and the product of this repository isn't yet finished, I don't really have a way to fix the problem or make you aware of it, other than this.
So not to repeat the same mistake as with the PowerShellGetv2 repository, here's my bug report in that repository, just to make you aware of that and hopefolly not to repeat the same mistake:
https://github.com/PowerShell/PowerShellGetv2/pull/592
Although I think I and many others would highly appreaciate it if that pull request can still be closed and one last version of PowerShellGetv2 published, just to fix that PowerShell Core problem, while we're waiting for this newly developed product. Thanks :)

**Comment by SydneyhSmith** [comment]
@echalone thanks for moving this over and for raising awareness to this problem (also that we hadnt merged the README update)...we will make sure this is taken care of in v3
