### ISSUE TITLE
Find-Module returns version as type string instead of type version when running in PS7

### ISSUE THREAD

**Issue by danubie** [PowerShell/PSResourceGet#128]
I'm can't qualifiy wheter this is a PS7 or PowershellGet issue

Find-Module return type for property "version" differs between PS7 and Windows-Powershell

Steps to reproduce
`(Find-Module powershellget -Repository psgallery).Version`

PS7 result (type string)
```
2.2.4.1
```

Windows-Powershell result (type version)
```
Major  Minor  Build  Revision
-----  -----  -----  --------
2      2      4      1
```

Workaround for compatbility when using the property is to explict cast the result
`[system.version] (Find-Module powershellget -Repository psgallery).Version`

Environment
```
$PSVersionTable
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

$PSVersionTable
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by SydneyhSmith** [comment]
@danubie thanks for opening this issue, we are currently working in PowerShellGet 3.0 in this version the string is type: 
![image](https://user-images.githubusercontent.com/43417619/80766087-6d17fd80-8af9-11ea-81be-bfce8b5287a3.png)
is this what you are looking for, or would you request the Windows PowerShell Version?

**Comment by SydneyhSmith** [comment]
Closing as we have addressed inconsistency in version types with the latest release
