### ISSUE TITLE
Readme badges still refers to PowerShellGet

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#1281]
### Summary of the new feature / enhancement

Readme badges still refers to PowerShellGet documentation and gallery link.

https://github.com/PowerShell/PSResourceGet/blob/d59abfe4808b01d884e95e754b95b69bf35d6c84/README.md?plain=1#L3-L4

**Comment by LaurentDardenne** [comment]
See to  the 'Bug report' form ( new Issue ) : 
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/c25cbc0c-1292-41cc-973d-83507901abf2)

Instead _**get-module Microsoft.PowerShell.PSResourceGet**_


But this does not return the prerelease version
_ReleaseNotes: ## 0.5.22-beta22_
