### ISSUE TITLE
Find-PSResource error messages [needs design doc published]

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PSResourceGet#1286]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

1 - Create a local repository ( file system) with the name 'PSRepoLocal' *  with the same priority of PSGallery repository
2 - Publish one or more versions of a module 'XYZ' into 'PSRepoLocal' repository
3 - Use 
```Powershell
Find-PSResource -Name 'XYZ'
```

`* Note : I have not tested with a repository name 'PSABC' that influences the search order.

### Expected behavior

```console
No error when a searched module does not exist in a repository.

I'm looking to find out where the module exists, not where the module doesn't exist.
```

### Actual behavior

```console
Throw an error when a searched module do not exist into a repository
```

### Error details

```console
$error[0]|select *


writeErrorStream      : True
PSMessageDetails      :
Exception             : System.Management.Automation.PSInvalidOperationException: Package with search criteria: Name
                        lowercase could not be found due to: Package does not exist on the server..
TargetObject          : Microsoft.PowerShell.PSResourceGet.Cmdlets.FindHelper
CategoryInfo          : NotSpecified: (Microsoft.Power...lets.FindHelper:FindHelper) [Find-PSResource],
                        PSInvalidOperationException
FullyQualifiedErrorId : FindNameResponseConversionFail,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : à <ScriptBlock>, <Aucun fichier> : ligne 1
PipelineIterationInfo : {0, 1}




$StackTrace
   à System.Management.Automation.ParameterBinderController.ReparseUnboundArguments()
   à System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
   à System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
   à System.Management.Automation.CommandProcessor.BindCommandLineParameters()
   à System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   à System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   à System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   à System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   à System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   à System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

### Environment data

```powershell
Get-Module Microsoft.PowerShell.PSResourceGet

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.5.22     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceR...


$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.3031}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/0bf943ac-d4ff-46dc-b674-fb959c56bd75)

**Comment by LaurentDardenne** [comment]
In this scenario the Save-PSResource cmdlet seems to have identical behavior:
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/f450f46d-72d4-44fa-bb1a-ea6b28208b6f)

**Comment by LaurentDardenne** [comment]
Another scenario, a module with the same name ('String') exists in two repositories which have the same priority. But the version numbers of the modules differ.
The search is therefore done on a version number :
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/d1a743a7-ee8b-48b0-a51e-5e9c7991077a)

Here the error message is more technical than functional:
 _Response didn't contain properties element._

**Comment by alerickson** [comment]
Hi @LaurentDardenne, there's a few different issues going on here:
1)  The original issue regarding `Find-PSResource`-- I do think it makes sense to not have an error message displayed if a package is found in any repository and that we should fix this.
2) The error with `Save-PSResource` -- this is expected behavior for both `Save-PSResource` and `Install-PSResource`.  Both cmdlets use the highest priority repository to find the package.  If two or more repositories have the same priority, it then uses alphabetical ordering or search through the first repository.
3) The error with `Find-PSResource` not containing property elements -- again, this is just a bug given that it's both available and that the error message is not descriptive.

**Comment by SydneyhSmith** [comment]
We discussed this issue and we came to this expected behavior:
1. Find should by default search all repositories in priority order and not provide error messages if not found 
2. Save/Install should search until the package is found, in order of priority 

for issue 3 @LaurentDardenne could you please see if this reproduces with beta 23

**Comment by SydneyhSmith** [comment]
Note that we will need to update docs and tests

**Comment by LaurentDardenne** [comment]
@SydneyhSmith 
> for issue 3 at LaurentDardenne could you please see if this reproduces with beta 23

Yes of course.

**Comment by LaurentDardenne** [comment]
Test for issue 3 with Beta23
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/486159b9-9430-45a8-a62d-d619fe9a6784)

Find module by version :
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/d845dc6d-7748-4e71-beee-1aa82d2d73be)

Error :
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/e7383d76-4de2-418d-ad63-5dad288b06f0)

If needed here is the archive containing the nuget packages of my tests.
[PSRepoLocal.zip](https://github.com/PowerShell/PSResourceGet/files/12249212/PSRepoLocal.zip)

**Comment by SydneyhSmith** [comment]
We have open PRs for this, I am also making a note here that we plan to blog about expected error behavior for Find, and well as publish a design doc for it in this repo...we will later determine if either of these should be added to official docs
