### ISSUE TITLE
Prerelease modules not installing via install-psresource

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#130]
Looks like it basically ignores the prerelease versions.

![image](https://user-images.githubusercontent.com/15258962/80766019-45c13080-8af9-11ea-89a9-fa8b215b61e3.png)

Works fine with both save-psresource and find-psresource, but not install-psresource

**Comment by JustinGrote** [comment]
In addition, if a prerelease module is installed, running install-psresource without prerelease tag will not install the latest non-prerelease version. Specifying Version and using nuget syntax to exclude the prerelease version range will work.

**Comment by alerickson** [comment]
Hmm, that's strange, I was planning on fixing this today but I can't repro.   Install isn't doesn't return anything... it's not showing up when you run 'Get-PSResource powercd' ?  Can you try running the install command with -Repository PSGallery ?

**Comment by JustinGrote** [comment]
I can't reproduce either now, so closing, will reopen if I can reproduce.
