### ISSUE TITLE
Undateable help files aren't being published

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PSResourceGet#1307]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Get-Help Find-PSResource

help info returned would be better for user help experience if it included:
Examples
Description
Synopsis
Parameters also lack descriptions

### Expected behavior

```console
See above
```

### Actual behavior

```console
Currently missing examples and other helpful info.
```

### Environment data

```powershell
0.5.23-beta23
```

**Comment by anamnavi** [comment]
Also in this doc: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/find-psresource?view=powershellget-3.x

It would be helpful if Example 3 had a description for how the VersionRange in that scenario operates, and link to the Package Versioning doc that is listed in -Version param section below. Or allude to it being there for more info (i.e "For more information on Version and accepted version range values/combinations, see the -Version parameter section below")

**Comment by LaurentDardenne** [comment]
>>Parameters also lack descriptions

See to _-Priority_  https://github.com/MicrosoftDocs/PowerShell-Docs-PSGet/issues/47

**Comment by sdwheeler** [comment]
@anamnavi Two things:
1. This issue should be in MicrosoftDocs/PowerShell-Docs-PSGet. The cmdlets are fully documented, but if there is room for improvement or needed examples, please add them to the docs repo.
2. It looks like the updateable help files aren't being published. I need to investigate that.

**Comment by SydneyhSmith** [comment]
> 2. It looks like the updateable help files aren't being published. I need to investigate that.

@sdwheeler should I open an issue for that in the PowerShellGet docs repo or do we want to track that here?

**Comment by sdwheeler** [comment]
The CI job was not configured since moving the Docs to the new repo. It's fixed now.
