### ISSUE TITLE
Update-ModuleManifest makes unintended changes

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PSResourceGet#1308]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

I downloaded the bicep package nupkg from PSGallery, and extracted and obtained the .psd1

Update-ModuleManifest -Path ./bicep.psd1 -Version "3.0.0"

### Expected behavior

```console
It should just update the ModuleVersion field in the .psd1.
```

### Actual behavior

```console
It updates the following which is unintended:
- CompanyName (was previously commented out and now it's uncommented out)
- Tags (the "@()" array syntax around them is removed, so this will fail parsing later on)
- Prerelease (was previously commented out and now it's uncommented out)

Also -Prerelease "  " can be passed as valid input, but should not be able to. We should follow sem version guidelines for what a prerelease string can contain ideally.
```

### Environment data

```powershell
0.5.23-beta23
```

**Comment by adityapatwardhan** [comment]
I verified that the issue repros with Microsoft.PowerShell.PSResourceGet - `Update-PSModuleManifest`

**Comment by anamnavi** [comment]
For the second issue, the changes to `tags` entry in the module manifest is by design of `New-ModuleManifest`. `Update-PSModuleManifest` calls `New-ModuleManifest` (for which the param type is string[] for the following params: Tags, CompatiblePSEditions, CmdletsToExport, FunctionsToExport, VariablesToExport, AliasesToExport, and a handful of other parameters, [per docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-7.3)). 

If a user generates the module manifest with `New-ModuleManifest` these parameters will be have their values listed as a string array without the `@()` syntax around the array (unless it was an empty entry and then the value is just `@()`). Since `New-ModuleManifest` is owned by the PowerShell project to change is it out of scope/design for PSResourceGet. At any rate it should not stop the user from being able to publish with that module manifest.

**Comment by anamnavi** [comment]
For the first issue, [per the docs ](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-modulemanifest?view=powershell-7.3#-companyname)for `New-ModuleManifest`, if you omit or comment out the entry for `CompanyName`, when `Update-PSModuleManifest` calls into `New-ModuleManifest` it will create a CompanyName entry with a value of "Unknown".

**Comment by anamnavi** [comment]
For the third issue, I've added checks to ensure `Prerelease` value cannot be empty string or whitespace. I couldn't reproduce the issue of it uncommenting out a prerelease value. If a user has a module manifest with Prerelease entry like:
 `# Prerelease = 'preview1'` it will change it to `# Prerelease = ''`
