### ISSUE TITLE
Install-PSResource should support -Whatif

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#131]
SupportsShouldProcess should be added.

Whatif should have target defined as the module and version e.g.
`2.0.0-beta1`

And the message as "Installing Module to Scope <Scope>"

So the resulting whatif message would be:

What if: Performing the operation "Install Module to Scope CurrentUser" on target "Pester 5.0.0-beta1".

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
