### ISSUE TITLE
*-Resource and *-ResourceRepository cmdlets should support -PassThru

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#132]
Install-PSResource, if `-PassThru` is specified, it should return the same object that Get-PSResource for the same item does. This will enable it to be easier to both verify an installation, and pass the object to other commands (e.g. import module).

**Comment by ThomasNieto** [comment]
I didn't see this one when I created #158 for `-PassThru` parameter on all applicable cmdlets.

**Comment by ThomasNieto** [comment]
@SydneyhSmith the scope of this issue will need to be expanded to cover the other issue I opened for the other cmdlets.

**Comment by SydneyhSmith** [comment]
Thanks for calling that out @ThomasNieto just updated the title to make sure we keep that in mind

**Comment by anamnavi** [comment]
Register-PSResourceRepository -> supports PassThru
Set-PSResourceRepository         -> supports PassThru
Unregister-PSResourceRepository -> add support

Install-PSResource    -> supports PassThru
Update-PSResource  -> supports PassThru
Save-PSResource      -> supports PassThru

**Comment by SydneyhSmith** [comment]
Re-looking at this issue and wanted to clarify the scenario for pass thru with Install-PSResource? This would return information about the object on the PowerShell Gallery rather than information on the installed resource. @JustinGrote Thanks!

**Comment by JustinGrote** [comment]
It should return information about the installed resource, preferably a `psmoduleinfo`, to support scenarios like:

`Install-PSResource 'MyModule' | Import-Module`

**Comment by alerickson** [comment]
Pass thru still needs to be supported for Unregister-PSResourceRepository, but is currently supported for everything else.
