### ISSUE TITLE
Feature Request: Update-Module without parameters should identify module/repository

### ISSUE THREAD

**Issue by LarsFosdal** [PowerShell/PSResourceGet#136]
When you run Update-Module without parameters, it runs through the installed modules and asks you to confirm installation if the InstallationPolicy dictates so.

Unfortunately, it does not display which module it is currently working on, nor the name of the repository.

It would be desirable if the confirmation also did a Write-Host of the module name and repository name before you confirm.

Example: A number of updates happened - but it is not possible to see which module was installed - except from during the progress bar display.

![image](https://user-images.githubusercontent.com/7009177/81144007-7a0e7400-8f73-11ea-8ab4-9c3f432a5fe6.png)

Suggestion - Output something like
```
Untrusted repository "repository name" for module "module name"
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository
cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A

```

**Comment by SydneyhSmith** [comment]
![image](https://user-images.githubusercontent.com/43417619/173813241-52a701ff-22f9-494d-866e-00d163c742ce.png)
I believe this work is only partially complete-- shows the repository name which is great but doesnt show the module name
