### ISSUE TITLE
Set-PSResourceRepository -Name PSGallery -Trusted:$true breaks the Repository

### ISSUE THREAD

**Issue by BohrenAn** [PowerShell/PSResourceGet#1360]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

Changing the PSResourceRepository somehow breaks the Repositroy. You can't search afterwards the Repository.

Get-PSResourceRepository
Name      Uri                                      Trusted Priority
----      ---                                      ------- --------
PSGallery https://www.powershellgallery.com/api/v2 False   50

Find-PSResource Get-Mailprotection -Type Script
Name               Version Prerelease Repository Description
----               ------- ---------- ---------- -----------
Get-Mailprotection 1.6                PSGallery  This Script checks diffrent DNS Records about a Domain - mostly about Mailsecurity Settings....

#Now we change the Status to Trusted
Set-PSResourceRepository -Name PSGallery -Trusted:$true

#At this point we can't query the Repository
Find-PSResource Get-Mailprotection -Type Script
ind-PSResource : Repository 'PSGallery' is not a known repository type that is supported. Please file an issue for support at
https://github.com/PowerShell/PSResourceGet/issues
At line:1 char:1
+ Find-PSResource Get-Mailprotection -Type Script
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...lets.FindHelper:FindHelper) [Find-PSResource], PSInvalidOperationException
    + FullyQualifiedErrorId : RepositoryApiVersionUnknown,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource

#Even if we switch it back
Set-PSResourceRepository -Name PSGallery -Trusted:$false

#Can't query the Repository
Find-PSResource Get-Mailprotection -Type Script
Find-PSResource : Repository 'PSGallery' is not a known repository type that is supported. Please file an issue for support at
https://github.com/PowerShell/PSResourceGet/issues
At line:1 char:1
+ Find-PSResource Get-Mailprotection -Type Script
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...lets.FindHelper:FindHelper) [Find-PSResource], PSInvalidOperationException
    + FullyQualifiedErrorId : RepositoryApiVersionUnknown,Microsoft.PowerShell.PSResourceGet.Cmdlets.FindPSResource

#Only way to fix it is Unregister/Register PSGallery
Unregister-PSResourceRepository -Name PSGallery
Register-PSResourceRepository -PSGallery
Find-PSResource Get-Mailprotection -Type Script

### Expected behavior

```console
Set-PSResourceRepository -Name PSGallery -Trusted:$true
Set-PSResourceRepository -Name PSGallery -Trusted:$false

Does not break the Repository
```

### Actual behavior

```console
Set-PSResourceRepository -Name PSGallery -Trusted:$true
Set-PSResourceRepository -Name PSGallery -Trusted:$false

Does break the Repository
```

### Environment data

```powershell
Get-Module Microsoft.PowerShell.PSResourceGet; $PSVersionTable

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.5.23     Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInf...

Key   : PSVersion
Value : 5.1.22621.1778
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.22621.1778
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### Visuals

![image](https://github.com/PowerShell/PSResourceGet/assets/45082822/05da722c-2983-4319-815a-9dacd502274a)

**Comment by SydneyhSmith** [comment]
Thanks @BohrenAn this is fixed in our latest release, beta24, it was resolved in PR #1310 ...you should be able to try it out now
