### ISSUE TITLE
Dependencies in PSResourceGet in PowerShell 7.4 LTS

### ISSUE THREAD

**Issue by dy-nz** [PowerShell/PSResourceGet#1397]
### Summary of the new feature / enhancement

Hi. 
I am unclear as to whether support for dependencies, for example nuget dependencies, will exist in PSResourceGet when it is released in PowerShell 7.4 LTS. The PSResourceGet rc1 module currently writes Warning messages for any Dependency, Without such support it will be difficult to complete side by side test of PSResourceGet vs legacy commands. 
Could someone please advise. 
Thanks, David

**Comment by SydneyhSmith** [comment]
@dy-nz we support module dependencies, but not nuget dependencies from nuget.org-- PowerShellGet also did not support nuget.og at all, or any v3 repositories

Thanks for the question! 

Could you share what isn't working in v3 that was working in v2? It would be great to know what you are seeing

**Comment by dy-nz** [comment]
Hi Sydney

thanks for the prompt response (as always ! ).

I went back and checked my scripts. 
You are correct - on all points.

I guess I was hoping that since PSResourceGet supported some aspects of nuget resourcing that it would fully treat nuget packages in the same was as Powershell modules, DSC resources etc, thus allowing the PackageManagement module to be deprecated.

Cheers.
