### ISSUE TITLE
[v3] Install-PSResource Installs Prerelease module folders with tag, which is not recognized by Get-Module

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#141]
This does not occur on Linux as far as I can tell, interesting enough.

Result of `Install-PSresource Pester -version '[4.999,]'`
![image](https://user-images.githubusercontent.com/15258962/81961457-4365d880-95c7-11ea-92e8-3fd5f54dbcfc.png)
![image](https://user-images.githubusercontent.com/15258962/81961491-4f519a80-95c7-11ea-8dbd-550d4f9eadce.png)

If I rename the folder to just "5.0.0"
![image](https://user-images.githubusercontent.com/15258962/81961556-5f697a00-95c7-11ea-87b5-7e68c01e3ddc.png)
![image](https://user-images.githubusercontent.com/15258962/81961570-66908800-95c7-11ea-9423-43bba41196de.png)

```
command get-command

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-Command                                        7.0.0.0    Microsoft.PowerShell.Core
```

### Resolution

1. Ideally PS7.1 would have Get-Module updated to also search for "prerelease" folder paths, so we can have more than one prerelease installed at a time. However, to maintain backwards compatibility PowershellGet should for now save with only the "base" version number, and once Get-Module can support it, add a switch option such as `-asprerelease` to allow installing 
 with the "fully qualified" module name.

**Comment by JustinGrote** [comment]
@SydneyhSmith I noticed you closed this but put it on the TO-Do. It's not fixed so maybe it should be left open?

example of it not working:
`install-psresource exchangeonlinemanagement -Prerelease -Verbose`
![image](https://user-images.githubusercontent.com/15258962/91100737-90236b80-e61a-11ea-8411-db59f0dd71d1.png)

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote  we made this update in beta7 https://github.com/PowerShell/PowerShellGet/commit/e1d709c47af239d4d2f4663a10663f3bf38b888a#diff-48e6112b761b57b4dbd7f7550c0e4305R568 ...what version are you running?

**Comment by JustinGrote** [comment]
Still reproducible on beta 8
```powershell
gmo powershellget

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.0      beta8      PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceR…
```

**Comment by alerickson** [comment]
@JustinGrote is get-module still not picking the module up?

**Comment by JustinGrote** [comment]
@alerickson Nope:
![image](https://user-images.githubusercontent.com/15258962/91105930-404aa180-e626-11ea-98b1-f76539f5c2e9.png)

You'd have to either update `get-module` in powershell core to also recognize "version-tag" folders (breaking backwards compatibility below 7.1), or you won't be able to include the prerelease in folder names. Version folders for modules must cast to `system.version` to be considered currently.

It's the "-tag" part that is breaking it. You remove that and it works fine, but then you can't do side-by-side previews
![image](https://user-images.githubusercontent.com/15258962/91106003-71c36d00-e626-11ea-88ae-5378a56570d6.png)


EDIT: For comparison after just renaming the folder:
![image](https://user-images.githubusercontent.com/15258962/91106170-ded70280-e626-11ea-9fce-eb0339541ad2.png)

**Comment by joeyaiello** [comment]
This looks like it's still reproing on `3.0.0-beta10`:

```
C:\Users\jaiello> Install-psresource -Name Microsoft.PowerShell.SecretStore -Repository PSGallery -Prerelease

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its Trusted value by
running the Set-PSResourceRepository cmdlet. Are you sure you want to install the PSresource from 'PSGallery' ?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
C:\Users\jaiello> gmo -li *secret*

    Directory: C:\Users\jaiello\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     0.5.3      preview4   Microsoft.PowerShell.SecretManagem… Core      {Register-SecretVault, Unregister-Secre…

    Directory: C:\Users\jaiello\Documents\PowerShell\Modules\Microsoft.PowerShell.SecretStore\0.5.2-preview2

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.0                   Microsoft.PowerShell.SecretStore.E… Desk      {Set-Secret, Get-Secret, Remove-Secret,…
```

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
