### ISSUE TITLE
Anything with RequiredResource fails silently

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSResourceGet#1411]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

I thought I was supposed to be able to run commands like this:

```PowerShell
Install-PSResource -RequiredResourceFile .\RequiredModules.psd1
Install-PSResource -RequiredResource @{ Pester = "[5.3.0,6.0)" }
```

But this does not do anything, and when I run it with `-Verbose` it does not show something like this:
`Installed package Pester 5.5.0 is already available.`

When I try something ridiculous like this:

```PowerShell
Install-PSResource -RequiredResource @{
    ModuleName = "There is No Module With This Name"
    ModuleVersion = "A.B.C"
}
```

The same _nothing_ happens.

### Expected behavior

```console
Missing modules should be installed
```

### Actual behavior

```console
Nothing
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     0.9.0      rc1        Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo…}


Name                           Value
----                           -----
PSVersion                      7.4.0-preview.5
PSEdition                      Core
GitCommitId                    7.4.0-preview.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anamnavi** [comment]
@Jaykul thanks for creating this issue and helping catch some bugs!

For `-RequiredResource` parameter format we follow the below format, [per the docs]([url](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/install-psresource?view=powershellget-3.x#example-5)):
`Install-PSResource -RequiredResource  @{
    Pester = @{
        version = '[0.0.1,1.3.0]'
        repository = 'PSGallery'
      }
}`

In running `Install-PSResource` with that example, I ran into some bugs which I've fixed but this syntax should now fully work.

You could also provide parameters with powershell splatting, assuming they have correct parameter names.
