### ISSUE TITLE
[beta3] Install-PSResource -RequiredResource

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#146]
Trying the examples from the RFC, I can't get any to work, the matching doesn't seem to be operating. Am I doing the syntax incorrectly?

![image](https://user-images.githubusercontent.com/15258962/82367421-a2ad5980-99c8-11ea-8004-a9af56c1f03f.png)

**Comment by alerickson** [comment]
Sydney and I just [updated the RFC](https://github.com/PowerShell/PowerShell-RFC/blob/b118eca8edb56a4988dd1072b208cd8dbbfebe76/2-Draft-Accepted/RFCxxxx-PowerShellGet-3.0.md#dependencies-and-version-management) yesterday, try using single quotes instead of double

**Comment by JustinGrote** [comment]
Doesn't json require double quotes?
https://www.json.org/json-en.html

Also I'm doing this by passing a hashtable to requiredresource, so singlequotes shouldn't matter (it's just how it evaluates).

I see that you're accepting RequiredResource as a [Object], are you expecting to support multiple object types like a string, etc.?

**Comment by JustinGrote** [comment]
I did finally get it to work as a json string (using double quotes):
`install-psresource -verbose -RequiredResource '{"Configuration": "[1.3.1,2.0)"}'`

However saving that same string to a file did not work, note that it said the parameter I used was `RequiredResource` when I clearly used `RequiredResourceFile`
![image](https://user-images.githubusercontent.com/15258962/82376872-a2688a80-99d7-11ea-9b9b-b90022a2a814.png)

So the scenarios so far are:

- [ ] RequiredResource as HashTable
- [x] RequiredResource as JSON String
- [ ] RequiredResourceFile as Json File


Hashtable-to-string workaround also works:
`Install-PSResource -RequiredResource ([String](@{Configuration='[1.3.1,2.0)'} | ConvertTo-Json -Compress)) -verbose`

**Comment by SydneyhSmith** [comment]
@JustinGrote thanks again for the detailed feedback, after chatting with Amber we have worked through the scenarios and hope to get this fixed up, in addition we discussed the need for better error messaging about what may be wrong with the format provided by the user.
