### ISSUE TITLE
Add -Online to Import-Module

### ISSUE THREAD

**Issue by markdmac** [PowerShell/PSResourceGet#1470]
### Summary of the new feature / enhancement

Add an option for -Online when importing a module so the module loaded is always the most recent version without needing to install it on the server or workstation.

### Proposed technical implementation details (optional)

Import-Module AZ.ConnectedMachine -Online

This would connect to the latest version of the module and import it in a PowerShell script.

**Comment by SydneyhSmith** [comment]
Import is handled by PowerShell so the change will need to happen there
