### ISSUE TITLE
Install-PSResource failed with error Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by pdestree** [PowerShell/PSResourceGet#1493]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

We use a local JFROG Artifactory to proxy request to Powershell Gallery.
When we register the repository by forcing to V2 ApiVersion, find-module can find all modules but Name is empty.
Is we try to install the module, we get the error : Install-PSResource : Object reference not set to an instance of an object.
Using the URL for V3 ApiVersion works in some ways but all modules from Powershell Gallery cannot be installed. We needs to use V2 protocol

### Expected behavior

```console
PS C:\WINDOWS\system32> find-Module Microsoft.PowerShell.PSResourceGet -Repository PowershellGallery

Name                                Prerelease Version    Repository           Description                                                                                                                            
----                                ---------- -------    ----------           -----------                                                                                                                            
Microsoft.PowerShell.PSResourceGet             1.0.1      PowershellGallery    PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, Scripts,...
PS C:\WINDOWS\system32> Install-Module -Name Microsoft.PowerShell.PSResourceGet -Repository PowershellGallery

PS C:\WINDOWS\system32>
```

### Actual behavior

```console
PS C:\WINDOWS\system32> find-PSResource -Name Microsoft.PowerShell.PSResourceGet -Repository PowershellGallery

Name Version Prerelease Repository        Description                                                                                                                    
---- ------- ---------- ----------        -----------                                                                                                                    
     1.0.1              PowershellGallery PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, ...
PS C:\WINDOWS\system32> Install-PSResource -Name Microsoft.PowerShell.PSResourceGet -Repository PowershellGallery
Install-PSResource : Object reference not set to an instance of an object.
At line:1 char:1
+ Install-PSResource -Name Microsoft.PowerShell.PSResourceGet -Reposito ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-PSResource], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
 

PS C:\WINDOWS\system32>
```

### Error details

```console
PSMessageDetails      : 
Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.InstallVersion(String packageName, String version, ErrorRecord& errRecord)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.InstallPackage(String packageName, String packageVersion, Boolean 
                        includePrerelease, ErrorRecord& errRecord)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.BeginPackageInstall(VersionType searchVersionType, NuGetVersion specificVersion, 
                        VersionRange versionRange, String pkgNameToInstall, PSRepositoryInfo repository, ServerApiCall currentServer, ResponseUtil currentResponseUtil, 
                        String tempInstallPath, Hashtable packagesHash, ErrorRecord& errRecord)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.InstallPackages(String[] pkgNamesToInstall, PSRepositoryInfo repository, 
                        ServerApiCall currentServer, ResponseUtil currentResponseUtil, ScopeType scope, Boolean skipDependencyCheck, FindHelper findHelper)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.ProcessRepositories(String[] repository, Boolean trustRepository, Boolean 
                        skipDependencyCheck, ScopeType scope)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.BeginInstallPackages(String[] names, VersionRange versionRange, NuGetVersion 
                        nugetVersion, VersionType versionType, String versionString, Boolean prerelease, String[] repository, Boolean acceptLicense, Boolean quiet, 
                        Boolean reinstall, Boolean force, Boolean trustRepository, Boolean noClobber, Boolean asNupkg, Boolean includeXml, Boolean skipDependencyCheck, 
                        Boolean authenticodeCheck, Boolean savePkg, List`1 pathsToInstallPkg, Nullable`1 scope, String tmpPath, HashSet`1 pkgsInstalled)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource.ProcessInstallHelper(String[] pkgNames, String pkgVersion, Boolean 
                        pkgPrerelease, String[] pkgRepository, PSCredential pkgCredential, InstallPkgParams reqResourceParams)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Install-PSResource], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
PS C:\WINDOWS\system32> Get-Module Microsoft.PowerShell.PSResourceGet; $PSVersionTable

ModuleType Version    Name                                ExportedCommands                                                                                               
---------- -------    ----                                ----------------                                                                                               
Binary     1.0.1      Microsoft.PowerShell.PSResourceGet  {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Get-PSScriptFileInfo...}                  

Key   : PSVersion
Value : 5.1.20348.2110
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.20348.2110
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by RavitejaVangala** [comment]
We are also facing the same issue when we are trying to install the published package from Git Hub. we have used the below command with the PSCredential object using the username and git hub token 

`Install-PSResource -Name @('XXX') -Version '1.1.0' -Repository @('PowerShell-Packages') -Credential $BuiltCredentialObject` 

![image](https://github.com/PowerShell/PSResourceGet/assets/103105400/e2ae662d-2f94-481a-9b30-a883c52ccb02)

**Comment by anamnavi** [comment]
@pdestree @RavitejaVangala thanks for creating this issue and sharing these scenarios, we will work to fix this for Install-PSResource.

**Comment by adityapatwardhan** [comment]
@RavitejaVangala I am unable to reproduce the error. Can you give us the full stack trace?

**Comment by RavitejaVangala** [comment]
> @RavitejaVangala I am unable to reproduce the error. Can you give us the full stack trace?

We don't have full trace for the error, it just display a single line error as shown in the image

**Comment by piet0273** [comment]
PSMessageDetails      : 
Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.InstallVersion(String packageName, String version, ErrorRecord& errRecord)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.V2ServerAPICalls.InstallPackage(String packageName, String packageVersion, Boolean 
                        includePrerelease, ErrorRecord& errRecord)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.BeginPackageInstall(VersionType searchVersionType, NuGetVersion specificVersion, 
                        VersionRange versionRange, String pkgNameToInstall, PSRepositoryInfo repository, ServerApiCall currentServer, ResponseUtil currentResponseUtil, 
                        String tempInstallPath, Hashtable packagesHash, ErrorRecord& errRecord)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.InstallPackages(String[] pkgNamesToInstall, PSRepositoryInfo repository, 
                        ServerApiCall currentServer, ResponseUtil currentResponseUtil, ScopeType scope, Boolean skipDependencyCheck, FindHelper findHelper)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.ProcessRepositories(String[] repository, Boolean trustRepository, Boolean 
                        skipDependencyCheck, ScopeType scope)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallHelper.BeginInstallPackages(String[] names, VersionRange versionRange, NuGetVersion 
                        nugetVersion, VersionType versionType, String versionString, Boolean prerelease, String[] repository, Boolean acceptLicense, Boolean quiet, 
                        Boolean reinstall, Boolean force, Boolean trustRepository, Boolean noClobber, Boolean asNupkg, Boolean includeXml, Boolean skipDependencyCheck, 
                        Boolean authenticodeCheck, Boolean savePkg, List`1 pathsToInstallPkg, Nullable`1 scope, String tmpPath, HashSet`1 pkgsInstalled)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource.ProcessInstallHelper(String[] pkgNames, String pkgVersion, Boolean 
                        pkgPrerelease, String[] pkgRepository, PSCredential pkgCredential, InstallPkgParams reqResourceParams)
                           at Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Install-PSResource], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.PSResourceGet.Cmdlets.InstallPSResource
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
