### ISSUE TITLE
404 in repo README

### ISSUE THREAD

**Issue by KUTlime** [PowerShell/PSResourceGet#150]
A link to documentation in the main repo README.md leads to 404 in section [Get PowerShellGet Module](https://github.com/PowerShell/PowerShellGet/tree/master#get-powershellget-module). 

The link https://aka.ms/installing-psget leads nowhere.
It should probably lead to https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget

**Comment by SydneyhSmith** [comment]
Thanks @KUTlime I have updated it to a live link
