### ISSUE TITLE
Discussion - regarding PSCONFEU PowerShellGet 3.0 questions for the community

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSResourceGet#153]
Since you asked to have this discussion in the GitHub repo ... :-)

I would prefer having a `Save-PSResource` cmdlet and not have a `-DestinationPath` parameter on `Install-PSResource`.  I believe those are two semantically different actions that shouldn't be provided by Install-PSResource alone.  

As for credentials, I don' want to have to specify credentials on every invocation of a command.  Package managers like npm/Conan provide a way to [adduser](https://docs.npmjs.com/cli/adduser) for each repo where you can specify your credentials once, that gets stored (quasi) securely in a file and those credentials are used by default afterward.  

RE `Install-PSResource -Force` parameter, I was wondering why you still need it if both conditions are handled by new parameters i.e. `-TrustRepository` and `-Reinstall`.  I would probably remove it until you find a need for it. Or I suppose you could make `-Force` be a shortcut for providing both -TrustRepository and -Reinstall.  

RE dependencies, in the vein of **"just make it work"**, I think those need to be installed by default.  Presumably running `Install-PSResource foo -WhatIf` would show me what dependencies would be installed.  

As for making it easier to migrate to v3, I still believe having an alias function `Install-Module -> Install-PSResource -Type Module` would help with the muscle memory.

**Comment by SydneyhSmith** [comment]
Thanks again for all the feedback @rkeithhill very much appreciated!
