### ISSUE TITLE
Install-PSResource did not install module and is silent about it

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSResourceGet#154]
I tried to install PSReadLine 2.1.0-beta2 like so:
```
06-06 13:42:09 6> Install-PSResource PSReadLine -Prerelease -TrustRepository
```
And got no output so I assumed it installed.  But no, it apparently didn't.  When I run this with `-Verbose` I see this:
```
06-06 13:42:40 7> Install-PSResource PSReadLine -Prerelease -TrustRepository -Verbose
VERBOSE: Current user scope installation path: C:\Users\Keith\Documents\PowerShell
VERBOSE: All users scope installation path: C:\Program Files\PowerShell
VERBOSE: Scope is: CurrentUser
```
If Install-PSResource didn't actually install the module I'd like to at least see a message (or warning) along those lines.

This is on PSGet 3.0.0-beta4 running on PS 7.0.1 on Windows 10 2004.  Also, I had PSRL 2.1.0-beta1 installed with PSGet 2.2.x in `~\Documents\PowerShell\Modules\PSReadLine\2.1.0`.  It appears something also installed PSRL directly in `~\Documents\PowerShell\Modules\PSReadLine`.  Anyway, I removed the PSRL folder and tried again:
```
06-06 14:13:32 1> Install-PSResource PSReadLine -Prerelease -TrustRepository -Verbose
VERBOSE: Current user scope installation path: C:\Users\Keith\Documents\PowerShell
VERBOSE: All users scope installation path: C:\Program Files\PowerShell
VERBOSE: Scope is: CurrentUser
VERBOSE: Verbose statement
```
This time it installed into `~\Documents\PowerShell\Modules\PSReadLine\2.1.0-betat2`.  Yay.  So I'm not sure exactly what this command did earlier when PSRL 2.1.0-beta1 was installed but it did not install anything i.e. PS still loaded 2.1.0-beta1.

Argh!  Now neither PS 7.0.1 nor PS 7.1.0-preview3 will load from that `2.1.0-beta2` directory. Off to rename it to remove the `-beta2`.  Dang! I liked that naming convention because it allows installing new prerelease versions without running into "file in use" conflicts.

**Comment by JustinGrote** [comment]
Here's an example of it happening to me with Pester, may have something to do with the Publisher check since it's a diff publisher from the native:
![image](https://user-images.githubusercontent.com/15258962/85208447-76e20400-b2e5-11ea-944d-9ca5e9658ffd.png)

I'd recommend after a module is installed that PSGet at least do a quick Test-Path on the .psd1 module to make sure it was actually installed, otherwise it should throw a "Something happened" error instead of silently failing.

**Comment by MartinHBA** [comment]
same for me, it's just stuck forever

**Comment by MartinHBA** [comment]
@SydneyhSmith is this issue to be addressed? why it has tag "resolved-3.0"? is it resolved somewhere?

**Comment by alerickson** [comment]
@MartinHBA it'll be resolved for our GA release... it's a slightly confusing tag

**Comment by SydneyhSmith** [comment]
Thanks, we have added a message for when it installs and most situations where it wouldn't but will add an additional check at the end to verify installation

**Comment by rkeithhill** [comment]
@SydneyhSmith This happens during `update-psresource` as well:
```
10-17 14:25:03 3> Update-PSResource Microsoft.PowerShell.SecretStore

10-17 14:25:29 4> Update-PSResource Microsoft.PowerShell.SecretStore -Verbose
VERBOSE: Scope is: CurrentUser
VERBOSE: Could not find package 'Microsoft.PowerShell.SecretStore' in repository 'PSGallery'
```
I shouldn't have to specify `-verbose` to see that the command did nothing because it couldn't find the package.

**Comment by alerickson** [comment]
Believe #497 should be looked at with this as well.
