### ISSUE TITLE
No GitHub Release for PSResourceGet v1.0.2

### ISSUE THREAD

**Issue by sean-r-williams** [PowerShell/PSResourceGet#1553]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

PSResourceGet [v1.0.2](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet/1.0.2) was uploaded to PowerShell Gallery this morning, but no corresponding release exists on GitHub. This means individuals interacting with the module's GitHub repo (including watchers) won't be notified of the updated version

### Expected behavior

```console
Git tag/GitHub release created alongside releases being uploaded to PowerShell Gallery
```

### Actual behavior

```console
GitHub/PSGallery are out of sync
```

### Environment data

```powershell
N/A
```

**Comment by hbuckle** [comment]
The GitHub changelog only goes up to 1.0.0 as well

**Comment by SydneyhSmith** [comment]
Thanks for opening this issue-- release is out now https://github.com/PowerShell/PSResourceGet/releases/tag/v1.0.2 and changelog will be merged soon
