### ISSUE TITLE
Update-PSResource Requires Name Parameter

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#157]
In PowerShellGet v2 you're able to run `Update-Module` without passing any parameters to update all installed modules. PowerShellGet v3 `Update-PSResource` has `Name` as a required parameter not allowing for all resources to be updated with one command.

Request - Restore PowerShell v2 update logic where if no name is passed all resources are updated.

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
