### ISSUE TITLE
Cmdlets should output concrete types

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#159]
Right now all the cmdlets return a `PSCustomObject`. They should return a concrete type.

**Comment by SydneyhSmith** [comment]
We plan to have the concrete types implemented in the next release however the find refactor which will surface these changes in the find experience will not be completed until the following release

**Comment by alerickson** [comment]
This will be addressed with Preview 11.  All of the *-PSRepository and *-PSResource cmdlets now have concrete types.
