### ISSUE TITLE
Get-PSResourceRepository in non-elevated prompt can't see repos that were registered in an elevated prompt

### ISSUE THREAD

**Issue by nbarnwell** [PowerShell/PSResourceGet#1596]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

1. `Register-PSResourceRepository` in elevated session
2. Close/reopen elevated session, `Get-PSResourceRepository` returns the PSGallery and the new repository
3. Open non-elevated session, invoke `Get-PSResourceRepository`

### Expected behavior

```console
Both repositories are listed.
```

### Actual behavior

```console
Only the PSGallery repository is listed.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
Thanks @nbarnwell what is the output of `gmo` in both consoles? And `Get-Command Get-PSResourceRepository`
