### ISSUE TITLE
Link for PSResourceGet on PowerShell Gallery directs to PowerShellGet project

### ISSUE THREAD

**Issue by joshcorr** [PowerShell/PSResourceGet#1610]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

From [PowerShellGallery](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet/1.0.3) for this module the "Project Site" link does not correctly link to this repo.

### Expected behavior

```console
"Project Site" redirects to https://github.com/PowerShell/PSResourceGet
```

### Actual behavior

```console
"Project Site" redirects to https://github.com/PowerShell/PowerShellGet
```

### Error details

```console
n/a
```

### Environment data

```powershell
n/a
```

**Comment by joshcorr** [comment]
Believe the root of the issue is this link in the resource that needs to be updated.
 https://github.com/PowerShell/PSResourceGet/blob/abfbf4222ef9a4c170b42e9c77df801040c69937/src/Microsoft.PowerShell.PSResourceGet.psd1#L55

**Comment by kilasuit** [comment]
> Believe the root of the issue is this link in the resource that needs to be updated.
> 
> https://github.com/PowerShell/PSResourceGet/blob/abfbf4222ef9a4c170b42e9c77df801040c69937/src/Microsoft.PowerShell.PSResourceGet.psd1#L55

Noted this and LicenseURI are still pointing to PowerShellGet, have added a PR for both

**Comment by joshcorr** [comment]
Thanks @kilasui for the PR, but I was thinking that the team may need to generate a new go link for this in case the destination changes in the future. (Like a msdn -> docs -> learn situation)

**Comment by SydneyhSmith** [comment]
Should get updated today, thanks everyone

**Comment by alerickson** [comment]
Links are updated now!  Thanks for opening the issue @joshcorr!
