### ISSUE TITLE
[Beta5] BROKEN - Will not load due to incorrect loading path

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#167]
@SydneyhSmith @alerickson for visibility.

It appears you are consolidating all module files into a single folder on build. If so you need to update the PSM DLL paths as well. Recommend you delist beta5 immediately, it's broken for all users.

https://github.com/PowerShell/PowerShellGet/blob/1f1a1406f1b2cbd3ef96a4f41d57d258dbbc0ac5/PSModule.psm1#L8-L17

![image](https://user-images.githubusercontent.com/15258962/86391303-6ec38600-bc4e-11ea-9811-eb8f1078b911.png)

**Comment by alerickson** [comment]
Hi @JustinGrote, when did you install beta5?  I had to change the build pipeline due to internal compliance issues but republished beta5 last night to fix that file structure.  I've unlisted beta5 until this is resolved.

**Comment by JustinGrote** [comment]
It must be cached on the CDN because I downloaded it again after you republished last night with the same result.

**Comment by JustinGrote** [comment]
I would just publish a beta6 if that's the case.

**Comment by JustinGrote** [comment]
Fixed with the beta6 publish.
