### ISSUE TITLE
Group Policy for a PSRepository Allow List/Registered List 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#1696]
### Summary of the new feature / enhancement

The group policy will register repositories as the only repositories allowed to be installed from if the policy is enabled. 
If the policy is enabled no other repositories will be allowed. 

The policy will take in a list of repositories, at minimum a name;uri pair or a full hashtable (or json may be preferred) of repository information. 

The policy will initially be Windows only but we will explore enabling on non-Windows via Intune policy and file system. 

The policy will be checked at each call to a repository, we will assume same privileges for all operations. 

There will also be a function/api that will expose if the policy is enabled and what repository Uris are available so that other tools which call PSResourceGet (such as WinGet) can integrate to this functionality. 

If an exact repo is specified that is not allowed it will be a terminating error. If no repo is specified all allowed repos will be seared and it will be a non-terminating error. 

### Proposed technical implementation details (optional)

![image](https://github.com/user-attachments/assets/4b03fcb7-26dc-4738-a138-4b4bebe459a5)

**Comment by SydneyhSmith** [comment]
We have decided to require json rather than a name value pair

**Comment by StartAutomating** [comment]
@SydneyhSmith This seems like it would be appreciated by the many organizations that still love group policy!

Ideally, this should be easy to get/set with PowerShell as well (for those people who dislike the group policy editor, or anything outside of the command line).

**Comment by adityapatwardhan** [comment]
We actually decided to use name value pair with the following format. It is not easy to write a JSON in the gpeditor.

```
Name=PSGallery;Uri=https://https://www.powershellgallery.com/api/v2 
```
