### ISSUE TITLE
`Compress-PSResource` does not compress scripts

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PSResourceGet#1715]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet)
- [X] Search the existing issues.

### Steps to reproduce

1. Create script
``` PowerShell 
New-ScriptFileInfo TestScript\TestScript.ps1 -Description "Test script for PowerShell CI" -Author "PSGetAuth"
```

2. Run 
``` PowerShell 
Compress-PSResource -Path .\TestScript.ps1 -DestinationPath c:\destination
```
or 

``` PowerShell 
Compress-PSResource -Path .\TestScript -DestinationPath c:\destination
````

### Expected behavior

Packs the nupkg and places it in `c:\destination`.

### Actual behavior

For the first Compress example above:
No error, but does not create the nupkg.

For the second example:
```PowerShell
Compress-PSResource: No file with a .psd1 extension was found in ''. Please specify a path to a valid module manifest.
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     1.1.0      preview2   Microsoft.PowerShell.PSResourceGet  {Compress-PSResource, Find-PSResource, Get-Instal…


Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jshigetomi** [comment]
I think the cause of this issue is from a limitation of the -DestinationPath Parameter to take in relative paths. 

In the picture below I am able to compress the script generated with the command:

```powershell
New-ScriptFileInfo ./TestScript.ps1 -Description "Test script for PowerShell CI" -Author "PSGetAuth"
```

<img width="863" alt="image" src="https://github.com/user-attachments/assets/51a908f5-c0c5-4ef8-893c-4c16f45c4ec6">

Could you verify that you are sending an absolute path to DestinationPath?

environment:  pwsh 7.5.0-preview.5, PSResourceGet 1.1.0-preview2

**Comment by jshigetomi** [comment]
```powershell
Compress-PSResource -Path .\TestScript -DestinationPath c:\destination
```

For this case, the Path doesn't have an extension so it resolves as a module.  Then it looks for a .psd1 file and not a .ps1 file.

Do we want this cmdlet to search the Path folder to determine if its a module or script? I think that would be useful.
