### ISSUE TITLE
Add '-Import` param to Install-PSResource

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSResourceGet#1746]
### Summary of the new feature / enhancement

As a tester, I want to Install & Import a module ideally in a single call, without the need to run `-PassThru | Import-Module` that I could then add as a session level entry `$PSDefaultParameterValues` 

This is super low priority & could be achieved externally to PSResourceGet via an extension module, especially with all the potential issues this could bring & is more `well it'd be nice` ask than `it really must have this` kinda ask

**Comment by SydneyhSmith** [comment]
Thanks I wonder if this breaks the PowerShell, the philosophy of "one action per cmdlet"? Can you explain the scenario more? Thanks!

**Comment by kilasuit** [comment]
Yeah it sort of does and that's why on thinking more about this I think I'm probably going to build this external to PSResourceGet as the user story for this in my mind was along the lines of 

``As a lazy user and wanting to reduce my typing, I want to be able from a single commmand download and determine how I am to test out a module's or script's functionality, which may be via importing them either into the current session, or by starting a seperate session, optionally making use of a container as a further isolation boundary``
