### ISSUE TITLE
Incompatible version info

### ISSUE THREAD

**Issue by iricigor** [PowerShell/PSResourceGet#175]
Version information from `Get-PSResource` and `Find-PSResource` although they look the same, **are not the same** and cannot be converted automatically.

### Example

You may see error when running these commands:
```PowerShell
(Find-PSResource Az.Accounts).Version -gt (Get-PSResource Az.Accounts).Version
```

### Expected result

I would expect to get boolean comparison result, `true` in this case on my computer or `false` in some other

### Actual result

I am getting the error

`InvalidOperation: Could not compare "1.9.0" to "1.7.4". Error: "Cannot convert the "1.7.4" value of type "System.Version" to type "NuGet.Versioning.NuGetVersion"."`

Obtained information is correct, I do have 1.7.4 installed and 1.9.0 is on the PS Gallery, its just a problem to compare them as they 
are different types. I do have `3.0.0.beta6` version of `PowerShellGet` module

### Workaround

Converting it to string and then to version works on either of properties, but that's just a workaround.

```PowerShell
(Find-PSResource Az.Accounts).Version.ToString() -gt (Get-PSResource Az.Accounts).Version
True

(Find-PSResource Az.Accounts).Version -gt (Get-PSResource Az.Accounts).Version.ToString()
True
```

### Proposed solution

Would it be possible to update one of those types or to enable automated conversion?

**Comment by SydneyhSmith** [comment]
Thanks @iricigor for noticing this and reporting, we agree that the types should be the same

**Comment by SydneyhSmith** [comment]
Closing as resolved in preview 10
