### ISSUE TITLE
`Save/Install-PSResource`: Accept object array containing name, version and repository

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PSResourceGet#1753]
### Summary of the new feature / enhancement

It'd be great if `Save-PSResource` and `Install-PSResource` could accept an object array of resources to install with additional details like version and repository.

This will come in handy, especially when PSResourceGet some time in the future, hopefully, implements parallelization / concurrency. Especially for PowerShell v5.1 which can't do concurrency as easy as `| ForEach-Object -Parallel {}`.

Today we can do:

```pwsh
# If multiple in one - No option of specifying version and/or repository
Save-PSResource -Name 'name_1', 'name_2'

# If foreach
(
  @{'Name'='Az.Accounts';'Version'='3.0.5';'Repository'='PSGallery'},
  @{'Name'='NuGet.Versioning';'Version'='[5,6)';'Repository'='NuGetGallery'}
) | ForEach-Object -Process {
  Save-PSResource -TrustRepository @_
}
```

### Proposed technical implementation details (optional)

Feature request would allow

```pwsh
Save-PSResource -TrustRepository -InputObject (
  @{'Name'='Az.Accounts';'Version'='3.0.5';'Repository'='PSGallery'},
  @{'Name'='NuGet.Versioning';'Version'='[5,6)';'Repository'='NuGetGallery'}
)
```

**Comment by SydneyhSmith** [comment]
We support this today via required resources https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.psresourceget/install-psresource?view=powershellget-3.x#example-5 ... does this meet your use?

**Comment by o-l-a-v** [comment]
Ah, sweet. My bad then. :)
