### ISSUE TITLE
Black Lives Matter

### ISSUE THREAD

**Issue by whatsthedealwithpolitics** [PowerShell/PSResourceGet#180]
Your FAQ directed website issues to GitHub, and I feel its appropriate for your organization to publicly respond to your public advocacy.

Black Lives Matter is a political organization attempting to advance a communist / marxist / socialist agenda.  I presume Microsoft is already aware of truths regarding behind the organizations which they support and have either chosen to accept them or be willingly ignorant toward them.  All Lives Matters goes without saying as much as Black Lives Matter goes without saying, as well as various other racial or ethnic groups, I merely question the politicization and weaponizing of "PowerShell Gallery" against the founding principles of Microsoft's own founding country.

Is Microsoft's public stance now to openly oppose our founding principles and to advocate for political parties -- or is it to develop software and tools?

Please provide clarification on the political advocacy on "PowerShell Gallery"

**Comment by alerickson** [comment]
I'm closing this issue as off-topic to PowerShellGet.  

To address your comment, please see this [Microsoft blog post](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblogs.microsoft.com%2Fblog%2F2020%2F06%2F23%2Faddressing-racial-injustice%2F&data=02%7C01%7CAmber.Erickson%40microsoft.com%7C756f928167f64ad25d5008d827413ea2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637302508462499247&sdata=GhiMHWgssS8gvXHTM17bsUQjQaCRCk31Vdw%2BYpfectg%3D&reserved=0).

**Comment by whatsthedealwithpolitics** [comment]
This is not off-topic.  Per your contact page, website issues are to be posted to your GitHub:  https://www.powershellgallery.com/policies/Contact
