### ISSUE TITLE
PowerShellGet won't search my (artifactory) repository for modules

### ISSUE THREAD

**Issue by godefroi** [PowerShell/PSResourceGet#19]
Steps to reproduce
------------------
```powershell
# get-psrepository                                                                                                      
Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2
BlahBlahPSModules         Trusted              https://artifactory.blahblah.com/api/nuget/psmodules-local

# find-module -Credential $cr1 -verbose -Name 'notreallyanamethatwillbefound'                                           VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='notreallyanamethatwillbefound'' for ''.
VERBOSE: Total package yield:'0' for the specified package 'notreallyanamethatwillbefound'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://artifactory.blahblah.com/api/nuget/psmodules-local' and PackageManagementProvider is 'NuGet'.
WARNING: Unable to resolve package source 'https://artifactory.blahblah.com/api/nuget/psmodules-local'.
VERBOSE: Total package yield:'0' for the specified package 'notreallyanamethatwillbefound'.
PackageManagement\Find-Package : No match was found for the specified search criteria and module name 'notreallyanamethatwillbefound'. Try Get-PSRepository to see all available registered module repositories.
At C:\Users\my.name\Documents\PowerShell\Modules\PowerShellGet\2.2.1\PSModule.psm1:8871 char:9
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.PowerShel\u2026Cmdlets.FindPackage:FindPackage) [Find-Package], Exception
+ FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage
```

Expected behavior
-----------------
My custom repository will be searched for the requested module. It is important to note that according to the Artifactory log, no requests are ever made to the server.

Actual behavior
---------------
My custom repository isn't searched for the requested module (because the package source couldn't be resolved, whatever that means).

Environment data
----------------
```powershell
# $psversiontable                                                                                                       
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
#  Get-Module -ListAvailable PowerShellGet,PackageManagement                                                            

    Directory: C:\Users\my.name\Documents\PowerShell\Modules

ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.4.4      PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, G…
Script     2.2.1      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find…

    Directory: C:\program files\powershell\6\Modules

ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.3.2      PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, G…
Script     2.1.3      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find…
```

```powershell
# Get-PackageProvider -ListAvailable                                                                                    
Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, …
PowerShellGet            2.2.1.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, In…
PowerShellGet            2.1.3.0
```

**Comment by pcgeek86** [comment]
I'm having the same problem with PowerShell 7 on Windows 10 with MyGet.org.

**Comment by alerickson** [comment]
@pcgeek86 are you able to use the workaround `Register-PackageSource -SkipValidate`

**Comment by pcgeek86** [comment]
@alerickson I tried that approach, and it isn't helping solve the problem. I still get the same result.

**Comment by pcgeek86** [comment]
```powershell
Register-PackageSource -SkipValidate -Location https://www.myget.org/F/asdf/api/v2 -Name asdf -ProviderName NuGet

Register-PSRepository -Name asdf -SourceLocation https://www.myget.org/F/asdf/api/v2 -PublishLocation https://www.myget.org/F/asdf/api/v2/package -Credential ps

Find-Module -Repository asdf
```

> ERROR: WARNING: Query Url https://www.myget.org/F/asdf/api/v2 is invalid.

**Comment by ReinierKop** [comment]
I'm on PS 5.1 and have the same issue when trying to connect to a Nexus 3 repository:

Both when running `Register-PSRepository -Repository xxx ...` and e.g. `Find-Module -Repository xxx`, I find myself looking at this warning:

```ps1
WARNING: Unable to resolve package source 'https://mynexusrepository.local/repository/nuget-hosted/'.
```

The same commands run perfectly fine in PS 7 but unfortunately we don't have the liberty to upgrade the PS environments on the target machines.

Edit: The workaround does not seem to work for me since I believe we want a `PowershellGet` providername rather than a `nuget`, which does not work together with `skipvalidate`

**Comment by mmackenna** [comment]
> ```PowerShell
> Name                     Version          DynamicOptions
> ----                     -------          --------------
> NuGet                    3.0.0.1          Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, …
> PowerShellGet            2.2.3.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, In…
> PowerShellGet            2.1.5.0
> PowerShellGet            1.0.0.1
> ```

@PDQDakota I noticed that I had two NuGet package providers on this list. I had the same one as you, version 3.0.0.1, but I also had a version of 2.8.5.208. I know that this worked for me previously, so I tried removing the NuGet 3.0.0.1 version. To remove it, I found the provider's location, which was a dll inside of PackageManagement 1.4.7 called Microsoft.PackageManagement.NuGetProvider.dll. I removed that file and placed it elsewhere. I then verified with 'Get-PackageProvider' that I just had the following for a NuGet provider, NuGet version 2.8.5.208. I then tried again to search using "Find-Module -Name 'MyKnownExistingPackage' -Repository 'MyRegisteredArtifactoryRepo' -Credential 'MyJFrogCred'" and it worked!
I am hoping this helps you as well.

FYI @SydneyhSmith

**Comment by jjolidon** [comment]
I had a similar situation with a ProGet instance requiring an authentication (surprisingly it works fine without the authentication). Here is a workaround that _may_  just work:

- First, register the source with Register-PackageSource but specifying to use the NuGet provider (this bit is the important part)
  > Register-PackageSource -Name MySource -Location "https://example.org/nuget/PSModules/" -ProviderName NuGet
- Second, register the source with Register-PSRepository
  > Register-PSRepository -Name MySource -SourceLocation "https://example.org/nuget/PSModules/"
- Third, use either Find-Package or Find-Module to locate the packages
  > Find-Package -PackageManagementProvider PowerShellGet -Source MySource -Name MyModule
  > Find-Module -Repository MySource -Name MyModule

As usual, specify proxy or credentials if needed (but most likely for all of the above commands if at all).

Let me know if it solved your issue

Cheers

**Comment by kevinblumenfeld** [comment]
> @PDQDakota I noticed that I had two NuGet package providers on this list. I had the same one as you, version 3.0.0.1, but I also had a version of 2.8.5.208. I know that this worked for me previously, so I tried removing the NuGet 3.0.0.1 version. To remove it, I found the provider's location, which was a dll inside of PackageManagement 1.4.7 called Microsoft.PackageManagement.NuGetProvider.dll. I removed that file and placed it elsewhere. I then verified with 'Get-PackageProvider' that I just had the following for a NuGet provider, NuGet version 2.8.5.208. I then tried again to search using "Find-Module -Name 'MyKnownExistingPackage' -Repository 'MyRegisteredArtifactoryRepo' -Credential 'MyJFrogCred'" and it worked!

I am having the same issue. Thank you for sharing your fix. Would you mind sharing how to get the 2.8.5.208 version on your system and what paths you used to find the file that you moved, please?

**Comment by alerickson** [comment]
This will no longer be an issue with the release of 3.0.13-beta.
