### ISSUE TITLE
PowerShell Core install location uses Windows PowerShell path

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#198]
PowerShellGet v3 beta7 has a bug where it fails to identify PowerShell core and uses the Windows PowerShell install location. It looks to be in this section of code here.

https://github.com/PowerShell/PowerShellGet/blob/8dbb8b4b5b3a438cc9b2428f3860c36140cacf49/src/InstallHelper.cs#L63-L83

`Get-PSResource` uses the correct location.

https://github.com/PowerShell/PowerShellGet/blob/8dbb8b4b5b3a438cc9b2428f3860c36140cacf49/src/GetPSResource.cs#L116-L131

There is also an error if the folder does not exist:

```
PowerShell 7.1.0-preview.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

C:\> Get-Module powershellget -ListAvailable

    Directory: C:\Users\Thomas\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     3.0.0      beta7      PowerShellGet                       Desk      {Find-PSResource, Get-PSResourceReposit…

C:\> Install-PSResource operationvalidation -Verbose -Debug
VERBOSE: Current user scope installation path: C:\Users\Thomas\Documents\WindowsPowerShell
VERBOSE: All users scope installation path: C:\Program Files\WindowsPowerShell
VERBOSE: Scope is: CurrentUser
Install-PSResource: Could not find a part of the path 'C:\Users\Thomas\Documents\WindowsPowerShell\Modules'.
```

**Comment by alerickson** [comment]
The latest release, Beta8, addresses this issue.  Feel free to test that version and provide any feedback.  Thanks!

**Comment by ThomasNieto** [comment]
@alerickson that looks to be resolved.
