### ISSUE TITLE
Cmdlets do not support argument completers

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#202]
The following cmdlets and parameters do not have argument completers.

* Find-PSResource -Name (can utilize cache for PSGallery)
* Get-PSResource -Name
* Get-PSResourceRepository -Name
* Install-PSResource -Name (can utilize cache for PSGallery)
* Set-PSResourceRepository -Name
* Save-PSResource -Name (can utilize cache for PSGallery)
* Uninstall-PSResource -Name
* Unregister-PSResourceRepository -Name
* Update-PSResource -Name

**Comment by SteveL-MSFT** [comment]
Publish-PSResource -Repository

**Comment by alerickson** [comment]
Updating that the following now have argument completers (as of [beta10](https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta10)):

- Get-PSResourceRepository -Name
- Set-PSResourceRepository -Name
- Unregister-PSResourceRepository -Name

And the following still need argument completers:

- Find-PSResource -Name (can utilize cache for PSGallery)
- Get-PSResource -Name
- Install-PSResource -Name (can utilize cache for PSGallery)
- Save-PSResource -Name (can utilize cache for PSGallery)
- Uninstall-PSResource -Name
- Update-PSResource -Name
- Publish-PSResource -Repository

**Comment by ThomasNieto** [comment]
The other `*-PSResource` commands with a `Repository` parameter would need a completer as well.

* Find-PSResource
* Install-PSResource
* Publish-PSResource
* Save-PSResource
* Update-PSResource

**Comment by anamnavi** [comment]
We are not going to address adding a completer for the `-Name` parameters of the following cmdlets until a cache is implemented, for efficiency sake: 

Find-PSResource
Get-PSResource
Install-PSResource
Save-PSResource
Uninstall-PSResource

As of PSGet 3.0.11 release, the following cmdlets have a completer for the -Repository parameter.

Find-PSResource
Get-PSResourceRepository
Install-PSResource 
Set-PSResourceRepository
Save-PSResource
Unregister-PSResourceRepository
Update-PSResource 
Publish-PSResource
