### ISSUE TITLE
Format returned objects

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PSResourceGet#212]
Objects returned from Find and Get-PSResource should contiain full object information, with proper formatting.  Get should include the installed location.

**Comment by ThomasNieto** [comment]
Here is related issue with missing properties from v2 #199. I know some of them don't apply anymore with the removal of `PackageManagement`. 

This would be a great time to also convert these returned objects from `PSObject` to a concrete type so we can use tab completion in `Select-Object` and `Where-Object` described in this other issue #159.

**Comment by SydneyhSmith** [comment]
We have created the strongly typed classed however these will not be updated in every cmdlet yet in the next release but should be updated in the following release for remaining cmdlets

**Comment by alerickson** [comment]
This will be addressed with Preview 11.

**Comment by LaurentDardenne** [comment]
The 'AdditionalMetadata' property is not populated for objects coming from a local repository (file system):
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/73f3bd44-20a9-403a-adfb-0c7ab262488e)

**Comment by LaurentDardenne** [comment]
Regarding the formatting, that of the version number is coded on 3 digits for PSGallery but on 4 digits for the local repository:
![image](https://github.com/PowerShell/PSResourceGet/assets/4894452/5e3bde83-0809-4f69-aad2-7f56a6ccc680)

The two module manifests each have a three-digit _ModuleVersion_ key:
[String-PsGallery](https://github.com/FriedrichWeinmann/string/commit/9a8131f71b8ac6602251e61abab23528a22978ac#diff-12909100c6a5a4a344a0fe0654f67b958ca57b081177238ebcb085bcb0f0f9e3)

[String-PsRepolocal](https://github.com/LaurentDardenne/psmodulecache/blob/FeatureModuleDependencies/test/Dependencies/Gallery/String/1.0.0/String.psd1#L15)
