### ISSUE TITLE
Set-PSResourceRepository does not accept pipeline input from Get-PSResourceRepository

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#213]
Trying to set all the configured repositories to trusted and it does not accept updating the URL of PSGallery. If the object returned from `Get-PSResourceRepository` returned read-only properties and `Set-PSResourceRepository` had a parameter set that accepted that property it would not need to complain about trying to set a read-only property.

```powershell
Get-PSResourceRepository | Set-PSResourceRepository -Trusted
Set-PSResourceRepository: The PSGallery repository has a pre-defined URL.  The -URL parmeter is not allowed, try running 'Register-PSResourceRepository -PSGallery'.
```

**Comment by anamnavi** [comment]
This works: 
![image](https://user-images.githubusercontent.com/30238344/128211992-422eba6a-014e-46c1-a1f5-4e422150f969.png)
