### ISSUE TITLE
Install-PSResource -Type parameter should be Enum to allow for tab completion

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#230]
Unless some sort of plug-in system is planned, Insatll-PSResource -Type parameter should be an enum for the types of resources (modules, scripts, nuget packages, etc.)

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote we are actually thinking of removing the `Type` parameter for install since there cannot be name conflicts across resource types, we do not see a use case...is there anything you are aware of that we are not thinking of?

**Comment by JustinGrote** [comment]
@SydneyhSmith as long as you are sure there cannot be conflicts across resource types (including resources in multiple repositories) or you have a way of handling a conflict and selecting the appropriate resource, then I'm good with that as long as it doesn't negatively impact query times (e.g. if having a type parameter may be able to speed up searches by 5x if it only has to search one type instead of searching 5)

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote that was a great point about query times, after reviewing the cmdlet this would not impact query times--thanks!
