### ISSUE TITLE
Beta9: Cannot run PS7 and WinPS versions simultaneously

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#232]
Apparently there is a step in the import process where assemblies are now attempted to remove on load. The problem is that if you already have either PS7 or WinPS open, it will fail because the assemblies are already loaded and file-locked

# Reproduce

Import the module into a PS7 session, then open a Windows Powershell session and import the module there.
![image](https://user-images.githubusercontent.com/15258962/91875365-3cbfa780-ec30-11ea-91ec-b8263f72d20a.png)

# Recommended Solution
Don't try to remove the files or move or whatever is going on here, just load conditionally based on whether you are in PS7 or WinPS.

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote we will include a fix in the next release.

**Comment by alerickson** [comment]
Resolved in [beta10](https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta10).
