### ISSUE TITLE
Duplicate repository names should not be allowed

### ISSUE THREAD

**Issue by brajjan** [PowerShell/PSResourceGet#238]
Register-PSResourceRepository currently allows to register multiple repositories with the same name

    Register-PSResourceRepository -name 'testing' -URL 'http://localhost'
    Register-PSResourceRepository -name 'testing' -URL 'http://localhost'
    Get-PSResourceRepository
    
    Name          Url                                                                     Trusted Priority
    ----          ---                                                                     ------- --------
    testing       http://localhost/                                                       false   50
    testing       http://localhost/                                                       false   50

    Get-PSResourceRepository -name 'testing'

    Name          Url                                                                     Trusted Priority
    ----          ---                                                                     ------- --------
    testing       http://localhost/                                                       false   50

**Comment by alerickson** [comment]
Thanks for opening this issue!  This has been resolved with the latest release of PowerShellGet [3.0.0-beta10](https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta10)
