### ISSUE TITLE
Find-PSResource Type parameter does not return Script types if Name contains wildcard

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PSResourceGet#247]
Type parameter not working as intended and doesn't filter by type. It only returns resources via the searchAsync() call that have tags of `PSModule`, tag length 0 or other random text tags (i.e Tag1, etc), but not any tags of type `PSScript`. It then attempts to filter by Tag value but since original found resources don't contain any `PSScript`, `PSCommand`, `PSDscResource`, `PSRoleCapability` tags filtering doesn't work.

Need to look into Nuget package API to determine what's happening in the searchAsync() call.

**Comment by StevenBucher98** [comment]
Closing for lack of repro
