### ISSUE TITLE
Console.WriteLine Usage

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#248]
`Uninstall-PSResource` and `Save-PSResource` writes to the console without user input or control. The user is not able to stop these messages from being written to the console. Was this added for testing?

```powershell
C:\> Uninstall-PSResource pskoans

Successfully uninstalled pskoans
C:\> Uninstall-PSResource pskoans

Did not successfully uninstall pskoans

C:\> Save-PSResource -Name PSKoans -Version 1.3.5.5l -ErrorAction SilentlyContinue

Save-PSResource: '1.3.5.5l' is not a valid version string
```

Is caused by these lines in the code.

https://github.com/PowerShell/PowerShellGet/blob/0d194381b47cf13fcf2b185c33261f386894f826/src/UninstallPSResource.cs#L165-L172

https://github.com/PowerShell/PowerShellGet/blob/5a99baeaf27d40a4d4c213b12228b8c548acba81/src/SavePSResource.cs#L669

**Comment by SydneyhSmith** [comment]
Thanks @ThomasNieto those messages should be updated to verbose

**Comment by alerickson** [comment]
This will be addressed with Preview 11.
