### ISSUE TITLE
Register-PSResourceRepository -Repositories Parameter Type

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#249]
The parameter type for `Register-PSResourceRepository -Repositories` is a `<List[hashtable]>` instead of the PowerShell standard of `[hashtable[]]` array.

**Comment by SydneyhSmith** [comment]
Thanks @ThomasNieto happy to make the change, although curious is this is impacting your functionality in any way or are just looking for consistency

**Comment by ThomasNieto** [comment]
@SydneyhSmith Its for consistency and ease of use. I would say that most PowerShell users don't know what generic types are and how to create them since none of the built-in cmdlets use them.
