### ISSUE TITLE
First run experience is... lacking. Cannot find XML

### ISSUE THREAD

**Issue by Windos** [PowerShell/PSResourceGet#258]
Testing PowerShellGet 3.0.0-beta10 with CompatPowerShellGet 0.0.2, on both PowerShell 7.0.3 and 7.1.0-preview.7.

First thing I did with the new module was try and install the SecretManagement module.

```powershell
Install-Module -Name Microsoft.PowerShell.SecretManagement -AllowPrerelease
```

I'm told Install-Module is deprecated (expected), but then get an error about not finding XML and being told to register a repo.

```output
WARNING: The cmdlet 'Install-Module' is deprecated, please use 'Install-PSResource'.
Install-PSResource: Was not able to successfully find xml. Try running 'Register-PSResourceRepository -PSGallery'
```

It seems that this error occurs when running *any* PowerShellGet command, including `Get-PSResourceRepository`.

As a first run experience with the module and expecting it to "just work", this is jarring. Surley PSGallery should be a default (as I'm sure most users will be using that, and only that... advanced users should be more than capable of removing it if needed?)

**Comment by alerickson** [comment]
Thanks for the feedback!  I completely agree with you, we do if it on our short list of things to add and should get this out with the next release
