### ISSUE TITLE
Find-PSResource Always Prints Warning for Nuget v3 Feeds

### ISSUE THREAD

**Issue by bormm** [PowerShell/PSResourceGet#259]
Tried version: 3.0.0-beta10

Hi,

in case I registered a nuget v3 feed from Azure DevOps, Find-PSResource always prints
`"WARNING: This functionality is not yet implemented"`
even the remaining functionality is given and the available resources are returned.

**Comment by SydneyhSmith** [comment]
Thanks for calling this out @bormm , looks like the issue is occurring here: 
https://github.com/PowerShell/PowerShellGet/blob/e562f86317bef8f9ae2d1e7547fb890525f7e799/src/FindPSResource.cs#L211

**Comment by bormm** [comment]
I do not think its a good idea to write "This functionality is not yet implemented" to output from somewhere in the code. What this "this" means is completely unknown for the user.

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
