### ISSUE TITLE
.nupkg.metadata not deleted when using Install-PSResource

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#260]
While testing for a solution for https://github.com/PowerShell/PowerShell/issues/5831 I found that there is a difference between `Install-PSResource` and `Save-PSResource`. Using save will remove the `.nupkg.metadata` file but does not get removed on install. Does PowerShellGet use this file? I didn't get any references using it in the code. By leaving this file it causes the validation to fail when using `Test-FileCatalog`.

**Comment by alerickson** [comment]
Nope, that should be removed as well
