### ISSUE TITLE
Install/Save-PSResource creates version folder using prerelease name

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#261]
Running `Save-PSResource -Name PowerShellGet -Path C:\Temp -Prerelease` will create a `C:\Temp\PowerShellGet\3.0.0-beta10`. `Import-Module` will throw an error because the folder name and version in the psd1 do not match.

```powershell
Import-Module C:\Temp\PowerShellGet
Import-Module: The specified module '.\PowerShellGet\' was not loaded because no valid module file was found in any module directory.

# Fixed by renaming the folder to remove -beta10
cd c:\temp\PowerShellGet
Rename-Item .\3.0.0-beta10\ .\3.0.0
cd c:\temp
Import-Module .\PowerShellGet
```

**Comment by PaulHigin** [comment]
I am seeing the same issue with Install-PSResource cmdlet.
```powershell
Install-PSResource -Name Microsoft.PowerShell.SecretManagement -Prerelease -Repository PSGallery

dir 'C:\Users\user\OneDrive - Microsoft\Documents\PowerShell\Modules\Microsoft.PowerShell.SecretManagement\'

    Directory: C:\Users\user\OneDrive - Microsoft\Documents\PowerShell\Modules\Microsoft.PowerShell.SecretManagement

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---           9/18/2020  9:39 AM                0.5.2-preview3
```

**Comment by ThomasNieto** [comment]
@PaulHigin what version of PowerShellGet are you running?

**Comment by PaulHigin** [comment]
3.0.0-beta10

**Comment by JustinGrote** [comment]
Since https://github.com/PowerShell/PowerShell/issues/2983 is likely a long way out, this should revert to the old folder conventions now because it currently doesn't work with any powershell version and it's extremely annoying to install a prerelease module only to have to go into the folder and rename it, I had to write a wrapper function to save myself the trouble.

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
