### ISSUE TITLE
Uninstall-Module fails when OneDrive has "Files-On-Demand" feature enabled

### ISSUE THREAD

**Issue by daniefer** [PowerShell/PSResourceGet#262]
I am forced to disable this File-On-Demand feature in OneDrive in order to get this error to go away. This is a real inconvenience for those on an enterprise environment where users who don't have rights to run as administrator cannot install modules under any other scope other than CurrentUser and don't have the access to modify Policies that allow disabling of the File-On-Demand feature (which requires a registry edit).

# Steps to Reproduce
1. Install any module under the CurrentUser Scope
1. Uninstall that module

# Actual Results
```none
Uninstall-Package : Access to the cloud file is denied
At line:1 char:1
+ Uninstall-Package Thor
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package],
   Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand,Mic
   rosoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage
```

# Expected Results
The module should uninstall successfully.

**Comment by SydneyhSmith** [comment]
Thanks @daniefer the Uninstall-Module cmdlet comes from a legacy version of PowerShellGet...we are currently in public preview for a new version of PowerShellGet (3.0) so any fix would be made in this version of the module...would you be able to install the latest preview and let us know if you are still hitting this error? 
https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta10

**Comment by daniefer** [comment]
I will get repro steps to you in the next 1-2 weeks with the v3 beta

**Comment by franklesniak** [comment]
I ran into this issue today. Thanks for the pointer on using the 3.0.x beta release of PowerShellGet - that worked!
