### ISSUE TITLE
Find-PSResource should include PreRelease property just like Get-Module does

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#264]
Right now if you do `find-psresource -prerelease`, there's no way to tell what Prerelease is available.
![image](https://user-images.githubusercontent.com/15258962/93914783-e0dec080-fcbb-11ea-92c7-49a004450e1a.png)

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote we will address this when we add formatting in the upcoming release:

https://github.com/PowerShell/PowerShellGet/issues/212

**Comment by ThomasNieto** [comment]
The problem with that solution is that its not a property that can be used in automation but added in the formatting system. To properly solve this the `Version` type should be changed to `[NuGetVersion]` that supports both a `[System.Version]` and `[SemanticVersion]` version schemes as described in #269.

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
