### ISSUE TITLE
Save-PSResource errors when downloading a script package

### ISSUE THREAD

**Issue by MaxFrost** [PowerShell/PSResourceGet#266]
Encountered this when I discovered that Save-PSResource had a shim in to replace Save-Script, and got an unexpected error. Dug deeper and found that it impacts all script resources saved this way from the PSGallery

Using Pwsh 7.0.3, PowershellGet 3.0.0-beta10
```Powershell
Save-PSResource Get-WindowsAutoPilotInfo -Path "$env:UserProfile\Downloads"
Save-PSResource: Could not find file 'C:\Users\james.maxson\AppData\Local\Temp\406111d6-1781-44d5-bb8f-be293f23a605\get-windowsautopilotinfo\3.5.0\Get-WindowsAutoPilotInfo_InstalledScriptInfo.xml'.
```
This is reproducible by going to any script package at https://www.powershellgallery.com/packages (filter by script) and attempting to download it with Save-PSResource.

Install-PSResource has no problem with this, I did check.

**Comment by SydneyhSmith** [comment]
Thanks @MaxFrost this should be addressed in the next release

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
