### ISSUE TITLE
Find-PSResource should preserve company name

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#267]
Current behavior of Find-Module is to override the company name with the owners aliases:
![image](https://user-images.githubusercontent.com/43417619/94282229-6c4a9280-ff04-11ea-999c-f86f3061e4ef.png)
We should get this fixed for Find-PSResource

This work will likely be a part of object formatting: #212

**Comment by anamnavi** [comment]
That information is not easily accessibly via the json metadata (IPackageSearchMetadata object returned via GetSearchAsync() and GetMetadataAsync() search APIs and may be more work than is worth to get this field. Here is a link listing the package information accessible via the package nuspec (note company name is not listed): 
https://docs.microsoft.com/en-us/nuget/reference/nuspec
