### ISSUE TITLE
Get-PSResource Version property is returning multiple types

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#269]
`Get-PSResource` is returning multiple types for the `Version` property. This is causing issues when trying to sort by version as well as casing to other types.

Can we please update this type to use `[NuGetVersion]`? NuGet supports both legacy `[System.Version]` and `[SemanticVersion]` formatting with proper sorting.

```powershell
C:\> Get-PSResource | % { $_.Version.GetType() } | Select-Object -Property Name -Unique

Name
----
String
Version
PSObject
```

**Comment by alerickson** [comment]
This will be addressed with preview 11.
