### ISSUE TITLE
PowerShellGet 3.0/PowerShellGallery should work with legacy TLS

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#270]
We should add this to 3.0 interaction with the Gallery and incorporate legacy TLS into our testing:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

**Comment by SydneyhSmith** [comment]
We are also considering adding a warning to update to TLS 1.2 instead

**Comment by StevenBucher98** [comment]
@alerickson is there a way to check if the issue is caused by the TLS issue and then be able to send a warning/error messaged based on that?

**Comment by alerickson** [comment]
@mgreenegit
