### ISSUE TITLE
Should be able to ignore dependencies.

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSResourceGet#274]
There are times when you will want to download a module from the gallery/internal gallery and ignore all dependencies (perhaps they are already installed) 

Therefore a `-IgnoreDependency` switch should be able to be provided

**Comment by ThomasNieto** [comment]
I would expect that `Install/Save-PSResource` should be smart enough not to install a dependency if its already installed. As for the option in general this feature will be great for times when needing to synchronize packages from the gallery to internal gallery.

Should the name of the parameter be `-ExcludeDependencies` to match `-IncludeDependenices` on `Find-PSResource`?

**Comment by SydneyhSmith** [comment]
Thanks @kilasuit and @ThomasNieto we agree that this should be available, and like the proposal for `-ExcludeDependencies` as the name

**Comment by alerickson** [comment]
This is resolved with PR #550
