### ISSUE TITLE
Cmdlets have SupportsShouldProcess but don't actually implement it

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#279]
Cmdlets have `SupportsShouldProcess` but don't actually implement it for `-WhatIf` and `-Confirm` parameters. This gives users a false sense of security.

* Install-PSResource
* Publish-PSResource
* Save-PSResource
* Update-PSResource
* Uninstall-PSResource
* Register-PSResourceRepository
* Unregister-PSResourceRepository
* Set-PSResourceRepository

These don't need `SupportsShouldProcess` since they are non-state changing cmdlets.

* Get-PSResourceRepository
* Find-PSResource
* Get-PSResource

**Comment by SydneyhSmith** [comment]
Thanks @ThomasNieto for calling this out, we do plan to implement

**Comment by alerickson** [comment]
This is complete for all of the mentioned cmdlets except for Save-PSResource.  We'll add this in shortly.

**Comment by alerickson** [comment]
Resolved with PR #447
