### ISSUE TITLE
Better error handling when a repo is already registered

### ISSUE THREAD

**Issue by HemantMahawar** [PowerShell/PSResourceGet#28]
_From @WernerMairl on November 18, 2016 8:27_

Hi
Working with Register-PSRepository i have found some behavior that was really unexpected.
Probably we are not talking about bugs but about usability....

1. Repository uniqueness
All the functions around PSRepository (Get, Register, Unregister) are using the Name Property/Argument to identify a Repo.
 
Seeing this API-Surface i'm assuming that the property Name is the one that implements the "unique" Key for Repos => expected behavior at the first look....

after playing a few hours with the api, i find out that internally NOT the Name must be unique but the property "SourceLocation" enforces uinqueness.

- That means i'm not be able to register the same package Source with different Names
- Means in different Powershell-Codebases that should run on the same server i must synchronize Repository NAMES....

To solve problems like that must select/filter my Repos by SourceLocation BUT the Get-PSRepo function doesn't implement filter for SourceLocation.... usability Issue, a property that is used as primary key should have some easy access....(yes i can do that with pure Powershell, but we are talking about API-Usability)

2. ErrorActionPreference is ignored!
If i call "Register-PSRepository" with a unique/random Name but a SourceLocation that is used in another Repo then the Function writes Error output.

_**PackageManagement\Register-PackageSource : The repository could not be registered because there exists a registered repository with Name 'XXXXX' and SourceLocation 'http://xxxxxxx.y.z.a:8080/api/odata'. To register 
another repository with Name 'XXXXX', please unregister the existing repository using the Unregister-PSRepository cmdlet**_

I found the following unexpected behavior here:

$ErrorctionPreference value is "Stop" in the calling script => assuming that a exception can be catched with try catch
Register-PSRepository writes the error record but it does not FOLLOWS the STOP behavior.. it IGNORES!

To enforce the "expected" behavior i must expplicitely use
Register-PSRepository ......-ErrorAction Stop

I'm not a expert in all the coding and behavior rules for PS but 
in 99% of my PS-Code i'm able to catch exceptions by using $ErrorActionPrefence on the global level
so i think that can be behavior issue inside Register-PSRepository

regards
Werner

_Copied from original issue: PowerShell/PowerShell#2717_

**Comment by Jaykul** [comment]
This is *also* extremely frustrating for us. Every deployment I have has lines like this at the top:

> We MUST be sure the URL is correct for the repository, because PowerShellGet only allows us to specify repositories BY NAME when we're installing modules. And we cannot call `Register` if the name is already registered. We could test the name *and* the URL, and if they don't match, remove and re-register, but that would take even more likes, so ...

```posh
$Url = "https://${Team}.pkgs.visualstudio.com/_packaging/PowerShell/nuget/v2"

# We simply always remove and re-register, just be sure
Get-PSRepository -WarningAction SilentlyContinue | Where { $_.Name -eq $Team } | Unregister-PSRepository
Register-PSRepository -InstallationPolicy Trusted -Name $Team -SourceLocation $Url
```

Of course, that's only the tip of the iceberg, because then we need three lines to install nuget just in case PowerShell/PowerShellGetv2#101

And **five or six lines** just to install a module without errors!?

**Comment by alerickson** [comment]
Resolved repository uniqueness in [3.0.0-beta10](https://www.powershellgallery.com/packages/PowerShellGet/2.2.4.1).

**Comment by AndrewSav** [comment]
@alerickson why does "3.0.0-beta10" link to `PowerShellGet/2.2.4.1` ? Typo?

**Comment by alerickson** [comment]
This will be resolved with the release of Preview 11.
