### ISSUE TITLE
Find-PSResource Type parameter is a string not enum

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#281]
This parameter is currently a string parameter with a `ValidateSet` attribute. Can this be changed to an enum for easier discovery and maintainability?

https://github.com/PowerShell/PowerShellGet/blob/f1ddcb3bc602c61f9b98f79b1ab02b00331da8f5/src/code/FindPSResource.cs#L64-L65

**Comment by alerickson** [comment]
This will be resolved in Preview 11.
