### ISSUE TITLE
*-PSResource does not throw error on non-existent module

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#282]
I typo'd the module and found that none of the following cmdlets write an error if it tries to perform an action on a non-existent module. For example, `Find-PSResource PSKoanssd`. V2 throws an error as expected.

* Find-PSResource
* Install-PSResource
* Save-PSResource
* Update-PSresource

**Comment by alerickson** [comment]
This is fixed with the release of 3.0.11-beta.  I’ll add the specific PR where this was fixed as well
