### ISSUE TITLE
Save-PSResource does not deduplicate dependencies

### ISSUE THREAD

**Issue by bgelens** [PowerShell/PSResourceGet#285]
Trying to use Save-PSResource to download Az (meta module).

![image](https://user-images.githubusercontent.com/10071039/96036606-fbdcc480-0e64-11eb-855a-d81eb78a3db1.png)

It fails because Az.Accounts is downloaded multiple times

Using beta10 on PowerShell 7.1 preview 7 on MacOS

**Comment by SydneyhSmith** [comment]
Thanks @bgelens just to clarify is this causing the save to completely fail? Or is just the Az.Accounts save failing?

**Comment by SydneyhSmith** [comment]
We may need to add a -Force parameter or something like that

**Comment by bgelens** [comment]
Hey @SydneyhSmith, It completely fails.

Repro is easy. Create a folder to save in and run `Save-PSResource az -Version 4.8.0 -Path 'folderpath'`

Az is downloaded, Az.Accounts is downloaded and Az.Advisor is downloaded then it terminates on the error that Az.Accounts is already in the target folder

**Comment by alerickson** [comment]
This will be resolved in Preview 11.
