### ISSUE TITLE
Publish-Script - include additional files in package

### ISSUE THREAD

**Issue by craibuc** [PowerShell/PSResourceGet#299]
I use a PowerShell data file (`.psd1`) to hold settings for my script file (`.ps1`), 

 It would be helpful to be able to include the `psd1` in the `nupkg` so that I don't need to deploy the settings files manually.

**Comment by SydneyhSmith** [comment]
Thanks @craibuc could you try our latest preview version of PowerShellGet [preview 10](https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta10) and let us know if `Publish-PSResource` resolves this for you? thanks! 

PowerShellGet views any package with a psd1 as a module so it will publish your script as a module, which should allow the psd1 to be a part of the nupkg, when you publish as a script only the .ps1 is published. 
Since we have made PSResource generic in our latest version this semantic difference isnt exposed.

**Comment by craibuc** [comment]
I was able to publish the script, but when I examined the contents of the `nupkg` archive, the `psd1` wasn't included.

Script:
```powershell
<#PSScriptInfo
.VERSION 0.0.0
.GUID bb3383a7-282d-4b38-9a1c-9489e313dcbb
.AUTHOR first.last@domain.tld
.COMPANYNAME Acme, Inc.
.COPYRIGHT (c) Acme, Inc.  All rights reserved.
.TAGS 
.LICENSEURI
.PROJECTURI 
.ICONURI
.EXTERNALMODULEDEPENDENCIES 
.REQUIREDSCRIPTS
.EXTERNALSCRIPTDEPENDENCIES
.RELEASENOTES
.PRIVATEDATA
#>

<#
.SYNOPSIS
Lorem ipsum

.DESCRIPTION 
Lorem ipsum
#>

[CmdletBinding()]
param ()

$ScriptName = (Get-Item $PSCommandPath).Basename
$SettingsPath = Join-Path $PSScriptRoot "$ScriptName.psd1"
$Settings = Import-PowerShellDataFile -Path $SettingsPath

Write-Host $Settings.Message
```

Settings:
```powershell
@{
    Message = 'Hello, World'
}
```

## Process
### Create repository
```powershell
$Repository = @{
    Name='craig'
    Trusted=$true
    Url='file:///Users/craig/Desktop/MyRepo'
}
Register-PSResourceRepository
```
### Publish script
```powershell
Publish-PSResource -Repository 'craig' -path ./MyScript.ps1
```

### Examine
```powershell
Find-PSResource -Repository 'craig'

Name         Version Repository Description
----            ------- ----------  -----------
MyScript   0.0.0.0  craig          Lorem ipsum #>                                                                                                                              
MyModule 0.0.1.0   craig          lorem ipsum
```

**Comment by craibuc** [comment]
I meant to ask: [how should the `.PRIVATEDATA` setting be used?](https://stackoverflow.com/questions/64265125/how-do-i-make-use-of-new-scriptfileinfo-privatedata)

**Comment by craibuc** [comment]
> I meant to ask: [how should the `.PRIVATEDATA` setting be used?](https://stackoverflow.com/questions/64265125/how-do-i-make-use-of-new-scriptfileinfo-privatedata)

I found the solution:

```powershell
$Info = Test-ScriptFileInfo $PSCommandPath
$PrivateData = [pscustomobject](Invoke-Expression $Info.PrivateData)
```

**Comment by craibuc** [comment]
> Thanks @craibuc could you try our latest preview version of PowerShellGet [preview 10](https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta10) and let us know if `Publish-PSResource` resolves this for you? thanks!
> 
> PowerShellGet views any package with a psd1 as a module so it will publish your script as a module, which should allow the psd1 to be a part of the nupkg, when you publish as a script only the .ps1 is published. Since we have made PSResource generic in our latest version this semantic difference isnt exposed.

Has this been implemented?

**Comment by StevenBucher98** [comment]
Yes, it is implemented @craibuc, let us know if you have any issues!
