### ISSUE TITLE
AllowClobber should write a warning about command collisions

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSResourceGet#30]
Can we please have Install-Module with -AllowClobber write a **warning** about command collisions, so that we still get notified about them _as we install_?

Personally, I think that should be the _default behavior_. I mean, hypothetically a user can always cancel or uninstall if it gets in the way, but so far I have never _not_ installed a module because of the command-collision error, so I'm just annoyed at having to run Install-Module commands two or three times.

**Comment by alerickson** [comment]
Addressed with release of 3.0.0-beta2
