### ISSUE TITLE
The gallery is running EXTREMELY slow

### ISSUE THREAD

**Issue by nexxai** [PowerShell/PSResourceGet#301]
And I'm not the only one having issues: https://twitter.com/HtekConsulting/status/1325903714754899971?s=20

**Comment by anamnavi** [comment]
@nexxai We had a few deployments on Monday, so that may have caused temporary latency and availability related issues. Please let us know if you're still seeing this issue, thanks!

**Comment by anamnavi** [comment]
Closing this as it is answered, will open if this is still an issue
