### ISSUE TITLE
Can't uninstall package

### ISSUE THREAD

**Issue by pradipd** [PowerShell/PSResourceGet#303]
I'm having issues uninstalling a package.  I have two versions present on my machine.
```
PS C:\> get-installedmodule akshci -AllVersions | select Version,Name
Version       Name
-------       ----
0.2.10-alpha9 AksHci
0.2.9         AksHci
```
When I try to uninstall them, it is constantly failing to uninstall the Prerelease version (0.2.10-alpha9)
I first tried to uninstall 0.2.9
```
PS C:\> uninstall-Package AksHci -RequiredVersion 0.2.9 -Force
Name                           Version 
----                           -------      
AksHci                         0.2.9            
```
The command returns, but, the package isn't gone.
```
PS C:\> get-installedmodule akshci -AllVersions | select Version,Name
Version       Name
-------       ----
0.2.10-alpha9 AksHci
0.2.9         AksHci
```
Because the 0.2.9 package isn't removed, the 0.2.10-alpha9 can't be removed.
```
PS C:\> uninstall-Package AksHci -RequiredVersion 0.2.10-alpha9 -Force
uninstall-Package : The module 'AksHci' of version '0.2.10-alpha9' in module base folder 'C:\Program Files\WindowsPowerShell\Modules\AksHci\0.2.10' was installed without side-by-side version
support. Some versions are installed in this module base with side-by-side version support. Uninstall other versions of this module before uninstalling the most current version.
At line:1 char:1
+ uninstall-Package AksHci -RequiredVersion 0.2.10-alpha9 -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : UnableToUninstallModuleVersion,Uninstall-Package,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage
```

Any help would be appreciated.
Thanks!

**Comment by pradipd** [comment]
I figured it out. User error.  I made a copy (packagename-copy) of the package in the C:\Program Files\WindowsPowerShell\Modules folder.  Once I deleted that, everything worked.

**Comment by Dhakor** [comment]
Hi @pradipd could you explain me me how you'd solved this? I've the same issue with PSTeams Module, but I didn't understand your resolution.

`PS C:\Windows\system32> Uninstall-Module -Name MicrosoftTeams
PackageManagement\Uninstall-Package : The module 'MicrosoftTeams' of version '1.1.10-preview' in module base folder
'C:\Users\user\OneDrive\Documents\WindowsPowerShell\Modules\MicrosoftTeams\1.1.10' was installed without
side-by-side version support. Some versions are installed in this module base with side-by-side version support.
Uninstall other versions of this module before uninstalling the most current version.
En C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1: 12733 Carácter: 21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Packag
   e], Exception
    + FullyQualifiedErrorId : UnableToUninstallModuleVersion,Uninstall-Package,Microsoft.PowerShell.PackageManagement.
   Cmdlets.UninstallPackage

PS C:\Windows\system32> get-installedmodule MicrosoftTeams -AllVersions

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.1.10-preview       MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Win...
1.1.6                MicrosoftTeams                      PSGallery            Microsoft Teams cmdlets module for Win...`

**Comment by Dhakor** [comment]
Solved, same issue like you, moved the WPS folder to a different OD container and that change didn't get reflected on the loaded module
