### ISSUE TITLE
Add -Scope param to Uninstall-PSResource

### ISSUE THREAD

**Issue by alerickson** [PowerShell/PSResourceGet#309]
Add -Scope param to uninstall packages within a specific scope  CurrentUser would only uninstall packages from the currentUser scope, AllUsers would uninstall packages from its respective scope, default would be to uninstall the first package displayed when running `get-psresource <packagename>`

**Comment by weyCC81** [comment]
I would also like that parameter! https://github.com/PowerShell/PowerShell/issues/16729

**Comment by schittli** [comment]
Does M$ really need more than 1.5 year to fix this kind of issue? 
It's a shame for a basic system tool.

**Comment by SydneyhSmith** [comment]
Marking as a duplicate in favor of https://github.com/PowerShell/PowerShellGet/issues/615

**Comment by schittli** [comment]
Yet another Microsoft disgrace: they make so many billions from us customers that it's hard to count, but such simple and obvious feature requests are ignored for years.

**Comment by mgreenegit** [comment]
@schittli looking at the project page, this issue has been labeled a "P1" or "Priority 1" compared to the highest ranking items in "P0". If you feel that is not the correct priotization, can you please leave a comment in #616? It will help if you might be able to help all stakeholders understand which P0 project work you would rank below this item. Thank you!
Project: https://github.com/PowerShell/PowerShellGet/projects/14
