### ISSUE TITLE
Parent folder name must match module name in order for "Publish-PSResource" to successfully publish module

### ISSUE THREAD

**Issue by demdante** [PowerShell/PSResourceGet#319]
Powershellget version: 3.0.0
Powershell Version: 5.1

I recently ran into an issue when trying to create a automated build pipeline for a powershell module that I wrote (lets call it the workext module).  I had the build scripts in the repository's root, and the module itself was in a sub-folder named "module."  When I would pass the module folder's full path as a parameter to "Publish-PSResource", I would get an error:

No file with a .psd1 extension was found in C:\Users\john\Documents\git\workext\module\module.psd1

It is pretty clear that, based on the error, that the cmdlet is looking for a module that matches the name of the parent directory, which is a pretty crippling limitation.  Issue #305 also seems to be referencing this problem.  I am not sure what inconvenience @SydneyhSmith is referring to that would have led the powershell team to design the cmdlet this way, but the way that it functions as of now is unacceptably limiting.  Here are a couple of suggestions that I think would be resolve this issue:

1. Add an additional parameter and parameter set to allow users to pass a powershell module manifest file to the cmdlet.  Eg. Publish-PSResource -File "C:\Users\john\Documents\git\workext\module\workext.psd1"
2. I think it is safe to assume that a folder containing a powershell module is only going to have one powershell module manifest file.  So, rather than assume that the powershell module contained within the folder passed to the "-Path" parameter has the same name as aforementioned folder, why not scan the directory for the first instance of powershell module manifest file within that folder?  Eg. 

```
#all of this would be handled by the "Publish-PSResource" cmdlet
$manifest = Get-childitem "C:\Users\john\Documents\git\workext\module\*.psd1" #list all powershell module manifest files
$manifest[0].FullName #Publish this module
```

I think both of these solutions would fix the limitation of the current implementation of the cmdlet.

**Comment by SydneyhSmith** [comment]
thanks @demdante this is great feedback that we will take into consideration, I will link this to the issue you references #305 and mark as a duplicate
