### ISSUE TITLE
Find-Module does not fail gracefully if target resource is not found #13965

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PSResourceGet#335]
When searching for a resource in the PS Gallery, if the package is NOT found, an odd error is thrown, although with an accurate message. There is an error message thrown at line 8879 in a PSM1 file. Seems to me that the module should catch the error and fail more gracefully.

This issue was first filed at: https://github.com/PowerShell/PowerShell/issues/13965 but has been added to PowerShellGet repo.

## Steps to reproduce

```console

Find-Module -name ModuleThatDoeNotExist

Find-Package: C:\Users\tfl.COOKHAM\Documents\PowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:8879
Line |
8879 |          PackageManagement\Find-Package @PSBoundParameters | Microsoft …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module name 'ModuleThatDoeNotExist'. Try Get-PSRepository to see all available registered module
     | repositories.

```

## Expected behavior

```console
C:\Foo> Find-Module -Name  ModuleThatDoeNotExist
No match was found for the specified search criteria and module name 'ModuleThatDoeNotExist'. Try Get-PSRepository to see all available registered module repositories.
```

## Actual behavior

```console
PS C:\Foo> Find-Module -name ModuleThatDoeNotExist

Find-Package: C:\program files\powershell\7-preview\Modules\PowerShellGet\PSModule.psm1:8879:9
Line |
8879 |          PackageManagement\Find-Package @PSBoundParameters | Microsoft …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module name 'ModuleThatDoeNotExist'. Try Get-PSRepository to see all available registered module
     | repositories.
```

## Environment data

```console

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.2
PSEdition                      Core
GitCommitId                    7.2.0-preview.2
OS                             Microsoft Windows 10.0.21301
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.0-preview…
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

This issue was first filed at: https://github.com/PowerShell/PowerShell/issues/13965 but moved here.

**Comment by SydneyhSmith** [comment]
Thanks @doctordns for the great feedback-- in v3 we currently return nothing if no package is found, and with the `-Verbose` switch we return a message that the module was not found, but would love your feedback on this: 
![image](https://user-images.githubusercontent.com/43417619/106946493-035afe80-66de-11eb-8e5e-04e1df9c3052.png)

**Comment by doctordns** [comment]
That is so much better  :-)  thanks for the fix.

**Comment by alerickson** [comment]
This is will be addressed in Preview 11.

**Comment by doctordns** [comment]
Thinking about it - should I need a switch to see a 'resource not found' error?

If I use `Get-ChildItem` and specify a non-existent path, I do not need to use -Verbose to see the error?

```powershell
PS C:\Foo> gci foo.bar
Get-ChildItem: Cannot find path 'C:\Foo\foo.bar' because it does not exist.
```
