### ISSUE TITLE
PowershellGet breaks if using the same PSModulePath for both WinPS and PS7

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#341]
# Issue
It is common to symlink the windowspowershell modules folder to the powershell modules folder so that two separate folders do not have to be maintained. However, PowershellGet's current startup behavior is to pick one framework and then delete the other, which basically "binds" it to that particular framework.

# Recommended Resolution
Storage is cheap, and you've already taken up the storage space, why not just keep both assembly sets and just add-type in the ones to use based on $PSEdition being 'Desktop' or not?

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote we agree that's a scenario we'd like to support and will make the update

**Comment by alerickson** [comment]
This will be addressed with Preview 11.
