### ISSUE TITLE
powershell module names are case sensitive when using find-psresource, but only when using wildcard

### ISSUE THREAD

**Issue by demdante** [PowerShell/PSResourceGet#352]
This new version of powershellget appears to be case-sensitive in regards to module names that are passed to the cmdlets, but only when a wildcard is also used.  At least that is definitely the case for find-psresource.  Consider the output when running the below commands:

```
Find-PSResource azurerm
Find-PSResource azurerm*
Find-PSResource Azurerm*
Find-PSResource AzureRM*
```

As you can see, the last three commands contain wildcards.  The first command runs successfully and returns the output we want, despite the name not matching the name of the module in powershellgallery as far as case sensitivity is concerned.  The last three commands, however, returns three different results when run in the current, 3.0.0 version of powershellget.  See below image:

![find](https://user-images.githubusercontent.com/64720591/111082007-fb248900-84fd-11eb-8c61-3abd3db9c6fc.png)

I **believe** that this might be related to issue #304 , as I assume (possibly incorrectly) that, when a module name is not passed to find-psresource, a wildcard is passed by default.  Whether or not the issue described here is related to issue #304 , this behavior is not how the 2.2.5 version of powershellget (using find-module) behaved, as it was case insensitive, which you can see reflected when we run the exact same commands as above, but with the 2.2.5 version of powershellget using find-module:

### First and second commands

![1st](https://user-images.githubusercontent.com/64720591/111082410-05e01d80-8500-11eb-96f6-da5f6e61f63d.png)

### Third command

![3rd](https://user-images.githubusercontent.com/64720591/111082421-11334900-8500-11eb-8d34-1346c18431ce.png)

### Fourth command

![4th](https://user-images.githubusercontent.com/64720591/111082424-198b8400-8500-11eb-8acb-abc96fb4c13c.png)

**Comment by alerickson** [comment]
This will be resolved in Preview 11.
