### ISSUE TITLE
Feature Request: Publish Module Package-Only

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#354]
https://github.com/PowerShell/PowerShellGet/blob/e669ac1af1ced7ff33a2cba294cbd859e1c6ba12/srcOld/code/PublishPSResource.cs#L477

The remaining publish to repository after this line should be gated in a switch parameter e.g. `-BuildOnly`, that if specified instead emits the path to the built .nupkg file rather than publishing to a repository. This is useful if you want to use the nupkg in a different manner, say uploading to Github Artifacts, caching the build result, or other CI/CD driven activities.

Currently with PSGetv2 a workaround has to be done which is publish to a local file repository, this would be much faster and more explicit.

**Comment by SydneyhSmith** [comment]
Thanks @JustinGrote for Publish-PSResource we plan to add a -DestinationPath parameter (https://github.com/PowerShell/PowerShellGet/blob/0cae3522fae8f723bd9cd01bdeccfaf4f23ab09b/Docs/PublishPSResource.md#-destinationpath) which allows you to publish a nupkg to a local path...would this cover your scenario?

**Comment by JustinGrote** [comment]
Yes it would, this issue can be closed when that feature is merged in. Thanks!

**Comment by randomchance** [comment]
This...kinda works in the new RC, which is awesome 👍 
Being able to publish the `.nupkg` file to an arbitrary folder helps a ton when we are setting up build pipelines! 

Only issue is that it still throws an error, even though it technically works....

```powershell
[core ~\source\GITLAB\simpleenv ]  [master ≡ +7 ~0 -0 !]
[17:47:46 ] > Publish-PSResource  -Path '.\Output\1.2.0\SimpleEnv\' -DestinationPath '.\Output\' -Verbose -Debug

Confirm
Are you sure you want to perform this action?
Performing the operation "Publish-PSResource" on target "Publish resource 'C:\Users\xxxxxxxxx\source\GITLAB\simpleenv\Output\1.2.0\SimpleEnv\' from the machine".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
VERBOSE: Creating new nuspec file.
VERBOSE: The newly created nuspec is: C:\Users\xxxxxxxxx\AppData\Local\Temp\b36e1a59-612c-492d-8d91-d7f3e8e59909\SimpleEnv.nuspec
VERBOSE: Successfully packed the resource into a .nupkg
Publish-PSResource: Response status code does not indicate success: 401 (An API key must be provided in the 'X-NuGet-ApiKey' header to use this service). Please try running again with the -ApiKey parameter and specific API key for the repository specified.
VERBOSE: Not able to publish resource to 'https://www.powershellgallery.com/api/v2'
VERBOSE: Deleting temporary directory 'C:\Users\xxxxxxxxx\AppData\Local\Temp\b36e1a59-612c-492d-8d91-d7f3e8e59909'

```

My  versions: 

``` powershell
[17:54:48 ] > $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core

[17:56:18 ] > Get-PSResource -Name Powershellget

Name          Version Prerelease Repository Description
----          ------- ---------- ---------- -----------
PowerShellGet 3.0.12  beta       PSGallery  PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, Scripts, and DSC Resources.

```
