### ISSUE TITLE
Install-PSResource to custom location

### ISSUE THREAD

**Issue by jjolidon** [PowerShell/PSResourceGet#360]
Hello all,

It is currently possible to change the $env:PSModulePath easily to reference additional locations, but PowerShellGet does not offer the possibility to install to any custom location.

I see benefits, however, to implementing that feature. As an example, installing a module to a temporary location, then discarding it, e.g. during a build process.

I guess the parameter would be orthogonal to Scope, so a parameter set would be needed for it.

Let me know your thoughts
Jérôme Jolidon

**Comment by SydneyhSmith** [comment]
Thanks @jjolidon in PowerShellGet 3.0 you will be able to use the `Save-PSResource` cmdlet with the `-Path` and `-IncludeXml` parameter to install to any path..thanks!
