### ISSUE TITLE
An error when registering the default repository

### ISSUE THREAD

**Issue by ferenczy** [PowerShell/PSResourceGet#368]
I needed to set up a proxy server for the default PSGallery repository, and because the proxy configuration part of the [Register-PSRepository](https://docs.microsoft.com/en-us/powershell/module/powershellget/register-psrepository?view=powershell-7.1) command, I needed to unregister the repository first:

    Unregister-PSRepository -Name PSGallery

Then I tried to register it back (removed the proxy configurationsince it doesn't have any impact on the issue):

    Register-PSRepository -Default

The repository has actually been registered, but the command produced the following error:

>Value cannot be null.
Parameter name: input

According the [documentation](https://docs.microsoft.com/en-us/powershell/module/powershellget/register-psrepository?view=powershell-7.1), there're no mandatory parameters when using the command with the `-Default` switch (and even that one is optional).

Powershell version: 7.1.3
PowerShellGet version: 2.2.5

**Comment by SydneyhSmith** [comment]
Thanks @ferenczy sounds like you have a workaround and are correct on the expected behavior, we are having some trouble reproducing this...we will plan to make sure this error does not occur in PowerShellGet v3..thanks!

**Comment by anamnavi** [comment]
Hi @ferenczy, can you run `Get-PSRepository` and share the output please?

**Comment by ferenczy** [comment]
@SydneyhSmith Well, it's not exactly a workaround, I have just used everything as it's supposed to be used, it seems to be actually working as it's supposed to work, it just throws an error or a warning in the process. 🙂 Let me know if I can provide you more information or try anything that would help you to reproduce the error, please.
 
@anamnavi Sure, here it is. The `InstallationPolicy` was changed to `Trusted` later:

```powershell
$ Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Trusted              https://www.powershellgallery.com/api/v2
```

And here's the whole process of unregistering of the default PSGallery repository and registering it back repeated:

```powershell
$ Unregister-PSRepository -Name PSGallery

$ Get-PSRepository
WARNING: Unable to find module repositories.

$ Register-PSRepository -Default
Value cannot be null.
Parameter name: input

$ Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2
```

Details of the loaded PowerShellGet module:

```powershell
$ Get-Module PowerShellGet

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability…}
```

It's of the type "Script", so it's part of the Powershell Core installation, I guess.

**Comment by SydneyhSmith** [comment]
Thanks for letting us know @ferenczy this shouldnt be an issue with v3 because we will no longer have the dependency on PackageManagement, but we will test against this
