### ISSUE TITLE
*-package versus *-module - inconsistent command output object attributes

### ISSUE THREAD

**Issue by peppekerstens** [PowerShell/PSResourceGet#406]
functions Get-module, Update-Module, Install-Module and Get-Package produce different command output object attributes for the path where the module/package is installed. 

Problem
----------

code sniplet/function as example/proof:

```PowerShell
function Get-ModulePath {
    [cmdletbinding()]
    param(
        # input result from one of commented commands (some need -Passthru for this)
        [Parameter(Mandatory,ValueFromPipeline)]
        [object]$Name
    )
    $ErrorActionPreference = 'Stop'
    Try{
        #Get-module
        Split-Path -Path $Name.Path
    }Catch{
        Try{
            #Update-Module/Install-Module
            $Name.InstalledLocation
        }Catch{
            #Get-Package
            [xml]$ModuleTAG = $Name.SwidTagText
            $ModuleTAG.SoftwareIdentity.Meta.InstalledLocation
        }
    }
}
``` 

Proposal
-------------
introduce a generic attribute 'modulepath' to overcome breaking issues.
this new attribute should contain the result of above function

**Comment by peppekerstens** [comment]
Use cases are:

- some (default) json config for a certain function within that module
- determine path for build purposes (Arm/Dsc)

\<snipplet\>
```PowerShell
$VersionControl = Install-ModuleEx -Name $VersionControlModuleName -Repository $PSGetName -AccountName $PSGetAccount -Password $SecurePassword -Verbose:$MoreVerbose
$PSModulePath = $VersionControl | Get-ModulePath
$Solutions = Get-Content -Path "$($PSModulePath)\Solutions.json" | ConvertFrom-Json
While($Solutions.Name -notcontains $Solution){
    If($Solution){
        Write-Warning -Message "Solution $($Solution) not found! Please provide valid input."
    }Else{
        Write-Host "Detected solutions: $($Solutions.Name)"
    }
    $Solution = Read-Host "Download resources for which solution"
}  
``` 

To be clear; I do not propose to include the function Get-ModulePath in any form or way. My point is that it should not have to exist at all if the command output object attributes are more consistent....

**Comment by peppekerstens** [comment]
from: https://github.com/PowerShell/PowerShellGet/issues/378

**Comment by SydneyhSmith** [comment]
We are currently providing the install path in v3 in the object that is returned, can you confirm if this is still an issue with v3? thanks! https://www.powershellgallery.com/packages/PowerShellGet/3.0.16-beta16
