### ISSUE TITLE
Azure Artifacts Credential Provider: Response status code 401 (Unauthorized) when connecting to ADO Feed. PowerShellGet module 3.0.0-beta10

### ISSUE THREAD

**Issue by nbdinara** [PowerShell/PSResourceGet#427]
Hello!

I  am getting an 401 (Unauthorized) error when I try to connect to private ADO Feed using Azure Artifacts Credential Provider. Could you please help me to solve this issue?

I wanted to use Azure Credential Provider to supply personal access token and store it in environment variable VSS_NUGET_EXTERNAL_FEED_ENDPOINTS to provide to user seamless experience. 
I used this documentation: GitHub - microsoft/artifacts-credprovider: The Azure Artifacts Credential Provider enables dotnet, NuGet.exe, and MSBuild to interactively acquire credentials for Azure Artifacts feeds.

I installed the latest PowerShellGet module 3.0.0-beta10. 
When I executed command: Find-PSResource -ModuleName -<ModuleName>-Prerelease -Repository <FeedName>  I got the 401 code error. 

![image](https://user-images.githubusercontent.com/35890180/127411991-6f93a452-c0d6-494f-a75e-0102a9abbdf0.png)
 
Below are the actions that I already have done:

1) Result of running the credential provider directly:
https://github.com/Microsoft/artifacts-credprovider#how-do-i-find-out-if-my-issue-is-a-real-401

 
![image](https://user-images.githubusercontent.com/35890180/127412258-c4ef275c-8573-4273-b8b3-974e7d3a2417.png)

2) I also tried to play with $accessToken value and set it to $accessToken = "$B64Pat" and $accessToken = "Basic $B64Pat", but got the same error.
3)I played with url to the feed too. I used “https://<org name>.pkgs.visualstudio.com/36d6487b-86e3-45b4-8db5-e005872078d6/_packaging/<feed name>/nuget/v3/index.json” as value, but got the same error again.

4) When I did the same set of actions using PowerShellGet module 2.2.5, I get the error “No match was found for the specified search criteria and module name 'PbiWb'. Try Get-PSRepository to | see all available registered module repositories.”

 
![image](https://user-images.githubusercontent.com/35890180/127412414-5beddaed-15c9-49ff-84f9-0b311448069b.png)

Result of running the credential provider directly:

 
![image](https://user-images.githubusercontent.com/35890180/127412571-e50659b5-0115-4541-abe3-2d7a5448ddd8.png)

I have Owner level permission to the feed that I am trying to access:

Thank you, 
-Dinara

**Comment by alerickson** [comment]
Hi @nbdinara unfortunately we do not yet have credential persistence for PowerShellGet 3.x yet.  Our plan is to actually implement credential persistence that is a bit more simple to set up and use than the Azure Artifacts Credential provider.  We are planning on integrating with [SecretManagement](https://www.powershellgallery.com/packages/Microsoft.PowerShell.SecretManagement/1.1.0-preview2) and the [SecretStore](https://www.powershellgallery.com/packages/Microsoft.PowerShell.SecretStore/1.0.2) to provide for a better and smoother experience.

We are tracking this issue and its development here #330 and here #64.

Please let us know if you any suggestions or feedback for this issue!
