### ISSUE TITLE
Add -DestinationPath parameter to the Publish-PSResource cmdlet.

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PSResourceGet#430]
This is a reminder to add this new parameter set as an alternative location (other than a Repository selection) to publish a PSResource package.

```powershell
Publish-PSResource -Path c:\Modules\MyModule -DestinationPath c:\Packages
```

**Comment by SydneyhSmith** [comment]
We will implement this parameter as a separate parameter set

**Comment by SydneyhSmith** [comment]
Closing in favor of #468
