### ISSUE TITLE
Get-InstalledPSResource cmdlet name change

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#457]
Why was `Get-PSResource` changed to `Get-InstalledPSResource` in `3.0.11-beta`? This naming convention does match v2 but doesn't match the prefix of other v3 cmdlets. Plus there is a `-Path` parameter to change the directory that its looking at. In my option it should be changed back to the way it was in `3.0.0-beta10`.  As another example, `Get-Module` isn't called `Get-InstalledModule`. Installed is implied in these contexts when using the `Get` verb.

**Comment by anamnavi** [comment]
@ThomasNieto, we'll do this by the next preview release, thank you!
