### ISSUE TITLE
Find-PSResource is missing -AllVersions from v2

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#458]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

In v2 there is an `-AllVersions` switch parameter to list out all versions of a module. There is no way in v3 to find all available versions.

### Expected behavior

```console
PS C:\> Find-PSResource -Name PowerShellGet -AllVersions
```

### Actual behavior

```console
PS C:\> Find-PSResource -Name PowerShellGet -AllVersions
Find-PSResource: A parameter cannot be found that matches parameter name 'AllVersions'.
```

### Environment data

```powershell
PS C:\> Get-Module -Name PowerShellGet

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.11     beta       PowerShellGet                       {Find-PSResource, Get-InstalledPSResource, Get-PS…

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.8
PSEdition                      Core
GitCommitId                    7.2.0-preview.8
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anamnavi** [comment]
Hi @ThomasNieto , we changed this from V2 so instead of having an `-AllVersions` parameter switch, to get all versions of a package simply use `-Version "*"`. The `-Version` parameter is following the NuGet Package Versioning syntax and the help doc explains this a bit more in depth as well as lists a caveat to it: https://github.com/PowerShell/PowerShellGet/blob/master/help/Find-PSResource.md#-version
