### ISSUE TITLE
Parameter consistency: change URL to Uri

### ISSUE THREAD

**Issue by fsackur** [PowerShell/PSResourceGet#460]
### Summary of the new feature / enhancement

As a PS user who benefits from consistency in parameter names across modules,
- when I run `Register-PSResourceRepository`
  - I want to provide the URL to a parameter called `Uri` (not `URL`)
  - I want the param type to be `[uri]` (as for `Invoke-RestMethod` / `Invoke-WebRequest`),
- so that
  - I can discover the usage of the command more easily
  - I can re-use splats
  - I get validation by casting string to uri

### Proposed technical implementation details (optional)

- Simple rename in `src/code/SetPSResourceRepository.cs` and `RegisterPSResourceRepository.cs`
- I propose no alias; we're still pre-release
- `irm`/`iwr` declare the param as follows: 
```
    [Parameter(Mandatory=$true, Position=0)]
    [ValidateNotNullOrEmpty()]
    [uri]
    ${Uri},
```

**Comment by fsackur** [comment]
Happy to PR, if maintainers agree

**Comment by StevenBucher98** [comment]
That sounds good @fsackur! We'd appreciate that PR, feel free to submit it whenever you'd like.

**Comment by PaulHigin** [comment]
@anamnavi  The two effective commands are:

`Register-PSResourceRepository`
`Set-PSResourceRepository`

But we also need to be consistent with our error/warning/verbose messages to use `Uri` instead of `Url`.
Also, we should rename all internal methods and parameters to use `Uri`.

**Comment by fsackur** [comment]
I'm taking this style:
- capitalise 'URI' in quoted strings
- sentence-case identifiers

Is that considered correct?

E.g:
- https://github.com/fsackur/PowerShellGet/commit/6ebdb7ceac905de156d23f0a4ed7ddfbc7f909ae#diff-f3c0d4e26f9242b68bb0934042839d1bc9485613458d799e280adc2f20dda6b1L155-R156
- https://github.com/PowerShell/PowerShellGet/compare/master...fsackur:rename-param-url-to-uri#diff-0c9edef736ab881504abdf22e3e415cff3c15cddfe8260e83010ca0fa2198e5bL208-R208

**Comment by StevenBucher98** [comment]
Feel free to open a PR and we can do the review in that! Thank you so much! @fsackur
