### ISSUE TITLE
 Register-PSRepository needs to support -Scope AllUsers

### ISSUE THREAD

**Issue by RobCannon** [PowerShell/PSResourceGet#462]
### Summary of the new feature / enhancement

We have a secure environment and all of registries are private proxies which have to be registered with PowerShell in order to install approved packages.  So, everyone in out environment need to register the same repositories.  It would be more efficient if we could register or configure those proxies for all users of a system so individuals don't need to do that.
If there are registries registered for all users, then the default nuget registry should not need to be installed by a user in order to install packages.

**Comment by anamnavi** [comment]
Thanks for reaching out @RobCannon, this is a duplicate issue of #84 so closing this issue. We will add this feature in soon.
