### ISSUE TITLE
Install-PSResource: Unimplemented parameter sets need to be implemented

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PSResourceGet#468]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

n/a

### Expected behavior

```console
be implemented
```

### Actual behavior

```console
not yet implemented
```

### Error details

```console
-RequiredResource parameter needs to be implemented
-RequiredResourceFile parameter needs to be implemented
-IgnoreDifferentPublisher needs to be implemented
-Add progress bar back in
-PassThru needs to be added
```

### Environment data

```powershell
all
```

**Comment by SydneyhSmith** [comment]
Closing in favor of #515 #516 #517 #518 #519
