### ISSUE TITLE
Uninstall-PSResource: complete unimplemented parameter sets/parameters

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PSResourceGet#471]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

n/a

### Expected behavior

```console
be implemented
```

### Actual behavior

```console
not yet implemented
```

### Error details

```console
- add Prerelease parameter
```

### Environment data

```powershell
all
```

**Comment by SydneyhSmith** [comment]
This parameter would be used to uninstall all prerelease modules, we will close this for now but will re-open based on feedback/need
