### ISSUE TITLE
Update-PSResource: complete unimplemented parameter

### ISSUE THREAD

**Issue by anamnavi** [PowerShell/PSResourceGet#472]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

n/a

### Expected behavior

```console
be implemented
```

### Actual behavior

```console
not yet implemented
```

### Error details

```console
- add UpdateTo parameter
```

### Environment data

```powershell
all
```

**Comment by randomchance** [comment]
I believe the `-Reinstall` parameter is also missing, or, if it's not supposed to be there the warning for existing versions is incorrect - I have not looked to figure out which yet. 

```powershell
Update-PSResource -Name InvokeBuild -Force
WARNING: Resource 'InvokeBuild' with version '5.8.6.0' is already installed.  If you would like to reinstall, please run the cmdlet again with the -Reinstall parameter
WARNING: Resource 'InvokeBuild' with version '5.8.0' is already installed.  If you would like to reinstall, please run the cmdlet again with the -Reinstall parameter

```

**Comment by StevenBucher98** [comment]
Commenting for discussion, does adding the -reinstall parameter make sense in the `Update-PSResource`? Should it just be with the `Install-PSResource`. Not sure if this is the right approach or not. 

@randomchance do you prefer the `-reinstall` in Update or in the Install cmdlet?

**Comment by StevenBucher98** [comment]
@randomchance we are unable to reproduce your error, what prerelease version were you using? and does this still happen for you on the latest prerelease?

**Comment by randomchance** [comment]
@StevenBucher98  Finally where I can respond and I can't reproduce it anymore either - glad to see it marked done.
