### ISSUE TITLE
Blog says Install-PSResource has a -DestinationPath parameter in 3.0.11 but it does not

### ISSUE THREAD

**Issue by craiglandis** [PowerShell/PSResourceGet#473]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

From the the Features section of the 3.0.11 blog post - 

https://devblogs.microsoft.com/powershell/powershellget-3-0-preview-11-release/

"Install-PSResource has a -DestinationPath parameter which allows the user to specify the target directory instead of one based on the -Scope parameter (default Scope is CurrentUser). Note that in this release “x86” paths, and Linux paths are not yet supported. Expect to see this support in future releases."

But I don't see it. Maybe that blurb was intended to be under the "Features to Expect in Coming Preview Releases" instead of "Features"? Because "Features to Expect in Coming Preview Releases" mentions "Publish-PSResource will include a -DestinationPath parameter to publish a resource to a particular file path", so it seems curious that Publish-PSResource would get -DestinationPath in a different release than Install-PSResource gets -DestinationPath.

```
PS C:\> (Get-Command -Name Install-PSResource -FullyQualifiedModule @{ModuleName='PowerShellGet';ModuleVersion='3.0.11'}).Parameters.Keys | Sort-Object
AcceptLicense
Confirm
Credential
Debug
ErrorAction
ErrorVariable
InformationAction
InformationVariable
Name
OutBuffer
OutVariable
PipelineVariable
Prerelease
Quiet
Reinstall
Repository
Scope
TrustRepository
Verbose
Version
WarningAction
WarningVariable
WhatIf
```

### Expected behavior

```console
Unclear if Install-PSResource was supposed to get -DestinationPath in 3.0.11 as the blog says, or in a later release.
```

### Actual behavior

```console
Install-PSResource has no -DestinationPath parameter
```

### Environment data

```powershell
Including env for 7.1.3 but it repros the same in 5.1, 7.1.3 and 7.2.0-preview.8

PS C:\> Get-Module PowerShellGet

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.11     beta       PowerShellGet                       {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Install-PSResource…}

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anamnavi** [comment]
Hi @craiglandis thanks for bringing this to our attention, we'll update the blogpost accordingly. We are not going to include the `-DestinationPath` parameter for Install-PSResource, but will implement a `-IncludeXML` and `-Path` parameter for Save-PSResource and this will essentially install to a specified path.

**Comment by craiglandis** [comment]
> Hi @craiglandis thanks for bringing this to our attention, we'll update the blogpost accordingly. We are not going to include the `-DestinationPath` parameter for Install-PSResource, but will implement a `-IncludeXML` and `-Path` parameter for Save-PSResource and this will essentially install to a specified path.

Will cloud drives (for example OneDrive) be supported PSModulePath locations? And will that future Save-PSResource -IncludeXml/-Path support let us install modules in OneDrive?

For example, I'd love to include something like C:\OneDrive\Modules in my PSModulePath so that any module I install on one of my machines is automatically installed in my other machines because they would all have C:\OneDrive\Modules in their PSModulePath. Currently module management across multiple machines is a pain - you have to manually install/uninstall modules on each machine to keep a consistent set of modules across them all.

**Comment by SydneyhSmith** [comment]
Yep @craiglandis OneDrive is a scenario we plan to support. Going to close this issue as we are tracking the work in Save-PSResource https://github.com/PowerShell/PowerShellGet/issues/470
