### ISSUE TITLE
Support a "post install" action

### ISSUE THREAD

**Issue by kceiw** [PowerShell/PSResourceGet#476]
### Summary of the new feature / enhancement

As a user, I want to use the the module [Az.Tools.Predictor](https://www.powershellgallery.com/packages/Az.Tools.Predictor/0.4.0) after I install the module so that I can get the intelligent suggestions out of box.

### Proposal
Add a "post install" action. The module author can use that action to configure the user environment. So that the user can use it out of box. The it's better that "post install" action support user input too.

### Background
Az.Tools.Predictor implements a PowerShell extension api. That's used by PSReadLine to provide the suggestions to the end user. All Az.Tools.Predictor's functionality is via that extension api, meaning that the user don't invoke any cmdlet. We provide some cmdlet to help the user to configure the default environment to use the tool.

PSReadLine is integrated with PowerShell so it's loaded when PowerShell starts. But any other modules are not imported automatically. That means if the end user install the module Az.Tools.Predictor, they still can use PSReadLine without explicitly importing the module. But the end user still misses the suggestions provided by Az.Tools.Predictor since the module isn't imported.

We provide a cmdlet `Enable-AzPredictor` to mitigate that. What it does is 
1. Implicitly import the module Az.Tools.Predictor
2. Configure PSReadLine to include the suggestions from Az.Tools.Predictor

The issue is that the user has to do that every time, unless the user puts it in the $PROFILE.

### The existing user experience
1. Install the module
1. Open PowerShell if the user closes the previous PowerShell session.
2. Run `Enable-AzPredictor`
3. Start to use Az commands and get suggestions from Az.Tools.Predictor

### The Problem
We found there are hundreds of downloads of the module but the user count is much less than that. Our hypothesis is that the user doesn't know the step 2. Most PowerShell modules provide the cmdlets. The module is imported when the cmdlet is run. But in this case, the module doesn't provide the essential cmdlet. The essential here I mean it's not something the end user has to run to finish their job. There is no obvious way for us to tell the user the step to enable az predictor.

### How we use the "post install" action
When the user installs the module "Az.Tools.Predictor". And we have a simple script in the "post install" action. The script asks the user to confirm whether they want to enable az predictor in $PROFILE. If so, it'll add Enable-AzPredictor in $PROFILE.

### Updated user experience
1. Install the module.
<The script from "post install" action runs>
2. Confirm to add `Enable-AzPredictor` to $PROFILE and the existing session.
3. Open PowerShell if the user closes the previous PowerShell session.
4. Start to use Az commands and get suggestions from Az.Tools.Predictor.

**Comment by kilasuit** [comment]
>Add a "post install" action. The module author can use that action to configure the user environment. So that the user can use it out of box. The it's better that "post install" action support user input too.

This IMO should only be a post-install suggestion, which really should be a pointer to documentation (whether online or shipped with the resource that has been installed) and not be something that can issue off any other automated action, especially not without, user confirmation of that action or by them having set an entry in `$PSDefaultParameterValues` 

Making it a suggestion, not an action, keeps the user in control, & stops an area for abuse. Just thinking from the admin/defender's point of view here,

That said, you can get some of this already today, using a `ScriptsToProcess` in the PSD1 on Import (not the install) of a module, which for me makes more sense as you can control the logic there and can set a `this has already run` config option somewhere else.

But adding a "post install message" that's surfaced in the PSD1 of the module in the PSData element, could be a way forward here and not break anyone going forward.

**Comment by SydneyhSmith** [comment]
I think it would be an interesting feature request For PowerShell to have a file location or other way of indicating modules you want loaded at startup
