### ISSUE TITLE
Support Azure Artifacts as a core scenario

### ISSUE THREAD

**Issue by chriskuech** [PowerShell/PSResourceGet#48]
JavaScript, C#, Java, and Python all have well-defined processes for
* publishing and hosting private modules in Azure Artifacts
* using Azure Artifacts as a secure mirror for public repositories

While there was a recently published [guide](https://devblogs.microsoft.com/powershell/using-powershellget-with-azure-artifacts/) on the subject, I have been unable to get it working (presumably due to PowerShell/PowerShellGetv2#433 ), and even still, there is no information on added PowerShell Gallery as an upstream package source, so there is no way of applying Component Governance to PowerShell modules or avoiding downloading from a public repository, which is forbidden in many security contexts.

Using Azure Artifacts as a private repository and mirror should be a core priority for PowerShellGet, as it enables PowerShell developers to operate at the same pedigree as application developers.  Please use this scenario when prioritizing features and writing documentation.

**Comment by Happycoil** [comment]
Is this resolved in Preview 1? I'm getting the following (url has been anonymized):
```
PS /Users/tm> Register-PSResourceRepository -Name test-powershell -URL "https://pkgs.dev.azure.com/<org>/<project>/_packaging/test-powershell/nuget/v3/index.json" -Credential $creds
PS /Users/tm> Find-PSResource -Repository test-powershell -Credential $creds
No cursor found. Defaulting to 01/01/0001 00:00:00.
Find-PSResource: Unable to load the service index for source https://pkgs.dev.azure.com/<org>/<project>/_packaging/test-powershell/nuget/v3/index.json.
```
