### ISSUE TITLE
Missing -SourceLocation and -ScriptSourceLocation in the Register-PSResourceRepository cmdlet

### ISSUE THREAD

**Issue by msft-jasonparker** [PowerShell/PSResourceGet#481]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I am trying to register a file based repository using v3.0.11-beta, but the cmdlet for registering the repository only accepts a URL.

### Expected behavior

```console
PS> Register-PSResourceRepository -Name MyRepo -SourceLocation "\\server\share" -ScriptSourceLocation "\\server\share"
```

### Actual behavior

```console
Parameters do not exist
```

### Environment data

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     3.0.11     PowerShellGet                       {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Install-PSResource...}

Key   : PSVersion
Value : 5.1.19041.1151
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.19041.1151
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by anamnavi** [comment]
Hi @msft-jasonparker thanks for reaching out,

With this preview version the `-URL` parameter encompasses File based URIs, as well as URIs with a HTTP, HTTPS or FTP schema. So you can provide file based paths to the `-URL` parameter.

Here's an example from the help doc [linked here](https://github.com/PowerShell/PowerShellGet/blob/master/help/Register-PSResourceRepository.md) -> Example 3. The `URL` will take a file based bath of `"c:/code/testdir"`. I'll update the help doc asap to include an example where I'm registering a single file based repository to showcase this more clearly.

Also per the doc linked above, you don't need a separate file based location for scripts location and for non-scripts. 

So in your example, you would do:
`Register-PSResourceRepository -Name MyRepo -URL "\\server\share"`

If you encounter any issues with this please open a new issue, or let us know. Thank you!
