### ISSUE TITLE
Register-PSRepository does not save basic auth credentials, Publish-Module does not work against repository with basic authentication

### ISSUE THREAD

**Issue by gahujipo** [PowerShell/PSResourceGet#51]
This is a follow up for PowerShell/PowerShellGetv2#60 

Steps to reproduce
------------------
We set up a Nuget.Server based on https://github.com/NuGet/NuGet.Server. We secured it with basic authentication to make the packages accessible only for authenticated users based on [this guide](http://blog.fermium.io/nuget-server-with-basic-authentication/). So it's basically a standard Nuget-Server with activated HTTP basic authentication. Install-Module, Find-Module and so on works perfectly fine. But Publish-Module fails. 

```powershell
$cred = Get-Credential
#enter the credentials which are neccessary to pass the basic authentication
Register-PSRepository -Name reponame -SourceLocation "<URL to the private repo>" -PublishLocation "<URL to the repo>" -Credential $cred
Publish-Module  -Repository reponame -Path <path to the module which should be published> -NuGetApiKey <API Key> -Credential $cred
```

Expected behavior
-----------------

```none
The module should be published/pushed to the Nuget-Server.
```

Actual behavior
---------------

```none
Publish-PSArtifactUtility : Failed to publish module '<modulename>': 'Cannot prompt for input in non-interactive mode.
".
In C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1227 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility
```

Additional notices and workaround
----------------
When doing the above steps with "plain" nuget.exe I was able to push to the repo even with basic authentication enabled. Steps to do that
```powershell
$cred = Get-Credential
nuget source add -Name reponame -Source <URL to the repo> -User $cred.UserName -Pass $cred.GetNetworkCredential().Password
nuget push <path to built .nupkg> -apikey <API key> -Source reponame
```
This works. But be aware that username and password get written to $env:appdata\Roaming\Nuget\NuGet.Config when you register the repo via plain nuget. -Credential arg on Register-PSRepository seems to get ignored. 
Following works: 
```powershell
nuget source add -Name testrepo -Username <Username to use on the repo for basic auth> -pass <Password to use on the repo for basic auth>
```
Open file $env:appdata\Roaming\Nuget\NuGet.Config and look for the repository name you registered via Reigster-PSRepository, eg. "reponame". rename the XML tags <testrepo> and </testrepo> to the name you use for your psrepo; in the above examples reponame. Execute
```powershell
Publish-Module  -Repository reponame -Path <path to the module which should be published> -NuGetApiKey <API Key> -Credential $cred
```
again and you will see that pushing works.

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```powershell
> Get-Module -ListAvailable PowerShellGet,PackageManagement
Get-Module -ListAvailable PowerShellGet,PackageManagement
```

```powershell
> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, Filter, Tag, Includes, DscResource, RoleC...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
```

**Comment by ThePoShWolf** [comment]
Apparently this is an issue that I've been having for ages but didn't realize there was an official issue for it. I'm looking forward to this being fixed in 3.0! I did just test 3.0.0-beta1, and it still does not cache the credentials.

**Comment by SydneyhSmith** [comment]
Closing as a duplicate

**Comment by gahujipo** [comment]
@SydneyhSmith which issue follows this problem now?

**Comment by SydneyhSmith** [comment]
We are tracking credential persistence with this issue: https://github.com/PowerShell/PowerShellGet/issues/64
and the current behavior of the credential parameter in Register with with issue https://github.com/PowerShell/PowerShellGet/issues/102
