### ISSUE TITLE
Install-psresource and save-psresource do not install powershell scripts

### ISSUE THREAD

**Issue by demdante** [PowerShell/PSResourceGet#514]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

As the title states, Install-psresource is not able to install powershell scripts.  In my case, I am tring to install the "send-file" powershell script that is hosted in the powershell gallery.  You can see the resource when you run 

```
Find-PSresource send-file
```

![image](https://user-images.githubusercontent.com/64720591/137849942-3fea4d21-1a3e-429e-a580-70e190ddc5bc.png)

But when trying to install the hosted script from powershell gallery, nothing happens.  It doesn't install and it appears that powershell just returns a null value.  

![image](https://user-images.githubusercontent.com/64720591/137850108-3eb31b6e-708a-4cbb-988f-5e9d676cff71.png)

I was able to install the hosted powershell script using powershellget v2 perfectly fine using install-script.  All of the above is also applicable to save-PSResource.

### Expected behavior

```console
Install-psresource send-file

Should install hosted powershell script from powershell gallery
```

### Actual behavior

```console
Install-psresource send-file

Returns null and script is not installed.
```

### Error details

```console
No error is returned
```

### Environment data

```powershell
PS C:\Windows\system32> Get-Module Powershellget; $PSVersionTable

ModuleType Version    Name                                ExportedCommands                                                                                               
---------- -------    ----                                ----------------                                                                                               
Binary     3.0.11     PowerShellGet                       {Find-PSResource, Get-InstalledPSResource, Get-PSResourceRepository, Install-PSResource...}                    

Key   : PSVersion
Value : 5.1.22000.65
Name  : PSVersion


Key   : PSEdition
Value : Desktop
Name  : PSEdition


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions


Key   : BuildVersion
Value : 10.0.22000.65
Name  : BuildVersion


Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

### Visuals

See original post.  Not doing all that again.

**Comment by StevenBucher98** [comment]
Thanks @demdante! Can you run your same install command but include a `Install-psresource send-file
-Verbose` command? We will also investigate further on our side and get back to you.

**Comment by alerickson** [comment]
@demdante this is resolved with our latest release, which will be out in the next 2 weeks.
