### ISSUE TITLE
Install-PSResource: implement -RequiredResource and -RequiredResourceFile 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#515]
For Install-PSResource we still need to implement -RequiredResource and -RequiredResourceFile parameters

**Comment by StevenBucher98** [comment]
Adding additional details from [blog posts](https://devblogs.microsoft.com/powershell/powershellget-3-0-preview-12-release/):

Install-PSResource will accept a path to a psd1 or JSON file (using -RequiredResourceFile), or a hash table or JSON (using -RequiredResource) where the key is the module name and the value is either the required version specified using Nuget version range syntax or a hash table where repository is set to the URL of the repository and version contains the Nuget version range syntax.
```powershell
Install-PSResource -RequiredResource @{
  Configuration = "[1.3.1,2.0]"

  Pester        = @{
    version = "[4.4.2,4.7.0]"
    repository = "https://www.powershellgallery.com"
    credential = $cred
    allowPrerelease = $true
  }
}
```
In this case the modules named “Configuration”, and “Pester” will be installed. The JSON format will be the same as if this hashtable is passed to ConvertTo-Json:

```JSON
{
  "Configuration": "[1.3.1,2.0]",

  "Pester": {
    "version": "[4.4.2,4.7.0]",
    "credential": null,
    "repository": "https://www.powershellgallery.com",
    "allowPrerelease": true
  }
}
```
