### ISSUE TITLE
Publish-Module forces semantic versioning regardless of manifest version

### ISSUE THREAD

**Issue by ChrisLGardner** [PowerShell/PSResourceGet#56]
If I have a module using 4 part versioning which ends in a 0 (1.2.0.0) that I try to publish using Publish-Module then it create a nupkg and nuspec with the version number 1.2.0 but leaves the manifest correct. After digging into the code and PowerShell/PowerShellGetv2#218 it looks like a problem with using `dotnet.exe` or a newer version of `nuget.exe` (3+). The initial nuspec file generated by the `Publish-PSArtifactUtility` function

If a manifest is using 4 part versioning then the nupkg and contained nuspec should reflect this regardless of which application was used to generate the nupkg.

This isn't a big problem for the PowerShell Gallery but some nuget providers are seeing both the nupkg version and the manifest version. Our internal ProGet instance is doing pass through to the PSGallery and it's showing two versions for any modules published like this, both 1.2.0.0 and 1.2.0, and this is causing further issues.

**Comment by SydneyhSmith** [comment]
I am seeing the fourth digit respected, but a zero added if a module has only two digits

![image](https://user-images.githubusercontent.com/43417619/91219478-8c9dec00-e6cf-11ea-93c2-a7803c97c81a.png)

**Comment by ChrisLGardner** [comment]
I'll grab the latest build of 3 and test it again. The main issue I saw for 4 part versions was when the 4th was a 0, it was fine with anything else there.

**Comment by alerickson** [comment]
@ChrisLGardner this should be resolved with [beta10](https://www.powershellgallery.com/packages/PowerShellGet/3.0.0-beta10).  Please let us know if you're still having this issue or similar issues so we can get a fix in before our GA.
