### ISSUE TITLE
PowerShellGet Contributing Docs, README fix, and PR Checklist

### ISSUE THREAD

**Issue by StevenBucher98** [PowerShell/PSResourceGet#562]
### Summary of the new feature / enhancement

With an upcoming 3.0 GA for PowerShellGet, we need a better documentation for community contributions. This way community members can have better direction with PowerShellGet best practices and can speed up the process of accepting community feature contributions. 

Current proposed flow:
- Check if problem is in existing issue
- Open an issue for discussion from the PowerShellGet team and community to best understand scenario
- If determined to have enough merit for a PR and community member is willing to submit a PR, then a PR can be created
- If PR meets all checklist items and approval from PowerShellGet team then it will be merged.

### Proposed technical implementation details (optional)

A better flow to the contributing docs can be created through these fixes:
- Create a more concise README
    - Breaking out sections of README into own docs when it makes sense
- Create a Contributing doc 
    - Outlines flow described above.
    - Includes details similar to the [PowerShell Contributing doc](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md)
    - Include engineering best practices 
- Create a PR checklist

**Comment by alerickson** [comment]
I believe we have all this incorporated now :)
