### ISSUE TITLE
Automation for Changelog

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#563]
### Summary of the new feature / enhancement

We should create automation to generate our changelog based on PRs

**Comment by alerickson** [comment]
Just wondering if the VSCode extension or any other repo has something we can snag for this.  If it's small, it might be nice to try it out for the release of 3.0.13-beta

**Comment by SydneyhSmith** [comment]
Looks like the extension uses this function https://github.com/PowerShell/vscode-powershell/blob/697b23c244b939e8e3e9d12f5975f23ebefeabf7/tools/ReleaseTools.psm1#L220 
hopefully with some updates we can reuse...and @andschwa may be able to help us out with questions

**Comment by andyleejordan** [comment]
Totally! It's probably the most recently written script, though we have similar things in PowerShell/PowerShell etc. too.
