### ISSUE TITLE
Improve help for Publish-Module to include Help for the Path ParameterSets

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSResourceGet#57]
The current help for Publish-module doesn't include any examples of using the Path ParameterSets.

**Comment by iricigor** [comment]
Is [this ](https://github.com/PowerShell/PowerShell-Docs/blob/release-62/reference/6/PowerShellGet/Publish-Module.md) the proper place where that update should be done? How it goes, it should be added to all versions (6, 5.1, 5.0,...) where applicable or only help for version 6 is maintained?

**P.S.** It is also missing description for `-AllowPrerelease` - it has only `{{Fill AllowPrerelease Description}}`

**Comment by alerickson** [comment]
We now have this documented for v3.
