### ISSUE TITLE
You have an older version of PackageManagement known to cause issues with the PowerShell extension. Would you like to update PackageManagement (You will need to restart the PowerShell extension after)?

### ISSUE THREAD

**Issue by DawidGrzejek** [PowerShell/PSResourceGet#575]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all [issues](https://github.com/PowerShell/vscode-powershell/issues?q=is%3Aissue) to ensure it has not already been reported.
- [X] I have read the [troubleshooting](https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md) guide.
- [X] I am sure this issue is with the _extension itself_ and does not reproduce in a standalone [PowerShell](https://github.com/PowerShell/PowerShell/issues/new/choose) instance.
- [X] I have verified that I am using the latest version of Visual Studio Code and the PowerShell extension.

### Summary

After installing (as Admin) PowerShell extension I got a warning: "You have an older version of PackageManagement known to cause issues with the PowerShell extension. Would you like to update PackageManagement (You will need to restart the PowerShell extension after)?"

After clicking "Yes":
1. PackageManagement updated, If you already had PackageManagement loaded in your session, please restart the PowerShell extension.
2. PackageManagement\Get-PackageSource : Unable to find repository 'PSGallery'. Use Get-PSRepository to see all available repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4489 char:35
+ ... ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSource], Exception
    + FullyQualifiedErrorId : SourceNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource

I restart Visual Studio Code, and warning occur again:
1.You have an older version of PackageManagement known to cause issues with the PowerShell extension. Would you like to update PackageManagement (You will need to restart the PowerShell extension after)?
2. PackageManagement updated, If you already had PackageManagement loaded in your session, please restart the PowerShell extension.
3. PackageManagement\Get-PackageSource : Unable to find repository 'PSGallery'. Use Get-PSRepository to see all available repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:4489 char:35
+ ... ckageSources = PackageManagement\Get-PackageSource @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...etPackageSource:GetPackageSource) [Get-PackageSource], Exception
    + FullyQualifiedErrorId : SourceNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackageSource

After all of that if I run my scripts they work just fine but error occur every time I launch VSC.

Also I don't know if problem isn't related to fact, that I'm using proxy in my company and maybe VSC can face problem to connect to some server to download neccesery repos.

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visual Studio Code Version

```console
1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64
```

### Extension Version

```console
ms-vscode.powershell@2021.10.2
```

### Steps to Reproduce

1. Install Visual Studio Code for Windows 10
2. Install Power Shell Extension
3. Problem should occur

**Comment by StevenBucher98** [comment]
Thanks @DawidGrzejek! Did you try any of the mitigation fix in the https://aka.ms/psgallerytls url? 
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
Install-Module PowerShellGet -RequiredVersion 2.2.4 -SkipPublisherCheck`

**Comment by DawidGrzejek** [comment]
Sorry @StevenBucher98  Yes I did:
```
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'PowerShellGet'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Her is a result for `Invoke-WebRequest 'https://www.powershellgallery.com/api/v2/'`

```
Invoke-WebRequest : <!DOCTYPE html>
<html>
<!-- FileName: index.html
     Language: [en]
-->
<!--Head-->
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <title>McAfee Web Gateway - Notification</title>
  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />
</head>
<!--/Head-->
<!--Body-->
<body onload="swOnLoad();">
  <table class='bodyTable'>
    <tr>
      <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/default/img/cabp_bg_body.jpg'>
<!--Logo-->
<table class='logoTable'>
  <tr>
    <td class='logoData'>
      <a href='http://intranet.creditagricole'>
        <img src='/mwg-internal/de5fs23hu73ds/files/default/img/cabp_logo.png'></a>
    </td>
  </tr>
</table>
<!--/Logo-->
<!--Contents-->
<!-- FileName: authenticationrequired.html
     Language: [en]
-->
<!--Title-->
<table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
  <tr>
    <td class='titleData'>
      Authentication Required
    </td>
  </tr>
</table>
<!--/Title-->
<!--Content-->
<table class="contentTable">
  <tr>
    <td class="contentData">
      You must be authenticated to access this URL.
    </td>
  </tr>
</table>

<script language="javascript" type="text/javascript">
   urlprotocol = "https";
   statuscode=407;
   if(statuscode==401 && urlprotocol == "ftp"){
      document.write("<form name=\"ftpform\" method=\"get\" action=\"\">");
      document.write("<table class=\"contentData\">");
      document.write("<tr><td class=\"contentData\" colspan=2>Please enter your credentials in the form below and click \"Access FTP\" button if your browser doesn't present authentication prompt for FTP sites.</td></tr>");        
      document.write("<tr><td class=\"contentData\">Username:</td><td><input type=\"text\" id=\"ftpUsername\" name=\"ftpUsername\" size=40 /></td></tr>");
      document.write("<tr><td class=\"contentData\">Password:</td><td><input type=\"password\" id=\"ftpPassword\" name=\"ftpPassword\" size=40 /></td></tr>");
      document.write("<tr><td class=\"contentData\" colspan=2 align=center><input type=\"button\" onclick=\"redirectToFTP();\" value=\"Access FTP\" /></td></tr>");
      document.write("</table>");
      document.write("</form>");
   }

   function redirectToFTP(){
      var username=escape(document.getElementById("ftpUsername").value);
      var password=escape(document.getElementById("ftpPassword").value);
      location.href = "ftp://"+username+":"+password+"@www.powershellgallery.com:443"
   }
</script>
<!--/Content-->
<!--Info-->
<table class="infoTable">
  <tr>
    <td class="infoData">
      <b>URL: </b><script type="text/javascript">break_line("https://www.powershellgallery.com");</script><br />
    </td>
  </tr>
</table>
<!--/Info-->
<!--/Contents-->
<!--Policy-->
<!--
<table class='policyTable'>
  <tr>
    <td class='policyHeading'>
      <hr>
      Company Acceptable Use Policy
    </td>
  </tr>
  <tr>
    <td class='policyData'>
      This is an optional acceptable use disclaimer that appears on every page. You may change the wording or remove this section entirely in index.html.
    </td>
  </tr>
</table>
-->
<!--/Policy-->
<!--Foot-->
<table class='footTable'>
  <tr>
    <td class='helpDeskData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
      For assistance, please contact your system administrator.
    </td>
  </tr>
  <tr>
    <td class='footData'>
      generated <span id="time">2022-01-11 08:00:30</span> by McAfee Web Gateway<br>
      client ip: 172.20.254.166, proxy server: MWG1B<br>
      Mozilla/5.0 (Windows NT; Windows NT 10.0; pl-PL) WindowsPowerShell/5.1.19041.1320
    </td>
  </tr>
</table>
<!--/Foot-->
      </td>
    </tr>
  </table>
  <script type="text/javascript">
    setTimeout(function() {
      var bodyTable = document.getElementsByClassName('bodyTable');
      if (bodyTable.length > 0) {
        bodyTable[0].classList.add('showUp');
      }
    }, 0);
  </script>
</body>
<!--/Body-->
</html>
At line:1 char:1
+ Invoke-WebRequest 'https://www.powershellgallery.com/api/v2/'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by StevenBucher98** [comment]
Thanks for trying that @DawidGrzejek! We believe this might be an issue with your proxy, we believe you will need to use the `-Proxy` and `-ProxyCredential` paramters. 

Also do you have this issue outside of VSCode extension experience?

**Comment by DawidGrzejek** [comment]
@StevenBucher98 Perfoming Install-Module PowerShellGet in Windows PowerShell ISE:
![image](https://user-images.githubusercontent.com/42537540/149752070-fe3d7036-bdd6-42af-bff5-3217c6c53a75.png)
```
WARNING: Version '1.0.0.1' of module 'PowerShellGet' is already installed at 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.
0.0.1'. To install version '2.2.5', run Install-Module and add the -Force parameter, this command will install version '2.2.5' in side-by
-side with version '1.0.0.1'.
```

After that I did perfom comand `Install-Module PowerShellGet -RequiredVersion 2.2.4 -SkipPublisherCheck` on PowerShell ISE. And It seems like I worked:
```
PS C:\WINDOWS\system32> Get-InstalledModule

Version    Name                                Repository           Description                                                         
-------    ----                                ----------           -----------                                                         
1.4.7      PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a new way to discover and in...
2.2.4      PowerShellGet                       PSGallery            PowerShell module with commands for discovering, installing, upda...
2.2.0.2    PSWindowsUpdate                     PSGallery            This module contain cmdlets to manage Windows Update Client.     
```   

I'll try to set my proxy in VSCode right and it should work.

**Comment by StevenBucher98** [comment]
Great! @DawidGrzejek we will close this issue and reopen if you have any further difficulty.
