### ISSUE TITLE
Unexpected behavior of Get-PSResource command

### ISSUE THREAD

**Issue by nbdinara** [PowerShell/PSResourceGet#576]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

When I run `Get-PSResource  Az -Version '*' -ErrorAction SilentlyContinue` command in CONSOLE WINDOW it returns nothing. Which is expected behavior since Az module is not installed on my machine

But when I run the same command as part of the SCRIPT it returns Microsoft.PowerShell.PowerShellGet.UtilClasses.PSResourceInfo object. 

Why this happening? 

### Expected behavior

```console
PS> Get-PSResource  Az -Version '*' -ErrorAction SilentlyContinue
*nothing since Az module is not installed*
```

### Actual behavior

```console
PS> Get-PSResource  Az -Version '*' -ErrorAction SilentlyContinue
Microsoft.PowerShell.PowerShellGet.UtilClasses.PSResourceInfo
```

### Environment data

```powershell
PowerShellGet 3.0.12
PowerShell 7.2.0
```

**Comment by SydneyhSmith** [comment]
Thanks @nbdinara I am having trouble reproducing this with our latest version, can you let me know if you are still having this problem
