### ISSUE TITLE
Install-PSResource fails with error: Failed to fetch results from V2 feed at...

### ISSUE THREAD

**Issue by nbdinara** [PowerShell/PSResourceGet#577]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Install-PSResource Az -Scope CurrentUser -TrustRepository -Reinstall 
Command failed with error: 
![image](https://user-images.githubusercontent.com/35890180/146250003-40677372-62d6-42bf-8bd2-2d619e2c4724.png)
The issue is flaky. 

When I do the same with Import-Module command everything works as expected. 

### Expected behavior

```console
PS> Install-PSResource Az -Scope CurrentUser -TrustRepository -Reinstall 
Installs Az module
```

### Actual behavior

```console
PS> Install-PSResource Az -Scope CurrentUser -TrustRepository -Reinstall 
Throws an error (on screenshot)
```

### Environment data

```powershell
PowerShellGet 3.0.12
PowerShell 7.2.0
```

**Comment by StevenBucher98** [comment]
Thanks for bringing this to our attention @nbdinara! Do you mind running the command again but with the `-Verbose` paramter and sharing the output?

Can you also share the output of `Get-Module Az -ListAvailable`?
