### ISSUE TITLE
Rename or alias the "PrereleaseLabel" property to match the display column "Prerelease" 

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSResourceGet#578]
### Summary of the new feature / enhancement

It's confusing to `Find-PSResource PowerShellGet -Prerelease -Version *` and see the `Prerelease` column, and then try to  `| Format-Table Name, Version, Prerelease, Tags` and find there's no content in that third column...

### Proposed technical implementation details (optional)

Please add an AliasProperty or rename the original property

**Comment by StevenBucher98** [comment]
Thanks @Jaykul! We will look at fixing this for the next release!
