### ISSUE TITLE
Create psget command for installing modules privately, like nuget

### ISSUE THREAD

**Issue by splatteredbits** [PowerShell/PSResourceGet#580]
### Summary of the new feature / enhancement

As a user, I want to be able to install modules privately across code repositories so I don't need to have them installed globally.

I'd like a command, `psget`, that behaves like `nuget`. You tell it to install modules and it reads what modules to install from a configuration file, psget.json, and installs them in the directory of the psget.json file, in a `PSModules` directory.

We use PowerShell as the foundation of our build, deploy, and installation platform. We have many modules that are required in each stage of our pipelines. We also have many, many different repositories each with different dependencies and version requirements. We want to be able to install, at build time, our dependent modules privately, in a PSModules directory in each repository. I'd like to run `psget install` to get them.

**Comment by kilasuit** [comment]
Sounds like you want either [PSDepend ](https://www.powershellgallery.com/packages?q=PSDepend) or [Install-RequiredModule](https://www.powershellgallery.com/packages/Install-RequiredModule/5.0.2) 

Both are already in the gallery Install-RequiredModule seems to be more actively maintained than PSDepend is

**Comment by StevenBucher98** [comment]
Thanks @splatteredbits, we are working on implementing this in PowerShellGet, related issue is #146. Marking as duplicate.
