### ISSUE TITLE
Install-PSResource -SkipPublisherCheck parameter

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#589]
### Summary of the new feature / enhancement

We should have a -SkipPublisherCheck parameter for Install-PSResource

**Comment by alerickson** [comment]
I'm closing this issue as a dup of https://github.com/PowerShell/PowerShellGet/issues/519

**Comment by alerickson** [comment]
Would be helpful if I read my own comments before reopening 😓
