### ISSUE TITLE
If no package is uninstalled the cmdlet should emit an error

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#598]
### Summary of the new feature / enhancement

If no package is uninstalled during a run of `Uninstall-PSResource` the cmdlet should emit a warning so that the user knows no action was completed. The warning can suggest users run `Get-PSResource`.

Alternatively this message could only be included in runs with `-Verbose` parameter

**Comment by ThomasNieto** [comment]
I just ran into this and it should really return a non-terminating error for the caller to know something didn't work as expected.

Here is my example, by trying to uninstall a specific version of PSReadLine it gave me every indication that it worked as expected.

```powershell
PS C:\> Get-PSResource -Name PSReadLine

Name                                  Version  Prerelease Repository Description
----                                  -------  ---------- ---------- -----------
PSReadLine                            2.2.5.0             PSGallery  Great command line editing in the PowerShell console host
PSReadLine                            2.2.0    beta5      PSGallery  Great command line editing in the PowerShell console host

PS C:\> Uninstall-PSResource -Name PSReadLine -Version 2.2.0
PS C:\> Get-PSResource -Name PSReadLine

Name                                  Version  Prerelease Repository Description
----                                  -------  ---------- ---------- -----------
PSReadLine                            2.2.5.0             PSGallery  Great command line editing in the PowerShell console host
PSReadLine                            2.2.0    beta5      PSGallery  Great command line editing in the PowerShell console host

PS C:\> Uninstall-PSResource -Name PSReadLine -Version 2.2.0-beta5
PS C:\> Get-PSResource -Name PSReadLine

Name                                  Version  Prerelease Repository Description
----                                  -------  ---------- ---------- -----------
PSReadLine                            2.2.5.0             PSGallery  Great command line editing in the PowerShell console host
```

**Comment by alerickson** [comment]
Uninstall * should return nothing
Uninstall <pkgname> should return an error

**Comment by alerickson** [comment]
Not sure when this got resolved, but I believe we currently have the appropriate behavior.  
```powershell
PS C:\> Uninstall-PSResource notamodule
Uninstall-PSResource: Did not successfully uninstall package
```

I'll update the message here to actually reference the package name and version

**Comment by ThomasNieto** [comment]
@alerickson, when you're updating the error message it should say it failed because it does not exist. The current message just saying it failed for no reason is not helpful to the user on why it failed. See #942 for that specific issue.

If you need an example, use `Remove-Item` as that error message is explicit to the user.
