### ISSUE TITLE
Install-PSResource doesn't allow for a change in PSModulePath

### ISSUE THREAD

**Issue by russellds** [PowerShell/PSResourceGet#605]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Change PSModulePath using the directions in [about_PowerShell_Config PSModulePath](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-7.2#psmodulepath).

Create a `powershell.cofig.json` in `Split-Path $PROFILE` with the following:

``` JSON
{
    "PSModulePath": "C:\\PowerShell\Modules"
}
``` 
Execute: `Install-PSResource -Name KeepAlive`

### Expected behavior

```console
PowerShell module KeepAlive would be installed in C:\PowerShell\Modules.

A solution would be to allow for a PowerShellGet config file, similar to the about_PowerShell_Config, to
set the different paths for PowerShellGet. This would also solve #195 
```

### Actual behavior

```console
Module was installed in `Split-Path $PROFILE`.
```

### Error details

```console
No error returned.
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.12     beta       PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceR…

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by StevenBucher98** [comment]
Thanks for bringing this up @russellds we will look into fixing this.

**Comment by StevenBucher98** [comment]
@russellds Did Install-Module create the path `C:\PowerShell\Modules` or was that already created by you?

**Comment by russellds** [comment]
I created the folder. From browsing the code, it seems like any changes to the `$env:PSModulePath` are ignored, which makes sense because `$env:PSModulePath` doesn't identify user paths versus system paths. That is why I think a simple solution would be to have file similar to `powershell.config.json` as documented in [about_PowerShell_Config](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_config?view=powershell-7.2), something like `powershellget.config.json` where you could override the value of the user module path for PowerShellGet.

My use case is OneDrive / the Az module. The Az module is so large that it cause issues when trying to update or re-install it with OneDrive conflicts. Being able to override the user modules location would allow me to work around that as well as no longer having to replicate PowerShell modules to OneDrive.

**Comment by StevenBucher98** [comment]
@russellds I see, there is a way to do this with the `Save-PSResource` cmdlet. If you do `Save-PSResource -Name KeepAlive -IncludeXML -Path <Your path>` that should install that module in the designated path. Let us know if this covers your scenario! Thanks!

**Comment by russellds** [comment]
While a viable workaround, which I am currently using, how does that work with the other functions in PowerShellGet? Both updating and uninstalling a module will require manual tasks.

**Comment by vandre** [comment]
I'm not sure why this is marked as Fixed. 
I'm using PSResourceGet 1.0.1 and I created a powershell.config.json as described in the steps to reproduce and doing 
`Install-PSResource -Name KeepAlive` still installs the module to the User Documents folder.

@SydneyhSmith  @alerickson
