### ISSUE TITLE
Git Hub Nuget Packages

### ISSUE THREAD

**Issue by GamerClassN7** [PowerShell/PSResourceGet#608]
### Summary of the new feature / enhancement

Wil be ever possible to use github similar vay like Azure dev ops can be used like private PS repository ?

**Comment by StevenBucher98** [comment]
Thanks for this issue @GamerClassN7! Would you host your packages on GitHub and would you like to publish packages to the GitHub feed via git commands or PowerShellGet cmdlets? We would love to get any more details for the scenario you are thinking of! 

Also does not having this block any of your work flows?

**Comment by GamerClassN7** [comment]
Hello at my company ve use Azzure Dev Ops and Its Artefact to build Powershell Module and push it to company Repozitory , From where it can be installed on any pc wis simple Import-Module "package" after company repozitory nuget is registered.
To explain setup we wer setting it up this way: https://www.pipehow.tech/new-psrepository/ I would like to use Git hube nuget packages simillar way how ever it it not possible in current state since index.json post only one of required url: that with "@type": "PackagePublish/2.0.0" and not the second one required :( "LegacyGallery/2.0.0" whit is requiret to it to work with powershell module system. Hoewer i thing so many eople would love to have this oprion to use Github nuget for PS :) i hope my terrible neglish make at least some sence to you my repo where i am testing the idea is here: https://github.com/GamerClassN7/Povershell-IT3C-Module/ 
![image](https://user-images.githubusercontent.com/22167469/153558324-9299f165-7c43-43d6-bf8c-774243873062.png)
best regards

**Comment by StevenBucher98** [comment]
We definitely want to support this scenario and will keep track of this new feature! Thanks @GamerClassN7

**Comment by alerickson** [comment]
This will be resolved with PR #1167
