### ISSUE TITLE
Why does Publish error handling check for a magic NugetApiKey?

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSResourceGet#61]
In the error handling for `Publish-PSArtifactUtility` there is [a test for `$NugetApiKey -eq 'VSTS'`](https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/PSModule.psm1#L8492) which is driving me crazy.  

Under what circumstances does that actually come up? Doesn't it require that users know to use "VSTS" as a magical API key, but _not know **why**_ they should do so?  I mean, if they knew what they were doing it, they would not get this error, right? So it seems this only happens if they _coincidentally_ guess at the APIKey.

### I appreciate the attempt, and **the error message is _very useful_**.

Perhaps you could _just_ be match the `$errorMsg`? Or even just test for "visualstudio.com" in the URL instead? 

One final thought: could that error message (and/or the web url) be updated to include instructions for registering the URL from the command line?

**Comment by SydneyhSmith** [comment]
Closing as resolved since changing the publishing APIs
