### ISSUE TITLE
Local cache for command/module lookup

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PSResourceGet#613]
### Summary of the new feature / enhancement

As per the [RFC ](https://github.com/PowerShell/PowerShell-RFC/pull/237/files#diff-3543dd227ba0e5d6aa1adb426c03d460807134ca378489b072e91e5c4dda2845R342-R379) there is mention of a local cache.

I could not find this already listed in issues so raising so that this is tracked

**Comment by StevenBucher98** [comment]
Hi @kilasuit the local cache feature is listed in the Alternative Proposals and Considerations and are items outside of the scope of the 3.0 initial release. It is something we are still very interested in including in PowerShellGet but it will likely have to be once 3.0 is released.
