### ISSUE TITLE
Missing NuGetApiKey should not throw exceptions on Publish-Module

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSResourceGet#62]
The NuGetApiKey is not **marked** mandatory on Publish-Module.

In point of fact, there are NuGet repositories, like the Visual Studio Online package repositories, which require credentials _rather than_ API keys, so this error (with id "NuGetApiKeyIsRequiredForNuGetBasedGalleryService") is technically incorrect anyway.

You should just try the publish and provide proper errors _when and if_ the authentication fails.

**Comment by SydneyhSmith** [comment]
This is resolved as of 3.0-beta8
