### ISSUE TITLE
Switch for Install-PSResource and Update-PSResource to not install module dependencies

### ISSUE THREAD

**Issue by o-l-a-v** [PowerShell/PSResourceGet#620]
### Summary of the new feature / enhancement

Some modules have hardcoded dependencies on old versions of other modules, which PowerShellGet happily installs at the same time.

### Proposed technical implementation details (optional)

Implement an optional switch for ignoring installing module dependencies would be great, I want to handle what versions of Az.Accounts (for instance) I have installed myself.

**Comment by alerickson** [comment]
Hi @o-l-a-v, we now have the `-SkipDependencyCheck` for both `Install-PSResource` and `Update-PSResource`.  I'm going to close this issue since we have those flags implemented but feel free to open up a new issue if there are any bugs or other features you'd like to see here.  Thanks!
