### ISSUE TITLE
Install-Module -Name Az is really slow

### ISSUE THREAD

**Issue by luisnaranjo733** [PowerShell/PSResourceGet#623]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Install the latest version of Powershell 7
```powershell
 $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      2
```

Attempt to install the Az Powershell module per the [recommended method according to the documentation](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-7.3.2)

```powershell
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force
```

### Expected behavior

```console
Install-Module completes or at least posts progress updates
```

### Actual behavior

```console
Operation hangs indefinitely - never completes

See https://github.com/Azure/azure-powershell/issues/17210
for more details on the same exact issue
```

### Error details

```console
N/A
```

### Environment data

```powershell
PS C:\code> Get-Module PowerShellGet; $PSVersionTable

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Fin…

Key   : PSVersion
Value : 7.2.2
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.2.2
Name  : GitCommitId


Key   : OS
Value : Microsoft Windows 10.0.22000
Name  : OS


Key   : Platform
Value : Win32NT
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

**Comment by luisnaranjo733** [comment]
Update: I renamed the title of this issue because the operation did finally complete. It took ~8-10 minutes and the powershell command didn't report any indication of progress starting until ~5 min after the process was started.

From the user's POV, it feels like the script is just hanging.

**Comment by SydneyhSmith** [comment]
@luisnaranjo733 appreciate the feedback and totally understand the frustration--- we are doing work in both this module and in PowerShell Gallery to improve this performance over time...right now we are tracking this work with a few issues including #69 #599 and #31 .., with Install-PSResource we have also implemented a progress bar to show the progress

**Comment by HenryGelderbloem** [comment]
I am experiencing this issue today, it has been in a hung state for roughly 10 minutes so far.
