### ISSUE TITLE
`Uninstall-PSResource` should take `Version` from `ValueFromPipelineByPropertyName`

### ISSUE THREAD

**Issue by SeeminglyScience** [PowerShell/PSResourceGet#626]
### Summary of the new feature / enhancement

As a user I want to be able to pipe `Get-InstalledPSResource SomeModule` to `Uninstall-PSResource`.

Currently if you try to pipe a single version to `Unisntall-PSResource` it will try to uninstall all of them:

![image](https://user-images.githubusercontent.com/24977523/161619009-91c1aea1-7918-4a32-b10e-4337f4c159f9.png)

Using `Uninstall-PSResource -Name SomeModule -Version 2.0.0` works, but should be pipeable ideally.

**Comment by SydneyhSmith** [comment]
Thanks @SeeminglyScience looks like this is an issue we thought we addressed in preview 11 but is still an issue

**Comment by alerickson** [comment]
Resolved in https://github.com/PowerShell/PowerShellGet/pull/593
