### ISSUE TITLE
PowerShell Gallery: `Publish-Script`/`Module` warnings

### ISSUE THREAD

**Issue by iRon7** [PowerShell/PSResourceGet#638]
### Steps to reproduce

Both `Publish-Script` and `Publish-Module` produce (confusing) warnings (in `-verbose` mode?)

```PowerShell
Publish-Script -Path .\MyScript.ps1 -NuGetApiKey xxxxxxxxxxxxxxxxxxxxxxxxx -Verbose
```

At first I thought I needed to update my  **ScriptInfo** header and/or **`.psd1 Module Manifest** file, but it appears that it concerns PowerShell Gallery script that needs to translate the concerned Uri's to the GitHub.

### Expected behavior

No warnings

### Actual behavior

Several warnings

`Publish-Script` has also two additional warnings:
```Console
WARNING: NU5110: The script file 'Join.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package. Move it into the 'tools' folder.
WARNING: NU5111: The script file 'Join.ps1' is not recognized by NuGet and hence will not be executed during installation of this package. Rename it to install.ps1, uninstall.ps1 or init.ps1 and place it directly under 'tools'.
```

### Error details

```console
WARNING: NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
WARNING: NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/8080834/166477448-49618251-8c35-48e3-863c-25df24a0bb4a.png">

**Comment by daxian-dbw** [comment]
This is a PowerShellGet specific issue, so transfer it to the right repo.

**Comment by alerickson** [comment]
Hi @iRon7 unfortunately we can't do much about these changes in lower versions of PowerShellGet, particularly because these warnings are coming from the NuGet executable that's used to publish.  However, we've made some upgrades in PowerShellGet v3, so if you'd like to try our latest beta and let us know how that works for you, we'd love to get some of your feedback!  You can install the latest version here: https://www.powershellgallery.com/packages/PowerShellGet/3.0.14-beta14

**Comment by iRon7** [comment]
Thanks for your response.
I will try the new version as soon as I have something to upload.
