### ISSUE TITLE
Unable to install PowerShell module on AWS EC2 Windows 2019 Server

### ISSUE THREAD

**Issue by arniek93** [PowerShell/PSResourceGet#646]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I am experiencing a problem installing the PowerShell module on the Windows 2019 server. The server is a cloud server hosted on an AWS Ec2 instance. I have followed all the online resources to debug the issue, and I have enabled the tls12 on the server. But still, I am facing a problem with installing any of the modules.

### Expected behavior

```console
Install the PowerShell module successfully without any error.
```

### Actual behavior

```console
Getting the PackageManagement error as well as the source warning.
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' is not valid.
PackageManagement\Install-Package : Package 'PackageManagement' failed to download.
```

### Error details

```console
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' is not valid.
PackageManagement\Install-Package : Package 'PackageManagement' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\SA-JX2...anagement.nupkg:String) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage

WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' is not valid.
PackageManagement\Install-Package : Package 'PackageManagement' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\SA-JX2...anagement.nupkg:String) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage

WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/Az.Accounts/2.7.6' is not valid.
PackageManagement\Install-Package : Package 'Az.Accounts' failed to download.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\SA-JX2....Accounts.nupkg:String) [Install-Package], Excep
   tion
    + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPac
   kage
```

### Environment data

```powershell
Install-Module -Name PowerShellGet -Force
>> Install-Module PackageManagement -Force -Repository PSGallery
>> Install-Module -Name Az -Repository PSGallery -Force
```

### Visuals

![PowerShell Issue](https://user-images.githubusercontent.com/105807249/169090619-25cf09dc-0f96-4a14-bccf-8851c43140ef.JPG)

**Comment by SydneyhSmith** [comment]
Thanks @arniek93 for opening this issue! Could you please also provide the call with `-Verbose -Debug` switches enabled so we can get greater detail...thanks!

**Comment by arniek93** [comment]
Here is the Verbose for the command Install-Module PowerShellGet

  Install-Module -Name PowerShellGet -Force -Verbose -Debug
DEBUG: 00:00:00.0001347 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): Y
DEBUG: 00:00:00.0000358 Trying provider assembly: C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): Y
DEBUG: 00:00:00.0000001 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:00.0000937 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.0000112 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.0000990 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0034072 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.0035313 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0036402 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0036941 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0039375 Attempting loading of assembly: C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0041438 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.0076150 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.0077469 Acquiring providers for assemblyC:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0078331 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0078797 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0079237 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.0080748 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0545148 Registering providers via metaproviders for assembly
Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.PowerShellMetaProvider
DEBUG: 00:00:00.1109661 Initializing provider 'msu'
DEBUG: 00:00:00.1111976 Initializing provider 'msi'
DEBUG: 00:00:00.1112138 Initializing provider 'Bootstrap'
DEBUG: 00:00:00.1112248 Initializing provider 'Programs'
DEBUG: 00:00:00.1120495 Initializing provider 'NuGet'
DEBUG: 00:00:00.1125060 Initializing provider 'zipfile'
DEBUG: 00:00:00.1125958 Initializing provider 'WebDownloader'
DEBUG: 00:00:00.1165684 Trying to register metaprovider
DEBUG: 00:00:00.1416229 Provider 'WebDownloader' Initialized
DEBUG: 00:00:00.1416617 Using Downloader Provider WebDownloader
DEBUG: 00:00:00.1441176 Provider 'zipfile' Initialized
DEBUG: 00:00:00.1441470 Using Archiver Provider zipfile
DEBUG: 00:00:00.1449250 Initialize Bootstrapper
DEBUG: 00:00:00.1452403 Provider 'Bootstrap' Initialized
DEBUG: 00:00:00.1452811 Using Package Provider Bootstrap
DEBUG: 00:00:00.1507844 Calling 'NuGet'::'InitializeProvider'.
DEBUG: 00:00:00.1508315 Provider 'NuGet' Initialized
DEBUG: 00:00:00.1508731 Using Package Provider NuGet
DEBUG: 00:00:00.1545595 Calling 'Programs::InitializeProvider'
DEBUG: 00:00:00.1546256 Provider 'Programs' Initialized
DEBUG: 00:00:00.1546276 Calling 'msi::InitializeProvider'
DEBUG: 00:00:00.1546594 Using Package Provider Programs
DEBUG: 00:00:00.1546682 Provider 'msi' Initialized
DEBUG: 00:00:00.1546973 Using Package Provider msi
DEBUG: 00:00:00.1590380 Calling 'zipfile::GetFeatures'
DEBUG: 00:00:00.1592228 Calling 'msi::GetFeatures'
DEBUG: 00:00:00.1592235 Calling 'NuGet'::'GetFeatures'.
DEBUG: 00:00:00.1593759 Calling 'Programs::GetFeatures'
DEBUG: 00:00:00.1606516 The provider 'Programs' is imported
DEBUG: 00:00:00.1615172 The provider 'msi' is imported
DEBUG: 00:00:00.1616458 Calling 'msu::InitializeProvider'
DEBUG: 00:00:00.1617119 Provider 'msu' Initialized
DEBUG: 00:00:00.1617317 Using Package Provider msu
DEBUG: 00:00:00.1618270 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.1618644 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.1622644 The provider 'NuGet' is imported
DEBUG: 00:00:00.1624279 Initializing PowerShell MetaProvider
DEBUG: 00:00:00.1637062 SUCCESS provider assembly: C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.1661471 Calling 'msu::GetFeatures'
DEBUG: 00:00:00.1664247 The provider 'msu' is imported
DEBUG: 00:00:00.1664258 Calling 'WebDownloader::GetFeatures'
DEBUG: 00:00:00.1667276 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.1704304 Calling 'Bootstrap::GetFeatures'
DEBUG: 00:00:00.1715271 The provider 'Bootstrap' is imported
DEBUG: 00:00:00.1718463 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.1853615 Calling 'WebDownloader::DownloadFile'
'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409','C:\Users\<userID>\AppData\Local\Temp\Microsoft.P
ackageManagement\dq1bp3sw.iyr','40000','False'
DEBUG: 00:00:00.2166333 Attempting to load PowerShell Provider Module [C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1]
DEBUG: 00:00:00.3546382 Loaded PowerShell package provider: '[C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1]'.
DEBUG: 00:00:00.3641415 Loaded PowerShell Provider: PowerShellGet
DEBUG: 00:00:00.3669774 Initializing provider 'PowerShellGet'
DEBUG: 00:00:00.3767796 Calling New() : MethodName = 'InitializeProvider'
DEBUG: 00:00:00.3768193 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.3768327 WarningAction: SilentlyContinue
DEBUG: 00:00:00.3829397 INVOKING PowerShell Fn Initialize-Provider with args  that has length 0
DEBUG: 00:00:00.4082612 In PowerShellGet Provider - 'Initialize-Provider'.
DEBUG: 00:00:00.4085764 PowerShell Script 'PSModule' Function 'Initialize-Provider' returns null.
DEBUG: 00:00:00.4099649 Done calling powershell «Initialize-Provider» «PSModule»
DEBUG: 00:00:00.4100227 Provider 'PowerShellGet' Initialized
DEBUG: 00:00:00.4100393 Using Package Provider PowerShellGet
DEBUG: 00:00:00.4177339 Calling New() : MethodName = 'GetFeatures'
DEBUG: 00:00:00.4177755 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.4177931 WarningAction: SilentlyContinue
DEBUG: 00:00:00.4185273 INVOKING PowerShell Fn Get-Feature with args  that has length 0
DEBUG: 00:00:00.4302826 In PowerShellGet Provider - 'Get-Feature'.
DEBUG: 00:00:00.4419973 Done calling powershell «Get-Feature» «PSModule»
DEBUG: 00:00:00.4420808 The provider 'PowerShellGet' is imported
DEBUG: 00:00:00.4436914 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00 Calling New() : MethodName = 'GetDynamicOptions'

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:00.0002975 Force: True
DEBUG: 00:00:00.0003318 Verbose: True
DEBUG: 00:00:00.0003490 Debug: True
DEBUG: 00:00:00.0003641 Name: PowerShellGet
DEBUG: 00:00:00.0012452 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0166787 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0360636 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0407149 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0407379 Force: True
DEBUG: 00:00:00.0407529 Verbose: True
DEBUG: 00:00:00.0407668 Debug: True
DEBUG: 00:00:00.0407804 Name: PowerShellGet
DEBUG: 00:00:00.0413830 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0420381 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0441665 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0730305 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0730768 Force: True
DEBUG: 00:00:00.0730949 Verbose: True
DEBUG: 00:00:00.0731095 Debug: True
DEBUG: 00:00:00.0731220 Name: PowerShellGet
DEBUG: 00:00:00.0739557 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0747046 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0841884 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0877516 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0877751 Force: True
DEBUG: 00:00:00.0877899 Verbose: True
DEBUG: 00:00:00.0878037 Debug: True
DEBUG: 00:00:00.0878176 Name: PowerShellGet
DEBUG: 00:00:00.0883905 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0889959 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0920913 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:06.9951009 Calling SearchForPackages. Name='PowerShellGet'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:07.0091756 PackageProvider::FindPackage with name PowerShellGet
DEBUG: 00:00:07.0098829 Calling SearchForPackages After Select 1
DEBUG: 00:00:07.0528563 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:07.0548899 ProviderName: PowerShellGet
DEBUG: 00:00:07.0563635 Type: Module
DEBUG: 00:00:07.0578788 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:07.0594850 Force: True
DEBUG: 00:00:07.0608880 Debug: True
DEBUG: 00:00:07.0622019 Scope: AllUsers
DEBUG: 00:00:07.0636818 Verbose: True
DEBUG: 00:00:07.0649785 Name: PowerShellGet
DEBUG: 00:00:07.0665500 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:07.1401840 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:07.1976919 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:07.1995300 OPTION: Type => Module
DEBUG: 00:00:07.2010660 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:07.2026253 OPTION: Force => True
DEBUG: 00:00:07.2040033 OPTION: Debug => True
DEBUG: 00:00:07.2053551 OPTION: Scope => AllUsers
DEBUG: 00:00:07.2068703 OPTION: Verbose => True
DEBUG: 00:00:07.2109378 OPTION: Name => PowerShellGet
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
DEBUG: 00:00:07.3093969 PackageProvider::FindPackage with name PowerShellGet
DEBUG: 00:00:07.3561205 Calling 'NuGet'::'FindPackage' - name='PowerShellGet', requiredVersion='',minimumVersion='',
maximumVersion='''.
DEBUG: 00:00:07.3605361 Iterating 'PowerShellGet'.
DEBUG: 00:00:07.3816325 Calling 'NuGetRequest'::'RegisteredPackageSources',
'C:\Users\<userID>\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:07.3841520 Loading a configuration from file
'C:\Users\<userID>\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:07.3864822 Loaded a configuration from file
'C:\Users\<userID>\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:07.3922566 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:07.3963395 Calling 'NuGetRequest'::'GetPackageById', 'PowerShellGet'.
DEBUG: 00:00:07.4889102 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'PowerShellGet'.
DEBUG: 00:00:07.4909662 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
DEBUG: 00:00:07.5041891 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:07.5486632 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:07.5851375 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=40&$top=40'.
DEBUG: 00:00:07.5854410 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=160&$top=40'.
DEBUG: 00:00:07.5855950 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=120&$top=40'.
DEBUG: 00:00:07.5893022 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=80&$top=40'.
DEBUG: 00:00:07.5967536 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=40&$top=40'.
DEBUG: 00:00:07.6006493 '29' packages received in the last request.
DEBUG: 00:00:07.6031361 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=80&$top=40'.
DEBUG: 00:00:07.6054027 '0' packages received in the last request.
DEBUG: 00:00:07.6101103 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=160&$top=40'.
DEBUG: 00:00:07.6125486 '0' packages received in the last request.
DEBUG: 00:00:07.6126932 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=120&$top=40'.
DEBUG: 00:00:07.6163247 '0' packages received in the last request.
VERBOSE: Total package yield:'1' for the specified package 'PowerShellGet'.
DEBUG: 00:00:07.6199652 Completed iterating for 'PowerShellGet'.
DEBUG: 00:00:07.8581169 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:07.8885322 Calling New() : MethodName = 'GetInstalledPackages'
DEBUG: 00:00:07.8903732 ProviderName: PowerShellGet
DEBUG: 00:00:07.8917832 Type: Module
DEBUG: 00:00:07.8931072 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:07.8944923 Force: True
DEBUG: 00:00:07.8958780 Debug: True
DEBUG: 00:00:07.8971716 Scope: AllUsers
DEBUG: 00:00:07.8987930 Verbose: True
DEBUG: 00:00:07.9033964 Name: PowerShellGet
DEBUG: 00:00:07.9048671 INVOKING PowerShell Fn Get-InstalledPackage with args PowerShellGet, 2.2.5, ,  that has length
4
DEBUG: 00:00:07.9170774 In PowerShellGet Provider - 'Get-InstalledPackage'.
DEBUG: 00:00:07.9184828 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:07.9199431 OPTION: Type => Module
DEBUG: 00:00:07.9213983 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:07.9229034 OPTION: Force => True
DEBUG: 00:00:07.9244702 OPTION: Debug => True
DEBUG: 00:00:07.9259470 OPTION: Scope => AllUsers
DEBUG: 00:00:07.9274421 OPTION: Verbose => True
DEBUG: 00:00:07.9290933 OPTION: Name => PowerShellGet
DEBUG: 00:00:09.0036733 PowerShell Script 'PSModule' Function 'Get-InstalledPackage' returns null.
DEBUG: 00:00:09.0132047 Done calling powershell «Get-InstalledPackage» «PSModule»

Confirm
Are you sure you want to perform this action?
Performing the operation "Install-Module" on target "Version '2.2.5' of module 'PowerShellGet'".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 00:00:11.2520721 Calling New() : MethodName = 'InstallPackage'
DEBUG: 00:00:11.2545246 ProviderName: PowerShellGet
DEBUG: 00:00:11.2558381 Type: Module
DEBUG: 00:00:11.2571081 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:11.2584911 Force: True
DEBUG: 00:00:11.2598703 Debug: True
DEBUG: 00:00:11.2612273 Scope: AllUsers
DEBUG: 00:00:11.2625359 Verbose: True
DEBUG: 00:00:11.2668242 Name: PowerShellGet
DEBUG: 00:00:11.2684236 INVOKING PowerShell Fn Install-Package with args
NuGet|PowerShellGet|2.2.5|https://www.powershellgallery.com/api/v2|Module that has length 1
DEBUG: 00:00:11.2777899 In PowerShellGet Provider - 'Install-Package'.
DEBUG: 00:00:11.3198734 In PowerShellGet Provider - 'Install-PackageUtility'.
DEBUG: 00:00:11.3225255 The FastPackageReference is
'NuGet|PowerShellGet|2.2.5|https://www.powershellgallery.com/api/v2|Module'.
DEBUG: 00:00:11.3296429 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:11.3311009 OPTION: Type => Module
DEBUG: 00:00:11.3325866 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:11.3343446 OPTION: Force => True
DEBUG: 00:00:11.3358481 OPTION: Debug => True
DEBUG: 00:00:11.3374110 OPTION: Scope => AllUsers
DEBUG: 00:00:11.3389410 OPTION: Verbose => True
DEBUG: 00:00:11.3430529 OPTION: Name => PowerShellGet
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
DEBUG: 00:00:11.3599208 ArtifactType is Module
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'PowerShellGet' with version '2.2.5' from the repository
'https://www.powershellgallery.com/api/v2'.
DEBUG: 00:00:11.4549598 Calling 'NuGet'::'InstallPackage',
'$UFNOdUdldA==\UG93ZXJTaGVsbEdldA==\Mi4yLjU=\aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\cG93ZXJzaGVsbGdld
A=='.
DEBUG: 00:00:11.4574614 Calling 'NuGetRequest'::'GetPackageByFastpath',
'$UFNOdUdldA==\UG93ZXJTaGVsbEdldA==\Mi4yLjU=\aHR0cHM6Ly93d3cucG93ZXJzaGVsbGdhbGxlcnkuY29tL2FwaS92Mg==\cG93ZXJzaGVsbGdld
A=='.
DEBUG: 00:00:11.4622876 Calling 'NuGetRequest'::'ResolvePackageSource', 'PSNuGet'.
DEBUG: 00:00:11.4665019 Calling 'NuGetRequest'::'FindRegisteredSource', 'PSNuGet'.
DEBUG: 00:00:11.4680645 Source 'PSNuGet' is one of the registered sources in 'NuGet' provider.
DEBUG: 00:00:11.4700246 Calling 'HttpClientPackageRepository'::'FindPackage', 'PowerShellGet'.
DEBUG: 00:00:11.4716883 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
DEBUG: 00:00:11.4757469 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:11.5245002 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&$skip=0&$top=40'.
DEBUG: 00:00:11.5327351 'Package version' is '2.2.5'.
DEBUG: 00:00:11.5346039 'Request's Destination' is 'C:\Users\<userID>\AppData\Local\Temp\42214340'.
DEBUG: 00:00:11.5443055 Calling 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:11.5573307 There are '1' registered sources in 'NuGet' provider.
DEBUG: 00:00:11.5592068 Calling 'NuGetRequest'::'GetPackageById', 'PackageManagement'.
DEBUG: 00:00:11.5606941 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'PackageManagement'.
DEBUG: 00:00:11.5622921 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'' for
''.
DEBUG: 00:00:11.5658225 Downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'&$skip=0&$top=40'.
DEBUG: 00:00:11.5774812 Completed downloading
'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'&$skip=0&$top=40'.
DEBUG: 00:00:11.5802362 '25' packages received in the last request.
DEBUG: 00:00:11.5856419 Returning the call 'NuGetClient'::'GetPackageDependencies'.
DEBUG: 00:00:11.6435326 Calling 'NuGetClient'::'InstallPackage'.
VERBOSE: InstallPackage' - name='PackageManagement',
version='1.4.7',destination='C:\Users\<userID>\AppData\Local\Temp\42214340'
VERBOSE: DownloadPackage' - name='PackageManagement',
version='1.4.7',destination='C:\Users\<userID>\AppData\Local\Temp\42214340\PackageManagement\PackageManagement
.nupkg', uri='https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7'.
VERBOSE: An error occurred while sending the request.
DEBUG: 00:00:55.1357026    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__15.MoveNext()
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' for '2' more
times
VERBOSE: An error occurred while sending the request.
DEBUG: 00:01:48.4135977    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__15.MoveNext()
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' for '1' more
times
VERBOSE: An error occurred while sending the request.
DEBUG: 00:02:26.4090018    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__15.MoveNext()
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' for '0' more
times
VERBOSE: Downloading package 'PackageManagement' failed, please make sure
'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' is accessable.
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PackageManagement/1.4.7' is not valid.

**Comment by arniek93** [comment]
Issue has been resolved internally
