### ISSUE TITLE
PSResourceRepository -CredentialInfo should support all SM secret types

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#652]
### Summary of the new feature / enhancement

PSResourceRepository -CredentialInfo should support all SM secret types so that a PSCredential Object is not required. 
PowerShell SecretManagement supports the following secret data types:

- byte[]
- string
- SecureString
- PSCredential
- Hashtable

**Comment by alerickson** [comment]
Only implement:
string
