### ISSUE TITLE
Performance improvements for find/install

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#653]
### Summary of the new feature / enhancement

Based on the investigation in issue PowerShell/PowerShellGet#641 we have come to the following ideas:
- Fix IEnumerable issues  PowerShell/PowerShellGet#654 
- Refactor Find to use IRepositorySearch (with current nuget APIs) PowerShell/PowerShellGet#655
- (optionally) Look at IDownloadPackage refactor
- Use Find local cache PowerShell/PowerShellGet#613 
- Look at new implementations using HTTPClient

**Comment by JustinGrote** [comment]
@SydneyhSmith https://github.com/PowerShell/PowerShellGallery/issues/241 might be related at least for powershell gallery "Az*" searches.

**Comment by JustinGrote** [comment]
Even though I implemented it in native powershell, you may want to look at how I used a native httpclient to speed up installs of the Az module from 2 minutes to 5 seconds :).

The same logic can easily apply to C# and can be much faster if the awaitable tasks are chained together (which I can't really feasibly do in PowerShell)

https://github.com/JustinGrote/ModuleFast/blob/main/ModuleFast.ps1

**Comment by alerickson** [comment]
closing this in favor of #655
