### ISSUE TITLE
Find-PSResource does not accept pipeline input

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#666]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I should be able to take the output from `Get-PSResource` and pipe that to `Find-PSResource in order to find out what versions are on the repository.

```powershell
Get-PSResource operationvalidation | Find-PSResource
```

This is can be resolved by adding `ValueFromPipelineByPropertyName` to `Name` and `Repository` parameters.

### Expected behavior

```console
Get-PSResource operationvalidation | Find-PSResource

Name                Version Prerelease Repository Description
----                ------- ---------- ---------- -----------
OperationValidation 1.2.1.0            PSGallery  A set of tools for executing validation of the operation of a system. It provides a way to organize and ex…
```

### Actual behavior

```console
No resources are returned
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.12     beta       PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceRepository, Install-PSResource…}

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
Thanks @ThomasNieto for this feedback...for this scenario are you hoping just the name gets passed into the find call (in this case to see all verisions available), or are you hoping that the version of the installed module gets used as well? I'd love to just better understand the purpose of the original get call vs directly piping the name?

**Comment by ThomasNieto** [comment]
In my use case would be to get the list of installed resources and then find the latest version available on the repo as such I wouldn't need the version passed as well.
