### ISSUE TITLE
PSResourceInfo version property not correct for 2 or 3 digit version numbers.

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#697]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

If a resource is defined with a 2 digit (`1.2`) or 3 digit (`9.0.0`) version number then the `Version` property will incorrectly have `0` for either `Build` or `Revision` properties instead of `-1`.

### Expected behavior

```console
PS C:\> Find-PSResource -Name TabExpansionPlusPlus

Name                 Version Prerelease Repository Description
----                 ------- ---------- ---------- -----------
TabExpansionPlusPlus 1.2            PSGallery  TabExpansionPlusPlus extends the tab expansion and Intellisense features of…

PS C:\> Find-PSResource -Name NetworkingDsc

Name          Version Prerelease Repository Description
----          ------- ---------- ---------- -----------
NetworkingDsc 9.0.0            PSGallery  DSC resources for configuring settings related to networking.
```

### Actual behavior

```console
PS C:\> Find-PSResource -Name TabExpansionPlusPlus

Name                 Version Prerelease Repository Description
----                 ------- ---------- ---------- -----------
TabExpansionPlusPlus 1.2.0.0            PSGallery  TabExpansionPlusPlus extends the tab expansion and Intellisense features of…

PS C:\> Find-PSResource -Name NetworkingDsc

Name          Version Prerelease Repository Description
----          ------- ---------- ---------- -----------
NetworkingDsc 9.0.0.0            PSGallery  DSC resources for configuring settings related to networking.
```

### Error details

```console
N/A
```

### Environment data

```powershell
Name          Version
----          -------
PowerShellGet 3.0.14

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by denisky** [comment]
I experienced the same behavior.

For my use case I'm trying to install required modules in order to publish a new module.

- Module A
  - Version: 1.0.0
- Module B
  - Version 1.0.0
  - Required Modules
    - Module A
      - Version: 1.0.0

When I try to find the required module A it returns the version 1.0.0.0 which doesn't match the version defined in the module manifest.

**Comment by SydneyhSmith** [comment]
This issue is not reproducing for me with beta20 so I am going to mark it as resolved.

**Comment by ThomasNieto** [comment]
@SydneyhSmith beta20 isn't published for me to validate. When will that be published to the gallery?
