### ISSUE TITLE
Install-RequiredModule to support RequiredModules.psd1

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PSResourceGet#70]
Can I send a PR for a `Install-RequiredModule` command that handles the syntax suggested by PowerShell/PowerShell-RFC/pull/185 ...

Specifically:
- a `RequiredModulesFile` parameter defaulted to `RequiredModules.psd1`
- support installing a group of modules listed in said file
- supporting NuGet version (range) syntax 
- supporting specifying feed urls per resource
- with the option to install (save) locally (to folder) or to scope

If I did, would it be a problem if it required the Nuget.Versioning assembly (to guarantee the version range parsing is the same)?

**Comment by SydneyhSmith** [comment]
Closing as this is resolved by additional file options for Install-PSResource
