### ISSUE TITLE
PowerShellGet should move off of the nuget APIs

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#746]
### Summary of the new feature / enhancement

We hit a number of issues because of our reliance on the nuget APIs, instead we should make our own calls directly

**Comment by et1975** [comment]
This seems like pretty massive change and I see not discussion or details about it. Is there something we can look at to understand what's happening?
Are we talking about only the client code or the WebAPI/protocol of the feed?

**Comment by anamnavi** [comment]
@et1975 this is still a work in progress, but you can see the changes on this branch in our repo: https://github.com/PowerShell/PowerShellGet/tree/interface. 

The changes are for the client side NuGet APIs, and will not affect the WebAPI/protocol of the feed or the server side APIs.

**Comment by alerickson** [comment]
Adding issue #755 which will be resolved by moving off the NuGet APIs.

**Comment by alerickson** [comment]
Adding issue #754 which will be resolved by moving off NuGet APIs
