### ISSUE TITLE
`Update-PSResource *` seems stuck in nuget repo

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSResourceGet#747]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
update-psresource * -verbose
```

### Expected behavior

```console
Expect all installed resources to try to get updated
```

### Actual behavior

```console
When it hits the nuget repo, it repeats and doesn't seem to end:


VERBOSE: No packages found in repository: NuGet.


Seems like we should have some progress written during discovery and actual updating
```

### Error details

```console
N/A
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.16     beta16     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceRepository, Install-PSResource…}

Name                           Value
----                           -----
PSVersion                      7.3.0-preview.6
PSEdition                      Core
GitCommitId                    7.3.0-preview.6
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
Currently the Name parameter defaults to * we need to decide if this is the correct behaviour

**Comment by SteveL-MSFT** [comment]
From team discussion, part of the problem is `Update-PSResource *` may update to newer versions that the user doesn't want.  For example, if the user is on 1.0.1, they may only want to update to 1.0.x or optionally to 1.x.y.  This assumes semver is being respected.   So we need to think through more of the bulk update scenario on both what the user can control and what the defaults should be (I would suggest the safest updates by default so only to newest patch version and not even newer minor version).  For the 3.0 release, it may make sense to not allow wildcards so that we can have more time to design for 3.1

**Comment by alerickson** [comment]
For 3.0 we will remove wildcard support for `Update-PSResource`.  We still need to figure out if there's a hang with the nuget (or any) repo.

**Comment by alerickson** [comment]
Original issue no longer repros in 3.0.21-beta21.  Opened up issue #1126 to track the rest of the discussion in this thread.
