### ISSUE TITLE
Cmdlet implementation is inconsistent regarding Path parameters. Make all cmdlets use Path.

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#753]
### Summary of the new feature / enhancement

Cmdlet implementation is inconsistent regarding Path parameters. Make all cmdlets use Path.
•	The following cmdlets use -Path
o	Get-PSResource
o	Publish-PSResource
o	Save-PSResource
o	Update-ModuleManifest
The following cmdlets use -FilePath
o	New-PSScriptFileInfo
o	Test-PSScriptFileInfo
o	Update-PSScriptFileInfo

**Comment by alerickson** [comment]
Check that parameters for -Path and -FilePath are correct (not necessarily, consistent, just correct)

Script to check:
gcm -mod powershellget | % { gcm $_.Name -syn }

**Comment by alerickson** [comment]
Consider adding `-Path` as an alias

**Comment by alerickson** [comment]
This is resolved now.
