### ISSUE TITLE
Find-PSResource: Search with wildcard returns duplicate results

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#755]
### Summary of the new feature / enhancement

Search using wildcards returns duplicate results

PS> Find-PSResource Microsoft.PowerShell.WhatsNew -Repository PSG*

Name                          Version Prerelease Repository       Description
----                          ------- ---------- ----------       -----------
Microsoft.PowerShell.WhatsNew 0.4.0.0            PSGallery        The Get-WhatsNew cmdlet allows you to see What's New…
Microsoft.PowerShell.WhatsNew 0.4.0.0            PSGalleryScripts The Get-WhatsNew cmdlet allows you to see What's New…

**Comment by ThomasNieto** [comment]
Why does PSGalleryScripts still exist? I know it was there for PSGet v2 when the initial requirement had scripts and modules in separate repos but that has been long since gone. Can we just migrate the existing script resources into the module repo and remove scripts repo logic all together?

**Comment by SydneyhSmith** [comment]
This is not reproducing for me with beta20
