### ISSUE TITLE
Save-PSResource -AsNupkg -IncludeXML does not include XML file

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#757]
### Summary of the new feature / enhancement

Save-PSResource -AsNupkg -IncludeXML does not include XML file

**Comment by adityapatwardhan** [comment]
@SydneyhSmith Is the expectation to have the XML file next to the saved nupkg? 

I believe the correct fix would be to not allow `-AsNupkg` and `-IncludeXml` on the same parameter set.
