### ISSUE TITLE
Update-ModuleManifest -PassThru parameter does nothing 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#758]
### Summary of the new feature / enhancement

Update-ModuleManifest -PassThru parameter does nothing

**Comment by SydneyhSmith** [comment]
In v2 this returns a string of the contents of the file

**Comment by SydneyhSmith** [comment]
It would be nice if we could return a parsed object rather than a string of the contents of the file

**Comment by alerickson** [comment]
For `Update-ModuleManifest` remove -PassThru parameter
