### ISSUE TITLE
For the *-PSScriptFileInfo cmdlets, remove the .PRIVATEDATA 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#759]
### Summary of the new feature / enhancement

For the *-PSScriptFileInfo cmdlets, remove the .PRIVATEDATA  as it does not appear to be used

**Comment by kilasuit** [comment]
I wouldn't remove this as it can be used for additional metadata, which whilst not the norm in shared scripts/modules can be of great use in internal ones.

**Comment by ThomasNieto** [comment]
PrivateData can be used by script authors and as such cannot be removed.

**Comment by SydneyhSmith** [comment]
Thanks, we will not remove it...any examples you may have of privatedata would be useful for us...thanks!

**Comment by anamnavi** [comment]
It was also being checked for in V2 in PSScriptInfo comment block: https://github.com/PowerShell/PowerShellGetv2/blob/5aba7531f526b6e60b2757c36799995597b6dcec/src/PowerShellGet/private/functions/Get-PSScriptInfoString.ps1#L99
