### ISSUE TITLE
Add Get-PSScriptFileInfo cmdlet

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#762]
### Summary of the new feature / enhancement

As a user I want a `Get-PSScriptFileInfo` cmdlet to return a `PSScriptFileInfo` object from a specified script. This functionality was present in PowerShellGet v2 using the `Test-ScriptFileInfo` cmdlet.

**Comment by alerickson** [comment]
What if we added `-PassThru` on `Test-ScriptFileInfo`?  We can have discussions on keeping this as default behavior for `Test-ScriptFileInfo` as well.

**Comment by ThomasNieto** [comment]
I'd be fine with changing the default behavior for `Test-ScriptFileInfo` to return an object of the script info metadata. Then no `-PassThru` flag is needed or a new cmdlet. It also matches the behavior of `Test-ModuleManifest`.

**Comment by SydneyhSmith** [comment]
After some discussion, we determined that a `Get-PSScriptFileInfo` cmdlet is the best option this cmdlet would take a -Path parameter

**Comment by hrxn** [comment]
Hmm..

```PowerShell
PS C:\Windows\Temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\Temp> Test-ScriptFileInfo .\example.ps1

Version              Name                      Author               Description
-------              ----                      ------               -----------
1.0                  example                   hrxn.public@gmail.c… This is just an example script file...…

PS C:\Windows\Temp>
```

```PowerShell
PS C:\Windows\Temp> Get-Command Test-ScriptFileInfo

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Test-ScriptFileInfo                                2.2.5      PowerShellGet

PS C:\Windows\Temp>
```
:confused::question:
