### ISSUE TITLE
Update-PSScriptFileInfo and Update-ModuleManifest Verbs

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#766]
### Summary of the new feature / enhancement

`Update-PSScriptFileInfo` and `Update-ModuleManifest` both use the `Update` verb but the proper verb should be `Set`. The [PowerShell Verbs](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7.2) documentation have the following definitions.

Update
> Brings a resource up-to-date to maintain its state, accuracy, conformance, or compliance.

Set
> Replaces data on an existing resource or creates a resource that contains some data.

These two cmdlets set data on a resource in this case the script file info and module manifest respectively. They do not change state of a resource as update is intended for. `Update-PSResource` is a good example of the proper use of the update verb since it changes the state of the machine to bring it up-to-date. An alias can be added to [CompatPowerShellGet](https://github.com/PowerShell/CompatPowerShellGet) to avoid breaking changes.

**Comment by SydneyhSmith** [comment]
Thanks Thomas, curious if @JamesWTruher has a perspective on this one

**Comment by adityapatwardhan** [comment]
@ThomasNieto I was looking at fixing this issue and realized that `Update` might actually be the correct verb.

I would love to hear your thoughts about this.

Update suits current implementation of cmdlets because:

1. If the file does not exist, it does not create it (set requires to create it if it does not exist)

```
PS> Update-PSScriptFileInfo -Path D:\temp\abc.ps1 -CompanyName ddd -Version 1.0.0
Update-PSScriptFileInfo: Cannot find path 'D:\temp\abc.ps1' because it does not exist.
```

2. If only 1 property is changed, the other properties are not affected and the values are preserved. As you can see the description "test" was not overwritten.

```
PS> New-PSScriptFileInfo -Path "D:\temp\test_script.ps1" -Version '1.0.0.0' -Description 'test'
PS> Update-PSScriptFileInfo -Path "D:\temp\test_script.ps1" -Version '3.0.0.0'
<#PSScriptInfo

.VERSION 3.0.0.0

.GUID 249ad3ca-016b-4e1c-9cf4-469960eec436

.AUTHOR adity

.COMPANYNAME

.COPYRIGHT

.TAGS

.LICENSEURI

.PROJECTURI

.ICONURI

.EXTERNALMODULEDEPENDENCIES

.REQUIREDSCRIPTS

.EXTERNALSCRIPTDEPENDENCIES

.RELEASENOTES


.PRIVATEDATA


#>
<#

.DESCRIPTION
test

#>
```

**Comment by JamesWTruher** [comment]
while `Set` is certainly applicable, `Update` in this particular case is probably more appropriate, especially with regard to these tools _not_ creating the resource if it does not exist. `Update` assumes the existence of a resource while `Set` does not.

**Comment by ThomasNieto** [comment]
While most `Set` commands do create the resource if it does not exist it is not required to do so. In the PowerShell verbs doc there is a reference to `New` vs `Set` and in that section it mentions that `Set` can optionally create the resource if it does not exist.

> Use the New verb to create a new resource. Use the Set verb to modify an existing resource, **optionally creating it if it does not exist,** such as the Set-Variable cmdlet.

**Comment by adityapatwardhan** [comment]
Considering both of your responses, I think Update still fits better as it signifies the resource must exist. Also, Set-Variable seems to be creating the variable if it does not exist.
