### ISSUE TITLE
Proxy support is needed 

### ISSUE THREAD

**Issue by SydneyhSmith** [PowerShell/PSResourceGet#770]
### Summary of the new feature / enhancement

Proxy support is needed for the following cmdlets
-  Install
 - Update 
 - find
 - Save
 - Publish

**Comment by mgreenegit** [comment]
Suggest holding this item for after GA

**Comment by mgreenegit** [comment]
Suggest we hold this for post-GA and document workaround
https://github.com/PowerShell/PowerShellGet/issues/244#issuecomment-1031838955

**Comment by alerickson** [comment]
@mgreenegit just fyi v2 has proxy support so to be backwards compatible we should probably have some documentation out for GA

**Comment by SydneyhSmith** [comment]
closing in favor of #244
