### ISSUE TITLE
Resetting user password

### ISSUE THREAD

**Issue by mwpreston** [PowerShell/PSResourceGet#777]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Try and reset the password ;)

### Expected behavior

```console
Password gets reset
```

### Actual behavior

```console
I understand that this probably isn't the right spot but I've sent emails to the support email on the gallery to no end and received no response.

I'm trying to reset a password for a user, I enter in the username, the recovery email, but receive no email.  Can anyone point me to someone who might be able to help out in this case?
```

### Environment data

```powershell
website
```

**Comment by SydneyhSmith** [comment]
@mwpreston could you please send an email to cgadmin@microsoft.com
