### ISSUE TITLE
Provide parameter SkipModuleValidation in Update-ModuleManifest to skip verifying required modules whether installs in environment

### ISSUE THREAD

**Issue by BethanyZhou** [PowerShell/PSResourceGet#789]
### Summary of the new feature / enhancement

Please provide a parameter named "SkipModuleValidation" or something similar to let user skip verifying required modules whether installs in local.

I have a rollup psd1, which contains around 70 required modules. I want to update its version and release notes in each release by  Update-ModuleManifest. I will update this psd1 by ADO agent, which means environment is clear and empty each time. I don't want to install all required modules in environment each time. It's time-consuming. 

Is it possible to let us skip the installation verification just check whether its syntax is correct and go ahead to update information?

**Comment by mgreenegit** [comment]
This is a great idea but since it could be manually worked around, I would propose we address it after GA.

**Comment by alerickson** [comment]
@mgreenegit Paul has a PR out for -SkipModuleValidation in `Publish-PSResource` so he was just going to add that in for `Update-ModuleManifest` (a quick add)  #892

**Comment by PaulHigin** [comment]
PowerShellGet V3 `Update-ModuleManifest` (soon to be renamed to `Set-ModuleManifest`) does not run `Test-ModuleManifest` on the updated manifest file like PowerShellGet V2 does.  So there is no need for a `-SkipModuleValidation` parameter.
