### ISSUE TITLE
Enable PowerShellGet Telemetry on PS Core using AppInsights API

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PSResourceGet#80]
We need to use AppInsights API to enable PowerShellGet telemetry on PS Core as PowerShell Telemetry APIs got removed in PowerShell Core beta builds.

**Comment by ThomasNieto** [comment]
@SydneyhSmith is this ticket still needed with this PR: https://github.com/PowerShell/PowerShell/pull/19926
