### ISSUE TITLE
Update-help cmdlet broken in PS 7.2.6 (macOS) 

### ISSUE THREAD

**Issue by yashcrest** [PowerShell/PSResourceGet#811]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I am experiencing issue with the Get-Help cmdlet in PS core 7.2.6 ( macOS). I have installed powershell via HomeBrew in MacBook Air M1 ( v12.6) . 

Whenever I try to run the help cmdlet to get some examples for particular cmdlets. I get this: 

`REMARKS
    Get-Help cannot find the Help files for this cmdlet on this computer. It is 
    displaying only partial help.
        -- To download and install Help files for the module that includes this 
    cmdlet, use Update-Help.
        -- To view the Help topic for this cmdlet online, type: "Get-Help 
    Find-Module -Online" or
           go to https://go.microsoft.com/fwlink/?LinkID=398574.`

### Expected behavior

```console
It was suppose to return the examples of how to use the Find-Module command instead it gives back. 

Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help. -- To download and install Help files for the module that includes this cmdlet, use Update-Help. -- To view the Help topic for this cmdlet online, type: "Get-Help Find-Module -Online" or go to https://go.microsoft.com/fwlink/?LinkID=398574.
```

### Actual behavior

```console
Get-Help cannot find the Help files for this cmdlet on this computer. It is displaying only partial help. -- To download and install Help files for the module that includes this cmdlet, use Update-Help. -- To view the Help topic for this cmdlet online, type: "Get-Help Find-Module -Online" or go to https://go.microsoft.com/fwlink/?LinkID=398574.
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-D…

Key   : PSVersion
Value : 7.2.6
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.2.6
Name  : GitCommitId


Key   : OS
Value : Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; 
        root:xnu-8020.140.49~2/RELEASE_ARM64_T8101
Name  : OS


Key   : Platform
Value : Unix
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

**Comment by alerickson** [comment]
Did you try running `Get-Help Find-PSResource -Examples` to see examples or `Get-Help Find-PSResource -Full` to see all help info?  
Please make sure you're running the [latest prerelease](https://www.powershellgallery.com/packages/PowerShellGet/3.0.17-beta17) version as well.  

If you're still running into issues, please send us step by step the full commands you're running.

**Comment by yashcrest** [comment]
Hi @alerickson , 
Thanks for your input. 

Yes I am running the latest version of PowerShellGet Module. However, I am still getting the same result while running  Get-help Command. 

Here is the screenshot of it. 
<img width="1680" alt="Screen Shot 2022-10-13 at 7 38 12 pm" src="https://user-images.githubusercontent.com/79971012/195554458-8c5d9009-6a8e-4e75-aafb-79688f8badc3.png">

I also tried to run the `Update-help -Verbose` to see what is happening while updating the help module. It seems my connection is only being redirected but the module itself is not being updated . 
<img width="1548" alt="Screen Shot 2022-10-13 at 7 50 40 pm" src="https://user-images.githubusercontent.com/79971012/195561810-15ac06c6-5a20-4228-b417-99ae64805abc.png">

Anyway, I gave it another shot and ran  the Get-help command. But unfortunately, got the same result. 

![Uploading Screen Shot 2022-10-13 at 7.50.58 pm.png…]()

**Comment by anamnavi** [comment]
@yashcrest what version of PSGet are you using? We are no longer working on PowerShellGet V2, could you try using the latest preview of PowerShellGet V3: https://www.powershellgallery.com/packages/PowerShellGet/3.0.17-beta17 and let us know if this issue is still occurring for you? This is working for us in PowerShellGet V3.

**Comment by yashcrest** [comment]
@anamnavi thanks for your input. I did as you said and installed the latest preview of PSGet (3.0.17 beta 17). But unfortunately I am still getting the same result. 

<img width="1680" alt="Screenshot 2022-10-25 at 4 45 28 pm" src="https://user-images.githubusercontent.com/79971012/197696757-b7c03c93-19b5-4f6e-bd89-6af898ae4556.png">

**Comment by yashcrest** [comment]
Hi @anamnavi, could I please get an update for this ?

**Comment by alerickson** [comment]
@yashcrest The cmdlets have different names for PowerShellGet 3.0 and above.  Once the module is imported (`Import-Module PowerShellGet "3.0.17-beta17"`) you can run the equivalent cmdlets, `Get-Help Find-PSResource -examples`

**Comment by yashcrest** [comment]
Thanks @alerickson, that worked. Could you guide me to a documentation of all the changed cmdlets in PowerShell 7.
