### ISSUE TITLE
Publish-PSResource flatten folder and file structure

### ISSUE THREAD

**Issue by MVKozlov** [PowerShell/PSResourceGet#837]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

`Publish-PSResource -Credential $Cred -Repository $Repo -Path $Path`
`$Path` contains file tree but publish flatten it in nupkg

The problem triangled in #704
https://github.com/PowerShell/PowerShellGet/commit/270d57e7d86bb49735f35ee172b33050ad193e8b#diff-56bf43952db65da3734ae9fabbe720248ec3a4d18d87ee94ec8ce2b91bce4af1
line  354-359 vs 400-402
``` diff
- var fileName = fileNamePath.Substring(_path.Length).Trim(_PathSeparators);
- var newFilePath = System.IO.Path.Combine(outputDir, fileName);
+ FileInfo fileInfo = new FileInfo(fileNamePath);
+ var newFilePath = System.IO.Path.Combine(outputDir, fileInfo.Name);
```
new one does not respect relative file path, only file name

### Expected behavior

```console
folder/file structure preserved
module.psd1
file1.ps1
public/
  file2.ps1
private/
  file3.ps1
```

### Actual behavior

```console
public/
private/
module.psd1
file1.ps1
file2.ps1
file3.ps1
```

### Environment data

```powershell
Version    Name
-------    ----
3.0.17     PowerShellGet

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MVKozlov** [comment]
btw, v2 by default skip hidden files/folder such as `.git` , v3 is not

**Comment by alerickson** [comment]
@MVKozlov thanks for opening this issue!  We'll try to get this fix in for our next release.

**Comment by MVKozlov** [comment]
@alerickson, I hope skipping hidden files/folders will be done too

**Comment by PaulHigin** [comment]
I also see this behavior.  It breaks publishing `PowerShellGet` because our own module expects binaries to be in a subdirectory (`netstandard2.0`), so after publishing then installation, the PowerShellGet module does not work.

**Comment by MVKozlov** [comment]
@alerickson
To skip hidden directories and files I would use a strategy like this
1. Check attributes and don't create hidden directories
2. When adding files, check for the existence of the destination directory (and file attributes, of course, too)

**Comment by alerickson** [comment]
@MVKozlov I'm going to close this issue because the original issue (in title) is resolved.  Feel free to open a new issue regarding skipping hidden directories and we can continue that conversation.  Thanks!
