### ISSUE TITLE
Get-InstalledModule creates empty folder in $env:UserProfile\Documents

### ISSUE THREAD

**Issue by odonyde** [PowerShell/PSResourceGet#838]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

All PowerShell modules on the system are installed for the `AllUsers` scope (`Install-Module -Name $moduleName -Scope AllUsers`) and no PowerShell folder is existent in `$env:UserProfile\Documents`.

Executing `Get-InstalledModule $moduleName` for the first time in a new PowerShell instance creates an empty folder `PowerShell\Scripts\InstalledScriptInfos` in `$env:UserProfile\Documents`.

Subsequent calls of `Get-InstalledModule $moduleName` from the same PowerShell instance do not recreate this folder in case it has been manually deleted.

### Expected behavior

```console
`Get-InstalledModule` does not create any folder in `$env:UserProfile\Documents`.
```

### Actual behavior

```console
`Get-InstalledModule` creates an empty folder `PowerShell\Scripts\InstalledScriptInfos` in `$env:UserProfile\Documents`.
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Fin…

Key   : PSVersion
Value : 7.2.7
Name  : PSVersion

Key   : PSEdition
Value : Core
Name  : PSEdition

Key   : GitCommitId
Value : 7.2.7
Name  : GitCommitId

Key   : OS
Value : Microsoft Windows 10.0.22621
Name  : OS

Key   : Platform
Value : Win32NT
Name  : Platform

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

**Comment by odonyde** [comment]
Workaround to clean up folder `$env:UserProfile\Documents\PowerShell` after running `Get-InstalledModule`:
```pwsh
$ghostFolderPath = "$env:UserProfile\Documents\PowerShell"
if (Test-Path $ghostFolderPath) {
    Remove-Item $ghostFolderPath -Recurse
}
```
For sure this is just applicable if the PowerShell folder in the user's documents folder is not used for any other purposes (e.g. to store modules with scope `CurrentUser`).

**Comment by alerickson** [comment]
@odonyde the version of PowerShellGet you're using is 2.2.5.  We have a separate repository for all versions of [PowerShellGet below 3.0](https://github.com/powershell/powershellgetv2) and we are no longer making changes to that repository.  This repository is a complete rewrite of the other.  We don't believe that this issue repros in the latest versions of PowerShellGet.  Please let us know if you're still experiencing this issue in the latest release [3.0.17-beta17](https://www.powershellgallery.com/packages/PowerShellGet/3.0.17-beta17).

**Comment by odonyde** [comment]
Hello, @alerickson! Thanks for your reply.

I followed your suggestion and installed the latest beta version of PowerShellGet using `Install-Module -Name PowerShellGet -Scope AllUsers -AllowPrerelease -Force`. Running `Get-Module -ListAvailable PowerShellGet | Select-Object Name, Version` now shows:
```pwsh
Name          Version
----          -------
PowerShellGet 3.0.17
PowerShellGet 2.2.5
PowerShellGet 1.0.0.1
```
Opening a new shell and running `Import-Module -Name PowerShellGet -MinimumVersion 3.0.0 -PassThru` confirms that the latest module version gets imported:
```pwsh
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.17     beta17     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceR…
```
Unfortunately, the subsequent execution of `Get-InstalledModule` still recreates an empty folder `PowerShell\Scripts\InstalledScriptInfos` in `$env:UserProfile\Documents`. So it seems the issue still persists in version 3 of PowerShellGet.

Let me know if there are any other tests I could perform.

**Comment by anamnavi** [comment]
@odonyde thanks for installing and trying to repro this with PowerShellGet V3. I should note that the cmdlets in PowerShellGetV3 are a bit different, so `Get-InstalledModule` would be `Get-PSResource`. So if you can run `Get-PSResource -Name "PowerShellGet"` and let us know if this still repro's with PowerShellGetV3 that would be really helpful, thanks!

**Comment by odonyde** [comment]
@anamnavi Ahh, I see. I can confirm that running `Get-PSResource -Name "PowerShellGet"` does not create any folder in `$Env:UserProfile\Documents`. 👍 But it also does not return anything. I had to add parameter `-Scope AllUsers` to retrieve the installed PowerShellGet v3 module. Is the default scope limitation of `Get-PSResource` intentional? This would be different from PowerShellGet v2's `Get-InstalledModule`, which lists all available modules by default.

**Comment by anamnavi** [comment]
@odonyde thanks for testing this with PowerShellGet V3. And yes, this behavior is different than Get-InstalledModule. Since you had installed the module with `-Scope AllUsers` (in your first post), when running `Get-PSResource` you have to add `-Scope AllUsers` to see the module installed with that scope.

**Comment by odonyde** [comment]
Ok, thanks for the explanation, @anamnavi.
