### ISSUE TITLE
Unable to upload powershell module DellBIOSProvider version 2.7.0

### ISSUE THREAD

**Issue by dellclientopensource** [PowerShell/PSResourceGet#847]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

![PowerShell_Gallery_Error_DellBIOSProvider](https://user-images.githubusercontent.com/82802072/199681791-68ac13c0-c5b0-4ef5-aeda-09282e4b6045.png)

Trying to upload DellBIOSProvider new version 2.7.0
Account is dcpp.dell@outlook.com

### Expected behavior

```console
DellBIOSProvider 2.7.0 should be uplaoded.
```

### Actual behavior

```console
getting nuget error
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.436
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.436
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by anamnavi** [comment]
@dellclientopensource thanks for reaching out, I tested publishing with my API Key and couldn't repro this. Could you check your key expiry date for me?

To see if the existing API Key associated with the account has expired, go to powershellgallery.com > sign in with the account associated with the package > click on your username > API Keys > Manage > for each key it should show expiry date.

To create a new API Key, go to powershellgallery.com > sign in with the account associated with the package > click on your username > API Keys > Create > make sure to select the package DellBIOSProvider

**Comment by anamnavi** [comment]
working on this offline with DellBiosProvider team.
