### ISSUE TITLE
1 second delay due to retry occurs on every query

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#848]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Upstream issue: https://github.com/NuGet/Home/issues/12195

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

```powershell
N/A
```

**Comment by anamnavi** [comment]
Thanks for letting us know about this issue, this should be resolved once we move off the NuGet client APIs and onto the HTTP REST based APIs, following issue #653
