### ISSUE TITLE
Get-PSResource -Scope AllUsers should return both CurrentUsers and AllUsers

### ISSUE THREAD

**Issue by alyssa1303** [PowerShell/PSResourceGet#868]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

`Get-PSResource -Scope AllUsers` should return resources installed for both CurrentUsers and AllUsers

### Expected behavior

```console
Get-PSResource -Scope AllUsers returns resources installed for both CurrentUsers and AllUsers
```

### Actual behavior

```console
Get-PSResource -Scope AllUsers only returns resources installed for AllUsers
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.17     beta17     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceR…

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.25236
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

<img width="867" alt="error" src="https://user-images.githubusercontent.com/49544763/203125044-9ec23df1-e8f1-4b66-a925-50c4b84caa84.png">

**Comment by anamnavi** [comment]
See similar: https://github.com/PowerShell/PowerShellGet/issues/860

**Comment by alerickson** [comment]
CurrentUser scope returns modules available to that user and AllUsers returns available to all users, this is by design.
