### ISSUE TITLE
`Find-PSResource` does not populate some fields that `Find-Module` used to populate in the result

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSResourceGet#878]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
$a = find-psresource hardwaremanagement
$b = find-module hardwaremanagement
```

### Expected behavior

```console
The two objects should contain the same information, although it's ok for the new version to have an actual .NET object like for `Includes`
```

### Actual behavior

```console
`AdditionalMetadata`, `CompanyName`, `Copyright`, `RepositorySourceLocation` are empty.

It's probably ok to not include `AdditionalMetadata` by default if it incurs more work on the server side as most users probably don't use it and have an additional switch `-IncludeAdditionalMetadata` to request it.
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.17     beta17     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceRepository, Install-PSResource…}
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability…}


Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anamnavi** [comment]
With the HTTP client request changes we will be able to populate those fields at Find time, but currently due to NuGet search APIs' limitations information on these metadata properties will not be accessible during the Find operation.

CompanyName and other metadata information is not easily accessibly via the json metadata (IPackageSearchMetadata object returned via NuGet GetSearchAsync() and GetMetadataAsync() search APIs) and currently is more operational cost than is worth to get this field.

Find-Module was able to do so because it was using OData queries. 

We can populate RepositorySourceLocation, so will fix that.

**Comment by mgreenegit** [comment]
Since this is already a breaking change, unless we have a known ask for RepositorySourceLocation, I would suggest we hold this for post-GA. We 100% need to document the behavior though, probably with a blog post as well.

**Comment by jdhitsolutions** [comment]
I will add my 2 cents about needing additional metadata, especially the PowerShellVersion value. In v2.x I could search for modules and see the minimum PowerShell version. I haven't found a way to get that information in v3.x. There is still a large base of Win5.1 users who need to be able to search and disregard modules or scripts that require v7.

Some of the other metadata values are helpful, but not nearly as important, I think, as the PowerShell version.,

**Comment by alerickson** [comment]
All of this has been added as of 3.0.21-beta21, with the exception of `CompanyName` since that's not provided from the server metadata.
