### ISSUE TITLE
`Find-PSResource` has `Includes` member that is essentially an empty object

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSResourceGet#879]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

```powershell
$a = find-psresource hardwaremanagement
$a.includes
```

### Expected behavior

```console
The exported functions, cmdlets, etc... to be shown.  If it's extra work on the server to get this info, then it's ok to have a new switch `-IncludeModuleExports` to make it explicit.
```

### Actual behavior

```console
Cmdlet         :
Command        : {}
DscResource    : {}
Function       :
RoleCapability :
Workflow       :
```

### Environment data

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.17     beta17     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceRepository, Install-PSResource…}
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability…}


Name                           Value
----                           -----
PSVersion                      7.4.0-preview.1
PSEdition                      Core
GitCommitId                    7.4.0-preview.1
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by anamnavi** [comment]
We will investigate and resolve this, thanks!

**Comment by mgreenegit** [comment]
This should be an easy fix but if it has any risk, I suggest we hold until after GA. It contains no data, so it should not break anyone to remove later (obviously we should document and blog it).

**Comment by alerickson** [comment]
This issue is related to #676 so I'll tackle this now to resolve the other issue.

**Comment by alerickson** [comment]
Upon trying to repo this issue and debugging how the includes object is created, it looks like this not actually a bug.  In the original repro example "HardwareManagement" actually doesn't include any Cmdlets, Commands, DscResources, Functions, RoleCapabilities, or Workflows, which is why the object is empty.  If you try to repro this by searching for a module like "PowerShellGet" or "PowerCD", the includes object gets populated properly.

Going to close this as resolved.
