### ISSUE TITLE
Give some way to configure psrepos via GPO or other method

### ISSUE THREAD

**Issue by dotps1** [PowerShell/PSResourceGet#88]
We use an internal NuGet feed to host a lot of our module/scripts for people in IT.  but everytime they get on a new box, they need to register that repo, which is very cumbersome, it would be nice if the PSRepository was not stored in CLIXML because that makes it pretty cumbersome to try and deploy those settings.  i guess a logon script to be used, but that seems like the wrong direction to go to accomplish this.

## Expected Behavior

maybe allow to have a machine targeted repo, similar to how powershell profiles work, where we can deploy an internal default PSRepo to machines.

## Current Behavior

currently the PSRepository is user based, so this makes it hard to setup an internal repo on multipule machines.

## Possible Solution

see expected behavor

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

as we publish more our scripts and build internal modules, that cannot be published publicaly, i need a way to configure our internal repo on all machines.  so users can use install/find-module/script OOB.

## Your Environment

```PowerShell

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

> Get-Module

> Get-Module -ListAvailable PowerShellGet,PackageManagement

> Get-PackageProvider

> Get-PackageProvider -ListAvailable
```

**Comment by mwtrigg** [comment]
> Of course `-SystemWide` is perhaps not the best name for something like this. But via a single swithc on the **Register-PsRepository** cmdlet would be really a helpfull feature IMHO.

Indeed, `-Global` is the probably the preferred option, to align with other related cmdlets and functions.

**Comment by SchulteMK** [comment]
any updates during the last two years?

**Comment by KeysAU** [comment]
Also interested in 2023!

**Comment by alerickson** [comment]
We now have Group Policy configurations integrated with PSResourceGet in the latest preview release: https://www.powershellgallery.com/packages/Microsoft.PowerShell.PSResourceGet/1.1.0-RC2
