### ISSUE TITLE
Publish-PSResource should skip hidden files/folders as v2 do

### ISSUE THREAD

**Issue by MVKozlov** [PowerShell/PSResourceGet#888]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

`Publish-PSResource -Path D:\TestModule -DestinationPath D:\`

### Expected behavior

```console
# TestModule.1.0.0.0.nupkg should not contain .git folder or other hidden files/folders
```

### Actual behavior

```console
# TestModule.1.0.0.0.nupkg contains .git folder and all git content and other hidden files/folders
```

### Environment data

```powershell
ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Binary     3.0.18     beta18     PowerShellGet

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by MVKozlov** [comment]
https://github.com/PowerShell/PowerShellGet/issues/837#issuecomment-1377195555

**Comment by alerickson** [comment]
We had some debate over whether we should assume the package owner does not want a hidden file to be published, but decided to not implement this at the moment.  Feel free to open if you disagree.

**Comment by MVKozlov** [comment]
@alerickson, Can't open again...
But I think v3 should default to v2's behavior (and might have some -AllowHidden flag or something like that)
Especially since such behavior greatly simplifies publishing from source (`git`, ci/cd )
