### ISSUE TITLE
Publish-PSResource fails with incorrect manifest file RequiredModules error

### ISSUE THREAD

**Issue by PaulHigin** [PowerShell/PSResourceGet#891]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Run `Publish-PSResource` cmdlet on a module for which its module manifest has a `RequiredModules` field, and ensure that at least one of the required modules is not installed on the machine (e.g., Microsoft.PowerShell.SecretStore).

The publish operation can be to any repo, including a local file base repo.

```powershell
Publish-PSResource -Path c:\temp\modules\Microsoft.PowerShell.SecretStore -Repository local_file_repo -SkipDependenciesCheck -Confirm:$false -Verbose
```

I **don't** believe this is related to issue (#883).

The problem is that `Publish-PSResource` uses PowerShell's `Test-ModuleManifest` cmdlet to validate the module manifest before publishing.  This is the wrong cmdlet to use because testing a module manifest is different from validating a module manifest.  A module manifest file may be valid but still not fully operational on a local machine (for instance if a required module is not installed), but this should not prevent a publish operation.

`Publish-PSResource` should perform only basics tests on the manifest file for validation and make no assumptions of machine state.  At minimum I feel `Publish-PSResource` should have a `-SkipManifestCheck` switch to bypass this problematic test.

### Expected behavior

```console
Microsoft.PowerShell.SecretStore module should be published to the local file repo.
```

### Actual behavior

```console
Publish operation fails with invalid module manifest error.
```

### Error details

```console
Publish-PSResource: Module manifest file validation failed with error: The specified RequiredModules entry
'Microsoft.PowerShell.SecretManagement' in the module manifest
'D:\temp\Modules\SecretStore\Microsoft.PowerShell.SecretStore\Microsoft.PowerShell.SecretStore.psd1' is
invalid. Try again after updating this entry with valid values.. Run 'Test-ModuleManifest' to validate the module
manifest.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by alerickson** [comment]
Resolved with #904
