### ISSUE TITLE
Better error messages when wrong credentials is used or wrong Uri is registered

### ISSUE THREAD

**Issue by rogermartensson** [PowerShell/PSResourceGet#914]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

Using GitLab NuGet repository version 3 that needs authentication to work.
Most of the messages says nothing about wrong credentials, missing credentials or even when wrong Uri is used.

Registered to GitLab using Register-PSResourceRepository, set up Credential object in an array to use.
Used Update-PSResource, Find-PSResource and Install-PSResource in a self-published package at our GitLab NuGet-repository.

### Expected behavior

```console
To get some sort of error that tells me I missed to use the -Credential switch, used wrong password or my Credential object was $null. Also a message if I've registered the wrong Uri or the Uri is changed after the Uri is registered making the repo inaccessible.

My issue is getting from no understandable errors to strange errors that most of the time is due to wrong credentials or something wrong with the registererd Uri
```

### Actual behavior

```console
One example when Using the wrong credential-object. I've forgot to set it.

The error that surfaced:

Install-PSResource: Package 'DemoModule' with requested version range '(, )' could not be found in any trusted repositories
```

Another error I got was:
```
Install-PSResource: Unable to successfully install package 'MiunVM': 'Could not find a part of the path...
```

When running with -verbose I found infamouse  retrieving resource from repository: Unable to load the service index for source....```

Before running in -verbose I tried Find-PSResource and there I get not complaing about wrong credentials. It just show some old listings from when I used working credentials. Adding -Verbose does not give any more information.
```


### Error details

_No response_

### Environment data

```powershell
PS C:\Program Files\PowerShell\Modules> Get-Module PowerShellGet; $PSVersionTable

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     3.0.18     beta18     PowerShellGet                       {Find-PSResource, Get-PSResource, Get-PSResourceR…

Key   : PSVersion
Value : 7.3.1
Name  : PSVersion


Key   : PSEdition
Value : Core
Name  : PSEdition


Key   : GitCommitId
Value : 7.3.1
Name  : GitCommitId


Key   : OS
Value : Microsoft Windows 10.0.22621
Name  : OS


Key   : Platform
Value : Win32NT
Name  : Platform


Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0…}
Name  : PSCompatibleVersions


Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion


Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion


Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion
```

**Comment by alerickson** [comment]
Thanks @rogermartensson for opening this issue!  We'll investigate and we're specifically curious if this is a GitLab issue or if it happens with other repositories as well.

**Comment by rogermartensson** [comment]
I do not know if this is a GitLab issue although my google-fu seems find mostly references to GitLab.
i believe it may be more of a authentication issue than a service provider issue. Maybe gitlab needs more authentication in the nuget v3-api than GitHub? 
I use mostly private repositories and that might also make the problem more visible.

One thing that I believe is GitLab specific is if you have a group of repositories you can get a nuget-uri for that group. That one I believe requires authentication.
