### ISSUE TITLE
Please setup Dependabot to keep dependencies updated

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#929]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I keep experiencing issues as a module I own has a dependency on `NuGet.Versioning` this causes issues since PowerShellGet also has that dependency and the versions mismatch. Please keep your dependencies up to date.

### Expected behavior

```console
Modules import without conflict
```

### Actual behavior

```console
Module assembly version conflict
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name          Version
----          -------
PowerShellGet 3.0.19
```

**Comment by SydneyhSmith** [comment]
Thanks @ThomasNieto great suggestion
