### ISSUE TITLE
Upon first install of PowerShellGet v3, there is no repository registered and getting bad error message

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PSResourceGet#93]
Installed PSGetv3 beta-1
Using any cmdlet includig get-PSResourceRepository returns:

```powershell
PS> Find-PSResource manage 
Find-PSResource: Was not able to successfully find xml
 PS>
Get-PSResourceRepository Get-PSResourceRepository: Was not able to successfully find xml 
```

Running `Register-PSResourceRepository -PSGallery` fixed the issue.  Seems like if there are no repositories registered, we should prompt if the user wants to register PSGallery.

**Comment by alerickson** [comment]
Addressed with release of 3.0.0-beta2
