### ISSUE TITLE
*-PSResourceRepository -Uri does not accept PSPath

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PSResourceGet#938]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

If you try to Register/Set a resource repository the `-Uri` parameter does not accept PSPath for example: `Temp:\repo`. I'd assume that Unix style paths also experience the same kind of issue.

Please add an argument transformation attribute to change the PS provider path to the full file system path that `-Uri` expects.

### Expected behavior

```console
Register-PSResourceRepository -Name Test -Uri 'Temp:\repo'
# works
```

### Actual behavior

```console
Register-PSResourceRepository -Name test -Uri 'Temp:\repo'
Register-PSResourceRepository: Invalid Uri, must be one of the following Uri schemes: HTTPS, HTTP, FTP, File Based
```

### Environment data

```powershell
Name          Version
----          -------
PowerShellGet 3.0.19

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by SydneyhSmith** [comment]
related to https://github.com/PowerShell/PowerShellGet/issues/939
