### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PSResourceGet#94]
When I try the install instructions from the blog post on v3p1, I get this:

![image](https://user-images.githubusercontent.com/5177512/77964413-3ce00380-729c-11ea-8cec-4e844a53ef47.png)

When I then restart PS and check my versions, I get this:

![image](https://user-images.githubusercontent.com/5177512/77964490-5b45ff00-729c-11ea-9199-05efb0ccf21c.png)

**Comment by rkeithhill** [comment]
BTW I got this to work in my case by removing a `PowerShellGet` user install of PowerShellGet and curiously one in `C:\Program Files\PowerShell\Modules`.

**Comment by SydneyhSmith** [comment]
Thanks, closing this issue as now resolved
