### ISSUE TITLE
Publish-PSResource does currently not work with Azure Artifacts

### ISSUE THREAD

**Issue by hemisphera** [PowerShell/PSResourceGet#969]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PowerShellGet)
- [X] Search the existing issues.

### Steps to reproduce

I tried to use PowerShellGet 3.0.0-beta19 for publishing a module to a Azure DevOps Artifacts feed.

At first I tried to register the feed using the `v2` endpoint. But I have seen that the cmdlet `Publish-PSResource` hardcoded adds `/package` to the URL, if it is a NuGet v2 endpoint, because the PowerShell gallery apparently uses this. But my Azure Artifacts feed does not have this and therefore the cmdlet fails with HTTP404.
The v2 endpoint for Azure Artifacts looks like this:
`https://pkgs.dev.azure.com/<org>/<project>/_packaging/<feedname>/nuget/v2/`

Then I tried to register the the PS Repository using the NuGet v3 endpoint. This however fails with this error message:
````
Publish-PSResource : Unable to load the service index for source https://pkgs.dev.azure.com/<org>/<project>/_packaging/<feedname>/nuget/v3/index.json.
````

Is there a preference which version I should use? Is this something that still needs implementing and is there a temporary workaround I can use in the meantime?

I am having a really hard time getting things to work with Azure Artifacts using PowerShellGet 2.x (older NuGet version, authentication, double repository registration) and therefore I'd prefer switchtig to PowerShellGet 3.x if possible.

### Expected behavior

```console
PowerShellGet should publish the package.
```

### Actual behavior

```console
Neither on the v2 nor on the v3 endpoint I seem to be able to publish the package.
```

### Error details

```powershell
Publish-PSResource : Unable to load the service index for source https://pkgs.dev.azure.com/<redacted>/<redacted>/_packaging/<redacted>/nuget/v3/index.json.
At line:1 char:1
+ Publish-PSResource -ApiKey <redacted> -Repository <redacted> -Path "C:\temp\psmod ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (:) [Publish-PSResource], ArgumentException
    + FullyQualifiedErrorId : PushNupkgError,Microsoft.PowerShell.PowerShellGet.Cmdlets.PublishPSResource
```

**Comment by SydneyhSmith** [comment]
Thanks @hemisphera were you having the same issue with Find and Install or just with Publish?

**Comment by hemisphera** [comment]
Haven't tried Find, but I have successfully installed a module by using Install. So I guess that one works fine.

I have tried to have a look at the code and it seems that the source that is passed along to the PushRunner does not get the credentials and therefore never authenticates. In fact: debugging traps a lot of HTTP401 exceptions.

**Comment by hemisphera** [comment]
@SydneyhSmith there seems to be no way for the Credentials to be passed along to to the `PushRunner` which is used to push the nupkg to the source. Therefore, the package source that is created inside the PushRunner is always created without credentials and fails to authenticate. 

When using Find or Install on the other hand, the `PackageSource` object is created by PowerShellGet and not by the NuGet SDK and therefore the Credentials are correctly passed along - and it works.

The only way to bypass this, I guess, is to inject the credentials into the `ISettings` object. I have tried that and using this approach I am able to correctly publish a module to a feed that requires authentication.

I have created a PR, even if I don't know if I'm supposed to because the readme clearly states that you do not accept PRs (beside tests).

**Comment by hemisphera** [comment]
I just now realized that this is actually a duplicate of #668.

**Comment by SydneyhSmith** [comment]
Thanks @hemisphera for the investigation and the PR, we have a major refactor of this cmdlet about to go out (beta 20), so after that we can retest this and see if the issue is resolved

**Comment by dbrennand** [comment]
Hey @SydneyhSmith 🙂  - Any news on beta 20 release? I'd love to see if this upcoming refactor fixes a similar issue I was having in https://github.com/PowerShell/PowerShellGet/issues/101#issuecomment-1227497001

**Comment by anamnavi** [comment]
We recommend publishing to AzureArtifacts with a V3 protocol URI for your repository. It's fixed now and -Credential with CredentialInfo value should work as of this next release.
